"""Cách làm Cá Chef viết lại (bằng lời riêng, giữ đúng trình tự, kỹ thuật, nguyên liệu) theo bài Cookpad đã chọn
ở data/de_xuat/cong_thuc_that_nguon.csv. CT[ma_mon] = (mô tả, [các bước]). Định lượng nằm ở cong_thuc_that.csv."""
CT = {'ba_chi_xao_kim_chi': ('Thịt ba chỉ xào lửa to cho xém cạnh rồi đảo cùng kim chi và nước kim chi, chua cay đậm đà.',
                        ['Thái ba chỉ lát mỏng, ướp với chút nước mắm và đường.',
                         'Chuẩn bị kim chi kèm thêm ít nước kim chi để xào.',
                         'Phi thơm tỏi băm, cho thịt vào xào nhanh lửa to đến khi hơi xém cạnh.',
                         'Thêm kim chi đảo đều cho thịt chín; nếu thích mềm thì cho nhiều nước kim chi và rim thêm một lúc.',
                         'Nêm thêm nước mắm và đường cho vừa rồi tắt bếp.']),
 'bi_ngo_non_xao_toi': ('Bí ngòi xào tỏi lửa to với mỡ, nêm nước mắm dầu hào, giòn ngọt và thơm hành hoa.',
                        ['Rửa sạch bí ngòi, bổ đôi rồi thái miếng dày 0,5 cm. Đập dập tỏi, cắt hành hoa thành khúc hơi dài.',
                         'Cho mỡ vào chảo nóng, phi thơm tỏi.',
                         'Đổ bí ngòi vào xào lửa to, nêm nước mắm, hạt nêm, dầu hào.',
                         'Khi bí gần chín, nêm chút mì chính, thả hành hoa vào đảo 30 giây rồi bày ra đĩa.']),
 'bo_bit_tet': ('Bò thái miếng dần mềm, ướp dầu hào, xì dầu, sốt BBQ, áp chảo rồi đun cùng sốt hành tỏi sánh.',
                ['Thái bò miếng mỏng bản to dày khoảng 0,5 cm, đập dẹt rồi dùng sống dao băm nhẹ cho mềm.',
                 'Ướp bò với hành tỏi băm, dầu hào, xì dầu, bột ngọt và sốt BBQ, để ngăn mát 6–8 tiếng.',
                 'Đun nóng dầu, áp chảo từng miếng bò đến khi chín vừa tới thì lấy ra; chắt riêng phần nước thịt tiết ra.',
                 'Rửa chảo, phi thơm hành tỏi băm, thêm dầu hào, xì dầu và sốt BBQ, rồi đổ bột ngô hòa nước vào đun sôi đến khi sánh.',
                 'Cho bò vào chảo sốt đun thêm 1–2 phút rồi xếp ra đĩa; dùng kèm khoai tây chiên và bánh mì.']),
 'bo_ham_dua_chua': ('Canh dẻ sườn bò hầm nhừ bằng nồi áp suất, nấu cùng dưa chua và cà chua, thơm ngò gai, rau ngổ.',
                     ['Cắt dẻ sườn bò thành khúc, phi thơm hành tỏi rồi cho bò vào đảo, nêm hạt nêm, bột canh và tiêu.',
                      'Đổ nước xăm xắp, đun sôi lăn tăn và hớt bọt, rồi hầm bằng nồi áp suất 35–40 phút cho bò nhừ.',
                      'Rửa dưa chua, cắt miếng; lột vỏ cà chua, thái múi cau. Phi thơm hành tím, cho dưa và cà chua vào đảo, nêm hạt nêm, '
                      'bột canh, thêm nước xăm xắp và đun 15 phút.',
                      'Cho bò vào nồi dưa, đun sôi đều 8–10 phút, thêm ngò gai và rau ngổ đảo qua rồi tắt bếp.']),
 'bo_ham_tieu_xanh': ('Nạm bò ướp tiêu xanh hầm với nước dừa, khoai tây, cà rốt, dầu điều, cay thơm, ăn kèm bánh mì.',
                      ['Phi hạt điều màu trong dầu nóng, đảo đến khi dầu đỏ đậm thì tắt bếp.',
                       'Cắt thịt bò miếng khoảng 4x3cm, ướp với tiêu xanh giã nhuyễn, tỏi băm, dầu ăn, hạt nêm, tiêu đen và muối khoảng 30 '
                       'phút.',
                       'Cắt cà rốt khoanh dày khoảng 1cm; cắt khoai tây khối rồi chiên sơ vàng mặt; cắt hành tây múi cau; giã sơ tiêu xanh '
                       'còn nguyên cành.',
                       'Phi thơm tỏi và tiêu xanh với dầu, cho cà chua hộp hoặc tương cà vào xào khoảng 1 phút.',
                       'Cho bò vào xào săn rồi đổ nước dừa vào, nấu lửa vừa đến khi sôi thì thêm cà rốt, khoai tây, tiêu đen và nêm vừa '
                       'ăn.',
                       'Nấu đến khi bò và rau củ mềm, hớt sạch bọt, cho hành tây và dầu điều vào, sôi thêm 3 phút thì tắt bếp.']),
 'bo_tai_chanh': ('Bò thái mỏng nhúng nước sôi vừa chín tới, thêm giá, hành lá, tiêu và vắt chanh hoặc tắc.',
                  ['Rửa sạch thịt bò, thái lát mỏng; cắt hành lá khúc khoảng 1 cm.',
                   'Đun sôi nước, cho bò vào, nêm chút muối và đường.',
                   'Khi bò vừa chín tới thì tắt bếp, cho hành lá, giá và tiêu xay vào.',
                   'Vắt nước chanh hoặc tắc vào nồi, nêm lại cho vừa rồi dùng ngay.']),
 'bo_xao_dua_chua': ('Thịt bò ướp gừng tỏi, dầu hào xào cùng dưa chua và cà chua, chua nhẹ đậm vị, để được lâu ăn dần.',
                     ['Thái thịt bò, ướp với tỏi, gừng thái nhỏ, muối, hạt nêm, xì dầu và dầu hào.',
                      'Phi gừng và tỏi với dầu đến khi vàng nâu thơm, cho bò vào đảo tái rồi trút ra bát.',
                      'Dùng nồi đó xào cà chua trước rồi thêm dưa chua, xào một lúc thì cho bò vào đảo.',
                      'Xào đến khi chín đều, ngấm gia vị thì tắt bếp, cho hành tươi và tiêu vào trộn đều.',
                      'Để nguội rồi cất tủ lạnh, dùng dần.']),
 'bo_xao_kho_qua': ('Thịt bò thái mỏng xào nhanh với khổ qua bào lát, đắng nhẹ, thơm tỏi và tiêu.',
                    ['Thái thịt bò lát mỏng, ướp với dầu ăn và bột ngọt.',
                     'Rửa sạch khổ qua, bỏ ruột, bào mỏng để ráo; cắt nhỏ hành lá.',
                     'Phi thơm tỏi đập dập với dầu, cho thịt bò vào xào sơ.',
                     'Cho khổ qua vào xào 5 phút, thêm hành lá, nêm hạt nêm và đường, đảo đều 1 phút rồi nhấc xuống.',
                     'Bày ra đĩa, rắc tiêu lên trên.']),
 'bo_xao_ot_chuong': ('Bắp bò xào chín tới cùng ớt chuông, hành tây và dầu hào, màu sắc tươi, thơm tỏi phi.',
                      ['Phi thơm tỏi băm, cho bắp bò thái lát vào xào, nêm nước tương, hạt nêm, tiêu; bò chín tới thì trút ra đĩa.',
                       'Cắt ớt chuông và hành tây thành khối vuông, cho vào chảo xào với dầu hào, thêm chút nước cho rau củ mau chín.',
                       'Cuối cùng thêm hành lá cắt nhỏ, đảo đều.',
                       'Gắp rau củ ra đĩa cùng thịt bò, rắc tiêu xay và tỏi phi.']),
 'bo_xao_thien_ly': ('Thịt bò ướp tỏi tiêu xào lửa to cùng hoa thiên lý, mềm ngọt, thơm mùi hoa.',
                     ['Rửa sạch hoa thiên lý; thái mỏng thịt bò.',
                      'Ướp bò với tỏi băm, tiêu, đường, bột canh, nước mắm và mì chính, trộn đều để 10-15 phút.',
                      'Phi thơm tỏi với dầu ăn trên lửa to, cho thịt bò vào đảo đến khi chín tái.',
                      'Cho hoa thiên lý vào đảo đều, nêm thêm bột canh vừa ăn rồi tắt bếp.']),
 'ca_bac_ma_kho_tieu': ('Cá bạc má kho nhỏ lửa với dưa chua, mỡ ba chỉ, riềng, tiêu và kẹo đắng đến khi cạn nước, xương mềm, đậm vị.',
                        ['Rửa sạch cá bạc má, cắt bỏ đầu và đuôi. Lọc lấy phần mỡ của thịt ba chỉ.',
                         'Cho cá, thịt và dưa chua vào nồi, thêm tiêu, nước mắm, riềng băm và kẹo đắng, xóc đều rồi để khoảng 10 phút cho '
                         'ngấm.',
                         'Đổ nước dưa chua vào vừa xăm xắp mặt cá, có thể thêm hành khô bóc vỏ cho thơm.',
                         'Kho lửa nhỏ khoảng 30-45 phút, tốt nhất trên bếp than, đến khi nồi cá cạn nước thì nhấc xuống.',
                         'Bày ra đĩa, trang trí chút rau mùi, dùng nóng với cơm.']),
 'ca_bop_kho_tieu': ('Cá bớp kho cùng thịt ba rọi trong sốt kho, kho hai lần cho sốt sệt, cay thơm tiêu xay.',
                     ['Ướp cá và thịt với sốt kho trong 15 phút.',
                      'Bắc lên bếp đun sôi, hạ lửa liu riu 15 phút rồi tắt bếp.',
                      'Để nguội 30 phút, sau đó kho lại đến khi sốt sệt.',
                      'Rắc tiêu xay, ăn kèm cơm.']),
 'ca_chep_om_dua': ('Cá chép ướp nghệ, chiên sơ rồi om cùng dưa cải, ba rọi, cà chua, đậu hũ, chua dịu, thơm thì là.',
                    ['Làm sạch cá (để vảy), ngâm 10 phút trong nước pha muối và nước dưa cải rồi rửa lại. Thái ba rọi, cắt khúc thì là và '
                     'hành lá (đập dập phần gốc hành); xắt gừng, ép nước nghệ, băm hành tím, tỏi, ớt; rửa và xắt dưa cải.',
                     'Khứa cá mỗi bên hai đường, ướp với nước nghệ, đường, muối, hạt nêm, tiêu, bột ngọt và ớt băm khoảng 10 phút.',
                     'Chiên sơ cá trong mỡ nước đến khi hơi vàng hai mặt rồi vớt ra; cho ba rọi vào xào đến khi săn và rám vàng thì vớt '
                     'ra.',
                     'Phi thơm hành tím, tỏi, gốc hành, gừng, bã nghệ và ớt trong mỡ nước; cho dưa cải vào xào săn, thêm thịt và phần nước '
                     'ướp cá còn lại, đảo đều.',
                     'Đổ nước muối dưa, đặt cá vào cùng nước dừa tươi và nước sôi ngập cá; sôi thì hạ lửa nhỏ om, hớt bọt thường xuyên, '
                     'khoảng 10 phút thì trở mặt cá.',
                     'Khi cá vừa chín, thêm cà chua và đậu hũ chiên, nêm đường, bột ngọt, nước mắm và giấm bỗng, om thêm khoảng 5 phút.',
                     'Rải hành lá, thì là, rắc tiêu rồi tắt bếp; dùng nóng với cơm hoặc bún, kèm nước mắm ớt.']),
 'ca_chuon_kho_man': ('Cá chuồn kho mặn với ớt, hành tím rồi om cùng mít non chiên sơ, mít thấm gia vị, rất đưa cơm.',
                      ['Luộc mít vừa chín, cắt miếng vừa ăn, chiên sơ với dầu.',
                       'Làm sạch ruột cá, rửa nước muối loãng, cắt đôi hoặc ba khúc, để ráo rồi ướp với muối và hành tím.',
                       'Phi hành tím với ớt bột, thêm nước vừa đủ và nước mắm; khi sôi xếp cá vào, hạ nhỏ lửa, cho ớt cắt lát, thỉnh '
                       'thoảng lật cá cho thấm rồi gắp cá ra.',
                       'Đổ nước kho cá sang chảo mít, thêm nước xâm xấp và nước mắm, kho lửa nhỏ cho mít thấm.',
                       'Khi mít chín vừa, đặt cá lên trên, đảo nhẹ tránh nát. Gắp ra đĩa, chan nước kho và rắc tiêu.']),
 'ca_dieu_hong_nuong_giay_bac': ('Cá điêu hồng ướp sốt xí muội, sa tế, gói giấy bạc cùng hành tây nướng 180–200 độ, đậm đà chua ngọt.',
                                 ['Rửa sạch cá. Trộn các loại gia vị và sốt thành hỗn hợp ướp, thoa đều lên cá, để thấm 2 giờ.',
                                  'Trộn hành tây và hành lá vào phần sốt ướp.',
                                  'Phết dầu lên mặt bóng của giấy bạc, cho sốt lên, đặt cá vào rồi gói kín.',
                                  'Nướng ở 180–200 độ khoảng 20 phút đến khi cá chín và giấy bạc phồng lên.',
                                  'Dùng kèm rau trộn dầu giấm và khoai tây chiên.']),
 'ca_dieu_hong_om_dua': ('Cá điêu hồng chiên sơ rồi om lửa liu riu với cải chua, cà chua, mẻ, nghệ và mắm tôm, chua thơm đậm đà.',
                         ['Làm sạch cá điêu hồng, cắt khúc hoặc để nguyên con rồi chiên sơ.',
                          'Phi thơm hành tím, tỏi và cà chua với dầu ăn, cho cải chua vào xào sơ.',
                          'Đổ nước lọc vào đun sôi, cho nghệ tươi để lấy màu, nêm đường, bột ngọt, Knorr, mẻ, mắm tôm và nước mắm cho vừa '
                          'ăn.',
                          'Cho cá vào om lửa liu riu khoảng 15-20 phút đến khi cá chín, nêm lại.',
                          'Khi ăn thêm thìa là, hành lá và chấm kèm nước mắm.']),
 'ca_dieu_hong_sot_ca_chua': ('Cá diêu hồng chiên vàng hai mặt rồi rim nhỏ lửa trong sốt cà chua sền sệt, ăn kèm rau sống.',
                              ['Đánh vảy cá, rửa với muối cho sạch nhớt. Cắt cà chua múi cau; rửa sạch hành lá và rau sống, để ráo.',
                               'Đun nóng dầu, chiên cá vàng đều hai mặt rồi gắp ra đĩa.',
                               'Chắt bớt dầu, cho cà chua vào xào, nêm hạt nêm, nước mắm và tiêu đến khi sốt sền sệt.',
                               'Cho cá vào chảo sốt, rim lửa nhỏ khoảng 5 phút.',
                               'Bày ra đĩa, rắc hành lá, ăn kèm rau sống.']),
 'ca_doi_kho_tieu': ('Cá đối nhỏ kho tiêu trong nồi đất với nước màu đường thắng, hành và ớt, kho lửa nhỏ lâu cho thấm.',
                     ['Băm nhỏ hành tím và ớt.',
                      'Cho dầu và đường vào nồi đất, đun đến khi đường chuyển màu cánh gián thì cho hành, ớt vào.',
                      'Xếp cá vào nồi, nêm nước mắm, hạt nêm, tiêu và kho lửa nhỏ 10 phút.',
                      'Thêm nước, kho tiếp khoảng 40 phút; kho lại nhiều lần thì cá càng ngon.']),
 'ca_duc_chien_gion': ('Cá đục ướp bột nêm, nước mắm, tiêu, áo bột chiên giòn và chiên lửa nhỏ, vỏ giòn thịt ngọt.',
                       ['Rửa cá bằng nước muối loãng, để ráo rồi thấm khô bằng giấy.',
                        'Ướp cá với bột nêm, nước mắm, tiêu hoặc ớt bột khoảng 10 phút, rồi rây bột chiên giòn lên cho bám đều.',
                        'Đun nóng dầu, cho vài lát gừng vào cho thơm và đỡ bắn dầu.',
                        'Chiên cá lửa nhỏ đến khi giòn đều mà không cháy.']),
 'ca_ho_chien_sa': ('Cá hố cắt khúc chiên với dầu phi tỏi đến vàng róc, chấm nước mắm hoặc tương xí muội.',
                    ['Làm sạch cá hố, cắt khúc khoảng 10 cm.',
                     'Phi tỏi trong dầu cho thơm, cho cá vào chiên đến khi một mặt vàng róc thì lật mặt còn lại.',
                     'Dùng kèm nước mắm hoặc tương xí muội.']),
 'ca_liet_chien_gion': ('Cá liệt nhồi sả ớt hành tỏi băm, nướng nồi chiên không dầu 200 độ trên giấy bạc, dai ngon không khô.',
                        ['Rửa sạch cá liệt, khía trên thân. Băm nhuyễn hành, tỏi, ớt và sả, trộn với đường, muối, nước mắm, bột ngọt và '
                         'dầu ăn.',
                         'Nhét phần lớn hỗn hợp ướp vào bụng cá, tránh để nhiều bên ngoài dễ cháy, ướp 15-30 phút.',
                         'Lót giấy bạc vào nồi chiên không dầu, chọc 3-4 lỗ cho nước chảy bớt rồi xếp cá vào.',
                         'Nướng mặt thứ nhất ở 200 độ C khoảng 25 phút, lật mặt nướng tiếp 200 độ C khoảng 20 phút, tùy cỡ cá.']),
 'ca_ro_phi_ran': ('Cá rô phi lăn bột chiên giòn hai mặt, rưới sốt nước mắm đường sệt và tỏi phi thơm.',
                   ['Rửa sạch cá, thấm khô rồi lăn qua bột chiên giòn không gia vị hoặc bột bắp.',
                    'Đun nóng dầu, chiên cá vàng giòn hai mặt, vớt ra để ráo dầu.',
                    'Phi thơm tỏi băm với ít dầu, vớt tỏi ra để riêng; cho nước mắm và đường vào chảo, khuấy đều đến khi sệt.',
                    'Rưới sốt mắm lên cá, rắc tỏi phi và ớt tươi lên trên; dùng với cơm nóng và rau luộc.']),
 'ca_trich_chien_gion': ('Cá trích ướp bột tỏi, áo bột chiên giòn rồi chiên vàng, ăn được cả xương, chấm nước mắm chanh ớt.',
                         ['Làm sạch cá trích, rửa qua muối và rượu cho hết tanh, khứa vài đường trên thân.',
                          'Ướp cá với bột tỏi, hạt nêm, bột ngọt và tiêu khoảng 30 phút.',
                          'Làm nóng dầu, lăn cá qua bột chiên giòn rồi thả vào chiên đến khi vàng giòn, vớt ra thấm dầu.',
                          'Pha nước mắm với ớt xắt lát và chút nước cốt chanh để chấm.']),
 'canh_bo_kim_chi': ('Canh kim chi thịt bò nấu nấm kim châm và đậu hũ non, chua cay nhẹ, ăn nóng với cơm.',
                     ['Thái thịt bò mỏng, ướp với hạt nêm, tiêu, dầu ăn trong 15 phút.',
                      'Cắt gốc nấm kim châm, ngâm nước muối loãng 15 phút, rửa sạch để ráo. Cắt nhỏ kim chi, boa rô, hành lá; cắt đậu hũ '
                      'non thành khối vuông.',
                      'Phi thơm boa rô với dầu, cho thịt bò vào xào lửa lớn đến khi chín rồi trút ra tô.',
                      'Đổ nước vào nồi, cho nấm kim châm nấu sôi 1 phút, thêm kim chi và nước kim chi, đun sôi lại.',
                      'Cho thịt bò vào, nêm hạt nêm, nước mắm, đường, bột ngọt; thêm đậu hũ non, đảo thật nhẹ tay, đun sôi lại, nêm vừa ăn '
                      'rồi tắt bếp.',
                      'Múc canh ra tô, rắc hành lá, ăn nóng với cơm.']),
 'canh_bo_nau_chua': ('Canh thịt bò nấu cải chua và cà chua, chua thanh, thơm rau răm, ngò gai và tỏi phi.',
                      ['Sơ chế sạch các nguyên liệu, để ráo.',
                       'Phi thơm tỏi với mỡ, vớt tỏi ra để riêng; cho cà chua vào xào chín.',
                       'Thêm cải chua và thịt bò vào xào cùng, rồi đổ nước sôi vào nấu.',
                       'Nêm nếm vừa ăn, thả hành, ngò, rau răm vào rồi múc ra tô, rắc tỏi phi lên trên.']),
 'canh_chua_ca_dieu_hong': ('Canh chua cá diêu hồng chiên sơ nấu cà chua, thơm, me, đậu bắp, bạc hà, vị chua ngọt thơm rau ôm.',
                            ['Bóp cá với muối giấm, rửa sạch rồi chiên sơ.',
                             'Cho cà chua cắt múi cau và thơm cắt lát vào nồi nước với chút muối, đun sôi.',
                             'Khi nước sôi, cho cá chiên, bạc hà, đậu bắp, giá và nước me vào; nêm nước mắm, đường cho vị chua ngọt.',
                             'Thêm rau ôm, ngò gai rồi tắt bếp. Múc ra tô, rắc tỏi phi và tiêu xay.']),
 'canh_dua_chua_nau_ca_loc': ('Cá lóc chiên săn nấu cùng dưa chua, cà chua, nghệ gừng, chua nhẹ thơm thì là.',
                              ['Làm sạch cá lóc, cắt khúc. Ngâm cá 10 phút trong nước ấm pha muối, rượu trắng, gừng rồi rửa lại với nước '
                               'sạch và muối cho hết tanh nhớt.',
                               'Chiên sơ cá cho săn.',
                               'Rửa dưa chua, bỏ nước ngâm; thái nhỏ cà chua, thì là; băm nhỏ tỏi, gừng, nghệ.',
                               'Phi thơm tỏi, gừng, nghệ, cho cà chua và dưa chua vào đảo đều, thêm nước rồi đun sôi.',
                               'Cho cá vào, nêm bột canh, mì chính, đường, ớt; hạ lửa liu riu nấu thêm 15–20 phút.',
                               'Tắt bếp, thêm thì là và nước mắm.']),
 'canh_ga_tan_hat_sen': ('Gà xào săn rồi hầm mềm cùng hạt sen, nấm đông cô, cà rốt và gói thuốc tiềm, nước canh ngọt thơm.',
                         ['Chặt gà miếng vừa ăn, ướp với bột ngọt, hạt nêm, tiêu, hành tím băm, đầu hành lá, đường trong 30 phút.',
                          'Ngâm nấm đông cô bằng nước sôi cho nở, rửa sạch. Gọt và cắt cà rốt; bỏ tim hạt sen cho khỏi đắng; ngâm và rửa '
                          'sạch gói nguyên liệu tiềm.',
                          'Phi thơm hành tím với dầu, cho gà vào xào săn rồi đổ nước vào nấu sôi, hầm đến khi gà mềm.',
                          'Cho nấm, cà rốt, hạt sen và nguyên liệu tiềm vào nấu chín mềm; nêm hạt nêm, bột ngọt, khuấy đều, nêm lại rồi '
                          'tắt bếp.',
                          'Múc canh ra tô, rắc hành lá và tiêu.']),
 'canh_kim_chi_thit_dau_phu': ('Canh kim chi thịt ba chỉ xào săn nấu cùng đậu phụ, chua cay đậm đà, thơm mè rang.',
                               ['Thái thịt ba chỉ lát nhỏ, mỏng, chần nước sôi khoảng 30 giây cho sạch. Thái mỏng hành tím.',
                                'Trộn thịt với một ít nước kim chi, nêm vừa miệng.',
                                'Phi thơm hành tỏi với ít dầu, cho thịt vào xào săn.',
                                'Đổ nước vào đun sôi rồi hạ lửa vừa; cho đậu phụ cắt khối nhỏ vào nấu đến khi chín.',
                                'Nêm lại vừa miệng, cho mè rang vào và đun thêm 5 phút ở lửa vừa.']),
 'canh_nam_kim_cham_thit_bam': ('Canh nấm kim châm với cà chua và thịt nạc xay vo viên dẻo, thanh ngọt, thơm hành tiêu.',
                                ['Cắt gốc nấm kim châm, ngâm nước pha chút muối khoảng 5 phút, rửa sạch, vắt ráo. Cắt cà chua múi cau.',
                                 'Ướp thịt nạc xay với hành tím băm, nước mắm, bột ngọt, tiêu, dầu ăn; trộn đều cho thấm rồi xay lại cho '
                                 'dẻo.',
                                 'Đun sôi nồi nước, cho cà chua vào, vo thịt thành viên thả vào nồi.',
                                 'Cho nấm kim châm vào nấu sôi, nêm vừa ăn rồi thêm hành lá và tiêu.']),
 'che_chuoi': ('Chè chuối già nấu nước cốt dừa với bột báng, thơm vani, rắc mè rang, ăn nóng hay lạnh đều ngon.',
               ['Lột vỏ chuối, bỏ phần quá chín rồi cho vào nồi nước. Rửa qua bột báng và ngâm cho nở.',
                'Cho nước cốt dừa vào nấu cùng chuối, thêm bột báng đã ngâm, sau cùng nêm đường theo khẩu vị.',
                'Khi chuối đã thấm nước cốt dừa thì tắt bếp, cho vani vào.',
                'Múc chè ra chén, rắc mè rang lên trên; dùng nóng hoặc lạnh.']),
 'chim_cut_ro_ti': ('Chim cút ướp dầu hào, ngũ vị, chiên vàng rồi rim nước dừa, phết mật ong giấm, kèm sốt từ nước rim.',
                    ['Rửa sạch chim cút, để ráo rồi thấm khô bằng giấy.',
                     'Trộn tiêu, ngũ vị hương, dầu hào, nước tương và tỏi băm thành hỗn hợp ướp; ướp cút, bọc kín và để tủ lạnh 1–2 tiếng '
                     '(hoặc qua đêm).',
                     'Đun nóng nhiều dầu, chiên cút đến khi vàng da hoặc vàng giòn.',
                     'Đun sôi nước dừa, cho cút cùng phần sốt ướp còn dư vào, rim nhỏ lửa.',
                     'Khi gần cạn, phết hỗn hợp mật ong và giấm lên cút, đun thêm chút rồi gắp cút ra.',
                     'Thêm chút nước và nước tương vào phần nước còn trong chảo, đun sôi làm sốt chấm kèm.']),
 'com_chien_kim_chi': ('Cơm chiên với tỏi, thịt rang, chả và kim chi, săn hạt, chua cay nhẹ.',
                       ['Phi thơm tỏi băm, cho cơm vào đảo đến khi săn.',
                        'Cho thịt rang và chả cắt nhỏ vào đảo đều.',
                        'Khi cơm săn, thêm kim chi cắt nhỏ, đảo lại cho thấm.',
                        'Cuối cùng cho hành lá cắt nhỏ vào đảo đều.']),
 'com_ga_hoi_an': ('Cơm nấu nước luộc gà với bột nghệ vàng óng, ăn kèm gà luộc, gỏi bắp cải và nước mắm gừng tỏi ớt.',
                   ['Nướng xém hành tây và gừng. Luộc gà với nước xâm xấp cùng hành tây, gừng nướng, gốc rau mùi, nêm hạt nêm.',
                    'Luộc khoảng 20–25 phút đến khi gà chín, vớt ra ngâm nước lạnh cho thịt săn; giữ lại nước luộc.',
                    'Bào sợi bắp cải, cà rốt; xé một phần thịt gà, trộn gỏi và nêm nước mắm, chanh, đường theo khẩu vị.',
                    'Vo sạch gạo, nấu với nước luộc gà và bột nghệ đến khi cơm chín.',
                    'Pha nước mắm tỏi ớt gừng. Lọc xương gà thái miếng hoặc chặt khúc, bày cùng cơm, gỏi và rau thơm.']),
 'ech_xao_mang_cay': ('Ếch ướp nghệ xào cùng đậu hũ, ba rọi chiên và măng chua, thơm lá lốt, tía tô, ngò gai.',
                      ['Ướp ếch với nghệ, muối, nước mắm và hạt nêm.',
                       'Chiên sơ đậu hũ và thịt ba rọi; rửa sạch măng chua, xé sợi.',
                       'Phi thơm hành tím, cho ếch vào xào cho thấm gia vị, thêm đậu và ba rọi, nêm vừa ăn rồi đảo khoảng 5 phút.',
                       'Cho măng vào xào tiếp, tắt bếp rồi thêm rau thơm và ớt, bày ra đĩa.']),
 'ga_kho_sa': ('Gà ta ướp sả, cà ri, dầu hào rồi kho với nước dừa tươi đến gần cạn, sém cạnh và đậm vị.',
               ['Rửa gà với muối và chút giấm.',
                'Ướp gà với hành tỏi băm, sả băm, đường, muối, bột cà ri, nước mắm, tiêu và dầu hào trong 15–30 phút.',
                'Đun nóng dầu, cho gà vào chiên đến khi sém cạnh.',
                'Đổ toàn bộ nước ướp và nước dừa tươi vào, đậy nắp khoảng 5 phút, thêm chút tương ớt cho lên màu.',
                'Kho đến khi gần cạn nước thì nêm lại cho vừa.']),
 'ga_rang_gung': ('Đùi gà ướp nước mắm, gừng, hành khô rồi rang săn và đun liu riu cho thấm, thơm lá chanh.',
                  ['Rửa đùi gà với muối, chặt hoặc lọc thịt rồi thái miếng vừa ăn. Gừng cạo vỏ, hành khô bóc vỏ, cả hai băm nhỏ.',
                   'Ướp gà với nước mắm, tiêu cùng một nửa phần gừng và hành khô khoảng 20–30 phút.',
                   'Phi thơm phần gừng và hành khô còn lại, cho gà vào rang đến khi săn thịt.',
                   'Thêm nước lọc, mì chính và chút nước mắm, đun thêm 15–20 phút đến khi gà chín, nêm lại cho vừa.',
                   'Tắt bếp, cho ớt và lá chanh thái sợi vào trộn đều.']),
 'ga_rang_muoi': ('Gà ướp sả, áo bột khoai chiên giòn hai lần, lắc cùng bột rang muối, sả, gừng, lá chanh thơm lừng.',
                  ['Chặt gà miếng vừa ăn, ướp với các gia vị cùng một cây sả băm trong 30 phút. Đập dập và xé sợi phần sả còn lại; thái '
                   'sợi gừng, lá chanh; thái nhỏ rau răm.',
                   'Để gà ráo nước rồi cho bột khoai vào xóc đều.',
                   'Đun nóng dầu, chiên gà ở lửa vừa đến khi vàng đều và chín, vớt ra; cho sả, gừng vào chiên vàng.',
                   'Để gà nghỉ 10 phút, rồi chiên lần hai ở lửa lớn cho gà giòn lâu.',
                   'Cho gà ra thau, thêm sả, gừng, rau răm, hành phi, lá chanh và bột rang muối, xóc đều; dùng nóng.']),
 'ga_tiem_thuoc_bac': ('Gà ác tiềm thuốc bắc với nước dừa, táo tàu, nấm hương trong nồi cơm điện 2 tiếng, mềm ngọt, thơm vị thuốc.',
                       ['Rửa gà với muối, để ráo. Rửa sạch gói thuốc bắc và táo tàu; ngâm nấm hương cho mềm.',
                        'Xếp gà vào thố, cho thuốc bắc, táo tàu, nấm hương và muối hồng vào, đổ nước dừa xăm xắp mặt gà.',
                        'Cho ít nước vào nồi cơm điện, đặt thố gà vào hầm khoảng 2 giờ.',
                        'Khi gà mềm và thấm vị, lấy ra dùng kèm muối tiêu chanh.']),
 'ga_xao_sa_ot': ('Gà ướp nghệ xào săn với tỏi, sả, ớt rồi đậy nắp om chín, vàng thơm, cay nhẹ.',
                  ['Rửa sạch gà, chặt miếng vừa ăn, ướp muối, đường và bột nghệ 20-30 phút.',
                   'Phi thơm tỏi, sả và ớt với dầu ăn, cho gà vào xào đến khi săn.',
                   'Thêm chút nước, đậy nắp om 10 phút cho gà chín, nêm nước mắm cho vừa.']),
 'gan_heo_xao_hanh': ('Gan heo ngâm giấm khử mùi, ướp tỏi gừng rồi xào nhanh với hành đến khi vừa săn.',
                      ['Ngâm gan heo trong nước pha giấm khoảng 20 phút rồi vớt ra.',
                       'Sơ chế hành, hành lá; đập dập tỏi và gừng.',
                       'Rửa lại gan, cắt miếng vừa ăn, ướp với tỏi băm, gừng băm, bột canh, hạt nêm, nước mắm và đường.',
                       'Phi thơm tỏi và gừng, cho gan vào xào đến khi hơi săn thì thêm hành, đảo đều.',
                       'Cho hành lá vào rồi tắt bếp.']),
 'gia_cay_chan_gio': ('Chân giò ướp mẻ, mắm tôm, riềng, sả, nghệ rồi hầm lửa nhỏ cho nhừ, ăn kèm bún.',
                      ['Rửa sạch chân giò.',
                       'Ướp chân giò với mẻ, mắm tôm, nước mắm, riềng, sả, nghệ và hành tây.',
                       'Đổ nước ngang mặt thịt, đun sôi rồi thêm baking soda để thịt nhanh nhừ mà không nát.',
                       'Hầm lửa nhỏ trong 30 phút, ăn kèm bún.']),
 'hai_san_nuong_mo_hanh': ('Sò điệp trần gừng sả rồi nướng, rưới mỡ hành, rắc lạc, chấm nước mắm tỏi chua ngọt.',
                           ['Làm sạch sò điệp, ngâm nước muối.',
                            'Đun sôi nồi nước có vài lát gừng hoặc sả, trần sò qua để khử tanh.',
                            'Làm mỡ hành bằng cách rưới dầu sôi lên hành; giã nhỏ lạc.',
                            'Pha nước chấm từ nước mắm, giấm, đường, bột nêm và tỏi đập.',
                            'Nướng sò bằng lò nướng hoặc nồi chiên không dầu 160 độ trong 15 phút, rưới mỡ hành rồi nướng thêm 3 phút; rắc '
                            'lạc và dùng với nước mắm.']),
 'hau_nuong_mo_hanh': ('Hàu nướng than lửa nhỏ với mỡ hành, rắc đậu phộng rang và hành phi, béo thơm.',
                       ['Rửa sạch hàu, tách vỏ rồi rửa nhẹ nhàng thêm một lần.',
                        'Bóc vỏ, thái lát hành tím rồi chiên lửa vừa đến khi vàng đều. Cắt nhỏ hành lá làm mỡ hành. Rang đậu phộng lửa '
                        'vừa, bỏ vỏ lụa.',
                        'Đặt hàu lên bếp than (hoặc lò) ở lửa nhỏ cho khỏi xém, cho mỡ hành lên.',
                        'Nướng 2-3 phút đến khi hàu chín, rắc đậu phộng rang và hành phi rồi dùng.']),
 'kho_qua_nhoi_thit_hap': ('Khổ qua nhồi thịt heo xay trộn nấm mèo, nấm hương, nấu chín trong nước sôi, vị thanh đắng nhẹ.',
                           ['Rửa sạch khổ qua, cắt khúc vừa để nhồi.',
                            'Trộn thịt xay với nấm mèo và nấm hương băm cùng toàn bộ gia vị.',
                            'Nhồi hỗn hợp thịt vào các khúc khổ qua.',
                            'Làm nóng dầu, phi thơm hành tím, đổ nước vào nấu sôi rồi thả khổ qua vào nấu đến khi chín.']),
 'lau_kim_chi_hai_san': ('Lẩu nước dùng ninh xương, kim chi xào tỏi hành gừng, nhúng hải sản, nấm và rau, chua cay đậm đà.',
                         ['Rửa sạch xương thịt, cho vào nồi ninh khoảng 45 phút lấy nước dùng ngọt.',
                          'Sơ chế hải sản, rau và nấm kim châm.',
                          'Phi thơm tỏi, hành và gừng băm.',
                          'Cho kim chi vào đảo đều 4–5 phút (thêm bột ớt nếu muốn cay hơn), rồi trút vào nồi nước xương và đun tiếp.',
                          'Nêm vừa ăn, cho hải sản vào nấu chín, thêm rau và nấm; ăn kèm bún hoặc mì tôm.']),
 'lau_thai': ('Lẩu Thái nước dùng hầm rau củ, sả, riềng, lá chanh, nêm chua cay với me và sa tế, nhúng tôm, nghêu, rau.',
              ['Cho rau củ nấu nước dùng vào nồi nước, đun sôi rồi hạ lửa hầm 30 phút, lọc bỏ xác.',
               'Rửa sạch nghêu; tôm có thể ướp hoặc để nguyên.',
               'Phi thơm sả và tỏi, cho cà chua và thơm vào xào để lên màu, rồi trút vào nồi nước dùng.',
               'Nêm nồi lẩu cho vừa vị chua, cay, mặn, ngọt.',
               'Chuyển ra nồi lẩu, nhúng tôm, nghêu và các loại rau, ăn kèm bún hoặc mì.']),
 'long_ga_xao_gia_dua': ('Lòng gà xào lửa to cùng giá, dứa, cà chua, giòn mềm, chua ngọt nhẹ và thơm tiêu.',
                         ['Làm sạch lòng gà, thái dày khoảng 0,5 cm; bổ đôi tim, bỏ tiết đen. Nhặt rễ giá, rửa sạch.',
                          'Thái cà chua múi cau và dứa thành miếng dày khoảng 1 cm; cắt hành hoa khúc dài khoảng 2,5 cm.',
                          'Xào lòng gà với bột canh đến khi chín tới, trút ra.',
                          'Phi tỏi băm, cho cà chua và dứa vào xào qua, thêm lòng gà và giá, xào lửa to đến khi giá chuyển màu trong.',
                          'Cho hành hoa và tiêu vào đảo nhanh rồi tắt bếp; vắt nước cốt chanh bỏ hạt vào trộn đều.']),
 'long_heo_luoc': ('Lòng heo luộc với sả gừng cho thơm, chấm mắm tôm pha chanh, đường, tỏi sả ớt, ăn kèm rau sống.',
                   ['Làm sạch lòng, rửa lại với muối và rượu.',
                    'Luộc lòng trong nồi nước có sả, gừng đập dập, nêm đường, muối, bột ngọt, hạt nêm và nước mắm cho thơm.',
                    'Pha mắm tôm với nước cốt chanh, bột ngọt, đường cùng tỏi, sả, ớt băm, khuấy đều rồi nêm lại cho vừa.',
                    'Bày lòng ra đĩa, dùng kèm mắm tôm và rau sống.']),
 'long_heo_xao_dua_cai': ('Lòng non, lòng già xào dưa cải chua, lòng giòn sần sật quyện vị chua dịu, ăn nóng với cơm.',
                          ['Bóp kỹ lòng với muối và giấm (hoặc chanh) cho sạch nhớt, rửa lại nhiều lần với nước.',
                           'Trụng lòng khoảng 30 giây trong nồi nước có vài lát gừng đập dập, vớt ra ngâm nước lạnh 5 phút cho giòn và '
                           'trắng rồi cắt khúc ngắn.',
                           'Rửa dưa cải cho bớt chua mặn, vắt ráo, cắt khúc.',
                           'Phi thơm hành tím với dầu, cho lòng vào xào chín, nêm dầu hào, hạt nêm, đường, bột ngọt.',
                           'Cho dưa cải vào xào chín, đảo đều cho hòa quyện. Tắt bếp, thêm hành lá cắt khúc và tiêu.']),
 'luoi_heo_luoc': ('Lưỡi heo luộc cùng hành tím, ngâm đá cho trắng giòn, thái lát mỏng ăn kèm.',
                   ['Cạo và rửa sạch lưỡi heo với muối, trụng qua nước sôi.',
                    'Luộc lưỡi với hành tím, muối và hạt nêm, để nước ngập lưỡi cho khỏi bị thâm, luộc khoảng 15 phút.',
                    'Khi lưỡi chín, cắt làm 4 rồi luộc thêm 5 phút để chín đều bên trong.',
                    'Muốn lưỡi trắng giòn thì ngâm vào tô nước đá, sau đó thấm khô và thái lát mỏng.']),
 'luon_om_chuoi_dau': ('Lươn om cùng chuối xanh và đậu, đậm vị nghệ, thơm lá lốt, béo bùi và hơi chát nhẹ.',
                       ['Làm sạch lươn bằng chanh và muối, cắt khúc vừa ăn; lươn to thì lọc bỏ xương sống. Ướp lươn với một ít tỏi, nghệ, '
                        'muối, tiêu, đường.',
                        'Bóc vỏ chuối xanh, cắt miếng, ngâm nước muối cho bớt chát. Cắt đậu thành miếng vuông.',
                        'Phi thơm tỏi, cho lươn vào xào săn rồi thêm chuối và đậu.',
                        'Nêm mắm, muối, tiêu, nghệ, đường, đổ nước ngập mặt và om 10 phút.',
                        'Thêm lá lốt vào rồi tắt bếp.']),
 'luon_xao_sa_ot': ('Lươn xào sả ớt ướp nghệ, ớt ngọt, xào cùng hành tây, ớt chuông và lá lốt, thơm cay đậm đà, hợp ăn cơm nóng.',
                    ['Làm sạch nhớt lươn, cắt khúc vừa ăn hoặc lóc lấy thịt.',
                     'Đập dập rồi băm nhuyễn sả. Chần sơ ớt chuông qua nước sôi cho bớt hăng rồi băm nhuyễn; thái sợi lá lốt.',
                     'Ướp lươn với một phần sả băm, bột ớt ngọt, bột nghệ, syrup, tiêu và hạt nêm, trộn đều và để 30 phút cho thấm.',
                     'Đun nóng mỡ nước, phi thơm hành tây và sả, cho lươn vào xào đến khi săn lại rồi nêm nếm lại.',
                     'Thêm lá lốt, ớt chuông băm và chút nước, xào tiếp đến khi lươn chín thì tắt bếp.']),
 'mien_luon': ('Miến lươn nấu từ nước luộc lươn ngọt, thịt lươn ướp ớt tiêu rồi xào săn, thơm mùi rau răm.',
               ['Chà lươn với muối và chanh cho sạch nhớt, rửa lại rồi cắt khúc.',
                'Luộc lươn trong nồi nước có gừng đập, hành và chút muối, hớt bọt khi sôi; vớt lươn ra, giữ lại nước luộc.',
                'Lóc lấy thịt lươn, ướp với hành tím, ớt bột, ớt tươi, hạt nêm, nước mắm và tiêu khoảng 30 phút.',
                'Phi thơm hành tím, cho lươn vào xào chín, nêm lại vừa ăn.',
                'Ngâm miến khoảng 15 phút cho mềm, để ráo; đun sôi nước luộc lươn, cho miến vào nấu chín rồi thêm lươn xào, sôi lại thì '
                'nêm vừa và tắt bếp ngay.',
                'Múc ra tô, rắc rau răm thái nhỏ và tiêu, dùng nóng.']),
 'mien_xao_long_ga': ('Miến dong xào cùng lòng gà giòn, măng khô, nấm, rau củ và sốt nước tương dầu hào đậm đà.',
                      ['Chà lòng gà với muối giấm, rửa sạch, trụng qua nước sôi có rượu trắng rồi để ráo. Ngâm măng khô bằng nước vo gạo '
                       'vài tiếng, luộc mềm, xả lại rồi xé sợi; ngâm nấm lộc nhung cho nở; cắt cọng cà rốt, cắt sợi hành tây.',
                       'Ngâm miến nước lạnh 15 phút rồi cắt khúc. Cắt khúc hành ngò, thái lát hành tím. Khuấy đều nguyên liệu sốt xào đến '
                       'khi đường và hạt nêm tan hết.',
                       'Phi thơm hành tím, xào mề gà đến chín tới rồi cho gan vào, nêm hạt nêm, tiêu và chút nước, xào đến khi lòng chín '
                       'săn thì trút ra đĩa.',
                       'Dùng chảo đó, thêm dầu, xào măng, nấm, cà rốt với một ít sốt; gần chín cho hành tây, hành lá vào đảo rồi trút ra.',
                       'Hạ lửa vừa, đổ phần sốt còn lại vào chảo, cho miến vào đảo đều (thêm chút nước nếu khô) đến khi miến trong và săn '
                       'thì tắt bếp.',
                       'Trộn lòng gà, rau củ với miến, bày ra đĩa, rắc ngò rí và tiêu; ăn kèm nước tương tỏi ớt.']),
 'mong_gio_ham_mang': ('Giò heo xào săn hầm cùng măng khô, nước dừa và hành tím nguyên củ, nước dùng ngọt thanh.',
                       ['Ngâm măng khô cho nở, rửa sạch rồi luộc nhiều lần đến khi hết vàng và đắng. Cắt bỏ phần già, cắt miếng vừa ăn.',
                        'Rửa sạch giò heo, để ráo. Phi thơm hành tím với dầu, cho giò heo vào xào săn; xào riêng măng với gia vị.',
                        'Xếp xen kẽ lớp măng, lớp thịt vào nồi, thêm nước dừa và nước sôi, nấu sôi lại rồi vớt sạch bọt.',
                        'Cho hành tím nguyên củ vào hầm nhỏ lửa, thỉnh thoảng vớt bọt, nêm lại cho vừa.',
                        'Múc ra tô, trang trí hành lá chẻ và vài lát ớt.']),
 'muc_chien_gion': ('Mực lá cắt khoanh áo bột chiên giòn, chiên ngập dầu vàng đều, chấm tương ớt, tương cà, mayonnaise.',
                    ['Làm sạch ruột mực, rửa lại, cắt khoanh và để ráo, không cần ướp.',
                     'Khuấy bột chiên giòn với nước, để bột nghỉ 15 phút.',
                     'Đun nóng lượng dầu đủ ngập mực; nhúng mực qua bột rồi thả vào chiên đến khi vàng đều.',
                     'Vớt ra đĩa lót giấy thấm dầu; dùng kèm tương ớt, tương cà và mayonnaise.']),
 'muc_xao_can_toi': ('Mực sữa trụng sơ, xào lửa lớn với cần tây, tỏi lá và hành tây, giòn ngọt, thơm tỏi tiêu.',
                     ['Rửa sạch mực, bỏ mai (có thể lột da), ướp với một nửa phần tỏi băm. Thái vát cần tây, cắt khúc tỏi lá, tách lớp '
                      'hành tây bổ cau nếu dùng.',
                      'Đun sôi một nồi nước, cho mực vào khuấy một vòng rồi tắt bếp, đổ ra rổ cho ráo.',
                      'Đun nóng già chảo với dầu, cho mực vào đảo nhanh, thêm nước mắm rồi trút ra đĩa.',
                      'Phi thơm phần tỏi băm còn lại với dầu, cho hành tây đảo 30 giây, rồi cần tây thêm 30 giây, nêm nước mắm.',
                      'Cho mực trở lại chảo cùng tỏi lá, đảo khoảng 30 giây đến 1 phút. Tắt bếp, rắc tiêu, ăn nóng.']),
 'nam_bao_ngu_xao_hanh_tay': ('Nấm bào ngư xám xào nhanh với hành tây và gừng sợi, chín giòn, thanh ngọt.',
                              ['Rửa nấm bằng nước muối, bóp ráo nước.',
                               'Thái hành tây múi cau mỏng; thái gừng thành sợi.',
                               'Đun nóng dầu, cho hành tây vào xào trước, tiếp theo là nấm rồi đến gừng.',
                               'Nêm bột nêm, bột ngọt và đường, xào đến khi nấm chín giòn thì tắt bếp.']),
 'nam_dui_ga_xao_toi': ('Nấm đùi gà xào bơ rồi om nhỏ lửa với sốt tỏi, nước tương, dầu mè, mềm và đậm vị.',
                        ['Rửa sạch nấm, thái dọc thành miếng dày khoảng 0,5 cm.',
                         'Pha sốt từ tỏi băm, nước tương, dầu mè và đường.',
                         'Xào nấm với dầu ăn (hoặc thêm bơ nhạt cho thơm) trên lửa vừa.',
                         'Khi nấm chín được một nửa, đổ sốt vào xào cùng rồi hạ lửa nhỏ, om 7–10 phút cho thấm, tắt bếp và bày ra đĩa.']),
 'nam_huong_nhoi_thit_hap': ('Nấm đông cô nhồi thịt heo xay trộn ớt chuông, hấp chín, phết lòng đỏ trứng và rưới sốt dầu hào.',
                             ['Sơ chế nguyên liệu; trộn thịt xay với ớt chuông, hành tím băm, hành lá, Knorr, tiêu và dầu mè cho thấm vị.',
                              'Áo mặt trong nấm đông cô một lớp bột mì cho dễ bám, dùng muỗng nhồi và nén chặt hỗn hợp thịt vào nấm.',
                              'Xếp nấm lên đĩa, hấp chín. Mở nắp, phết lòng đỏ trứng lên mặt thịt, đậy lại hấp tiếp đến khi trứng se mặt.',
                              'Làm sốt: phi thơm tỏi rồi vớt tỏi ra bỏ, cho dầu hào, nước tương, hắc xì dầu và nước vào khuấy đều, nêm '
                              'muối và đường vừa vị.',
                              'Luộc chín cà rốt tỉa hoa để trang trí. Bày nấm ra đĩa, rưới sốt, rắc hành lá và tiêu, dùng nóng với cơm.']),
 'nam_kho_tieu': ('Thịt kho cùng nấm đùi gà và tiêu xanh trong nước màu, có thể kho nhiều nước hoặc kho cạn tùy thích.',
                  ['Thái thịt dày khoảng 0,5–0,7 cm, nấm dày 1–2 cm. Bóc vỏ ngoài hành khô, rửa sạch. Ướp thịt và nấm với chút dầu hào, xì '
                   'dầu.',
                   'Đun dầu ăn với đường thành nước màu cánh gián.',
                   'Nhanh tay cho thịt, nấm, hành khô và hai nhánh tiêu xanh vào đảo, thêm nước mắm, đảo đến khi thịt săn.',
                   'Đổ nước xâm xấp mặt thịt, đun sôi rồi hạ nhỏ lửa.',
                   'Kho lửa nhỏ để giữ nhiều nước, hoặc đun lửa to cho cạn nước, tùy khẩu vị.']),
 'nam_rom_xao_thit_bo': ('Thịt bò thăn ướp sả tỏi xào lửa lớn cùng nấm rơm, hành tây và dầu hào, mềm ngọt, thơm.',
                         ['Thái mỏng thịt bò, ướp với nước tương, dầu hào, tỏi, sả băm, bột bắp và tiêu, trộn đều để 15 phút.',
                          'Cạo chân nấm rơm, rửa nhanh để ráo; nấm lớn cắt đôi, nấm nhỏ khía đầu để khỏi đọng nước. Thái hành tây múi cau '
                          'mỏng.',
                          'Đun nóng dầu, phi thơm hành tỏi băm, xào bò nhanh trên lửa lớn đến khi tái rồi trút ra đĩa.',
                          'Cùng chảo đó, đảo nấm rơm khoảng 2 phút cho chín, thêm hành tây đảo vài lượt và nêm dầu hào vừa ăn.',
                          'Cho bò vào trộn đều rồi tắt bếp. Bày ra đĩa, rắc hành ngò và tiêu, dùng với cơm.']),
 'nem_nam_dui_ga': ('Nem thính chay từ nấm đùi gà hấp xé sợi, trộn nước mắm chua ngọt, thính gạo rang và lá chanh, ăn kèm rau thơm.',
                    ['Hấp nguyên cây nấm đùi gà 8-10 phút cho dai, để nguội rồi xé dọc thành sợi vừa ăn.',
                     'Pha nước mắm chua ngọt: ướp tỏi ớt băm với nước cốt chanh. Khuấy tan đường, nước mắm, nước và mì chính, đun sôi rồi '
                     'để nguội, cho tỏi ớt vào và nêm lại cho vừa.',
                     'Làm thính: rang riêng gạo và đậu xanh (nếu có) đến khi vàng thơm, để nguội rồi xay chung thật mịn.',
                     'Bóp nấm cho khô, trộn với ít nước mắm chua ngọt và tỏi băm, bóp đều rồi vắt khô; có thể nêm thêm nước mắm nếu thích '
                     'đậm.',
                     'Rắc thính từng đợt vào trộn cho áo đều nấm, tránh đổ một lần gây vón cục. Trộn cùng lá chanh thái chỉ, chừa ít rắc '
                     'lên mặt.',
                     'Ăn kèm các loại rau thơm sẵn có, nhất là lá sung, cùng hành củ, riềng, sả tươi.']),
 'ngan_xao_sa_ot': ('Lườn ngan thái mỏng xào sả ớt, nêm nước mắm, thơm cay và mềm ngọt, ăn nóng.',
                    ['Bỏ gốc sả rồi thái vát, ớt cũng thái vát. Lọc xương ngan, thái mỏng, ướp với mì chính và hạt nêm 10 phút.',
                     'Đun nóng dầu, phi thơm sả rồi cho thịt ngan vào xào chín tới.',
                     'Cho ớt vào đảo đều, thêm nước mắm, nêm lại vừa ăn.',
                     'Xào đến khi thịt chín thì tắt bếp, múc ra đĩa ăn nóng.']),
 'ngheu_xao_sa_ot': ('Nghêu sò xào sả tỏi phi thơm, thêm chút đường và ớt, ngọt tự nhiên và cay nhẹ.',
                     ['Ngâm nghêu sò qua đêm trong nước biển cho nhả cát, sau đó rửa sạch với nước lạnh.',
                      'Cắt nhỏ tỏi và sả, phi thơm trong dầu nóng.',
                      'Cho nghêu sò vào xào cùng chút đường (không cần muối), đảo đều rồi đậy nắp khoảng 2 phút cho vỏ mở hết.',
                      'Thêm ớt, nếm lại cho vừa rồi tắt bếp.']),
 'nom_hoa_chuoi': ('Nộm hoa chuối trộn thịt ba chỉ luộc, đậu phụ bóp vụn và lạc rang, vị chua ngọt cay nhẹ.',
                   ['Pha nước trộn: nước cốt chanh bỏ hạt, mì chính, đường, bột canh và ớt băm, khuấy tan.',
                    'Thái ba chỉ luộc thành miếng nhỏ dài; trần đậu phụ qua nước sôi rồi để ráo; thái nhỏ rau mùi và húng.',
                    'Cho hoa chuối, thịt, rau thơm và đậu phụ bóp nát vào bát lớn, rưới nước trộn vào trộn đều, nêm lại cho vừa.',
                    'Thêm lạc rang, trộn qua rồi bày ra đĩa.']),
 'nuoc_ep_oi': ('Nước ép ổi lê bằng máy ép chậm, thêm vài hạt muối cho đậm đà, ngon nhất khi vừa ép xong.',
                ['Rửa sạch ổi, cắt nhỏ cho dễ ép; có thể để ngăn đá trước nếu muốn uống lạnh ngay.',
                 'Cho ổi vào máy ép chậm lấy nước.',
                 'Có thể thêm vài hạt muối vào cốc nước ép. Uống ngay sau khi ép; bảo quản tủ lạnh được 2–3 ngày.']),
 'nuong_kieu_han_kim_chi': ('Ba chỉ áp chảo không dầu kiểu Hàn, nướng cùng hành baro, nấm, tỏi và kim chi, thịt mềm, thơm quyện.',
                            ['Rửa sạch hành baro, hành tây, tỏi và nấm, vắt ráo nước nấm kim châm. Cắt hành baro khúc khoảng 5cm, thân chẻ '
                             'đôi; thái hành tây, tỏi và nấm đùi gà.',
                             'Đặt cả miếng ba chỉ vào chảo không dầu, lửa trung bình nhỏ, nướng vàng đều hai mặt, rắc muối tiêu cả hai mặt '
                             'và không lật quá nhiều; nếu để da thì nướng kỹ phần da cho giòn.',
                             'Khi hai mặt vàng, dùng kéo cắt thịt thành miếng vừa ăn.',
                             'Cho hành baro, hành tây, nấm và tỏi vào chảo, rắc chút muối tiêu, nướng cùng thịt.',
                             'Khi thịt gần chín, cho kim chi cắt nhỏ vào giữa chảo, không trộn lẫn với nguyên liệu khác, xào 3-5 phút đến '
                             'khi kim chi mềm và thịt vừa chín tới.',
                             'Chấm sốt thịt nướng Hàn Quốc hoặc tự trộn sốt từ hành lá, bột ớt Hàn, tỏi, ớt, dầu mè, mè rang, mật ong, '
                             'mayonnaise, tương ớt, tương đậu Hàn và chút mù tạt.']),
 'oc_nau_chuoi_dau': ('Ốc bươu nấu cùng chuối xanh, đậu hũ chiên, thịt ba chỉ, mắm tôm và cơm mẻ, chua nhẹ, thơm lá lốt tía tô.',
                      ['Ngâm ốc trong nước vo gạo với ớt cắt lát 3 tiếng rồi rửa sạch. Luộc ốc với sả đập dập và gừng lát 5 phút, để '
                       'nguội, lấy thịt, rửa lại và để ráo.',
                       'Gọt vỏ chuối, cắt lát dày khoảng 1cm, ngâm nước muối pha chanh 10 phút rồi rửa lại và để ráo.',
                       'Thái mỏng thịt ba chỉ, rang đến khi cháy cạnh rồi vớt ra. Lọc cơm mẻ với ít nước qua rây, khuấy cùng bột nghệ. Cắt '
                       'sợi tía tô, lá lốt; cắt nhỏ hành lá. Chiên đậu hũ vàng giòn, để ráo dầu.',
                       'Phi thơm hành tím trong mỡ còn lại sau khi rang thịt, cho ốc vào xào với đường và nước mắm khoảng 2 phút rồi tắt '
                       'bếp.',
                       'Bớt dầu ở chảo chiên đậu, xào chuối đến khi ngả vàng thì cho thịt vào đảo đều.',
                       'Đổ nước vào chảo chuối, thêm mắm tôm, đường, hạt nêm và nước cơm mẻ, nấu đến khi chuối mềm. Cho ốc vào nấu 5 phút, '
                       'tiếp tục cho đậu hũ vào nấu thêm 5 phút.',
                       'Nêm thêm nước mắm cho vừa, cho hành lá, tía tô, lá lốt vào đảo đều rồi tắt bếp. Dùng nóng với bún hoặc cơm.']),
 'pad_thai': ('Pad Thái xào sợi phở với tôm khô, hẹ, giá, trứng và sốt me đường thốt nốt, chua ngọt cay.',
              ['Ngâm sợi phở trong nước lạnh đến khi mềm.',
               'Trộn nước cốt me, đường thốt nốt, nước mắm và ớt bột thành sốt, nếm cho vừa vị.',
               'Phi thơm tỏi với dầu, cho hẹ, giá, tôm khô và một phần sốt vào xào chín.',
               'Cho sợi phở cùng phần sốt còn lại vào, đập thêm một quả trứng, xào đến khi sợi vừa mềm.',
               'Bày ra đĩa, ăn kèm đậu phộng giã và chanh.']),
 'pho_ga': ('Phở gà ta luộc ủ giữ thịt ngọt, nước dùng từ nước luộc gà, kèm trứng trần lòng đào.',
            ['Chà gà với muối và chanh, ngâm nước 10 phút rồi rửa lại nhiều lần.',
             'Cho gà vào nồi nước lạnh cùng rễ ngò, hành tím, muối và gừng cắt lát đập dập; đun sôi 5 phút thì tắt bếp, ủ thêm 30 phút. '
             'Rửa sạch và cắt nhỏ hành ngò.',
             'Đập trứng vào chén có ít nước, nghiêng chén thả vào nồi nước sôi lăn tăn khoảng 2 phút rồi vớt ra chén.',
             'Để gà nguội, lọc bỏ xương và cắt miếng vừa ăn; nêm nước luộc gà với chút nước mắm và đường làm nước dùng.',
             'Trụng bánh phở, để ráo, xếp vào tô cùng thịt gà; chan nước dùng, thêm hành ngò và tiêu. Chan nước dùng vào chén trứng, thêm '
             'hành ngò và tiêu.']),
 'ruoc_thit_heo': ('Ruốc thịt heo thăn luộc chín, đánh tơi rồi sao khô trên chảo, tơi bông, mặn ngọt vừa.',
                   ['Rửa sạch thịt, thái dọc thớ miếng to, ướp gia vị khoảng 30 phút.',
                    'Cho thịt vào nồi với chút nước, khi sôi hạ lửa nhỏ đun 20-30 phút cho chín.',
                    'Vớt thịt ra để nguội, xé nhỏ rồi cho vào máy xay hoặc máy đánh cho tơi.',
                    'Sao thịt trên chảo, nêm lại cho vừa và đảo đều tay đến khi khô như ý.',
                    'Có thể cho vào máy đánh thêm một lần nữa để ruốc bông hơn.']),
 'sinh_to_gac': ('Sinh tố chuối sứ và nạc gấc xay với sữa yến mạch tự làm và đá, mát lạnh, bổ dưỡng.',
                 ['Lột vỏ chuối sứ chín. Bổ đôi gấc chín, phơi ráo hai mặt rồi lấy phần nạc.',
                  'Xay yến mạch với nước ấm, lọc qua vải mùng bỏ bã để lấy sữa yến mạch.',
                  'Cho chuối, nạc gấc, đá và sữa yến mạch vào máy xay nhuyễn.']),
 'su_su_xao_thit_bo': ('Su su và đậu ve xào thịt bò với tỏi, xì dầu, thịt bò mềm, rau củ giòn ngọt.',
                       ['Rửa sạch su su và đậu ve, thái mỏng vừa ăn; băm tỏi.',
                        'Phi thơm tỏi với dầu, cho thịt bò vào đảo nhanh tay, nêm xì dầu và hạt nêm. Khi bò còn hơi tái thì trút ra đĩa.',
                        'Dùng phần nước xào bò còn trong chảo xào su su và đậu ve, nêm thêm xì dầu, hạt nêm, tiêu.',
                        'Khi rau củ chín, cho thịt bò vào đảo đều, nêm lại rồi bày ra đĩa.']),
 'suon_nuong_mat_ong': ('Sườn cốt lết ướp mật ong, dầu hào, ngũ vị hương, sả nướng than, quết sốt liên tục cho vàng óng, đậm đà.',
                        ['Chà muối và bóp kỹ sườn cho hết nhớt, ngâm nước muối loãng khoảng 10 phút, rửa sạch và để thật ráo. Dần nhẹ '
                         'miếng thịt vài lần cho mềm.',
                         'Băm nhuyễn hành tím và sả.',
                         'Ướp sườn với dầu hào, mật ong, nước mắm, ngũ vị hương, sả, hành tím, đường, bột ngọt, muối và tiêu, xoa đều '
                         'khoảng 5 phút rồi để 30 phút đến 1 tiếng.',
                         'Làm nóng vỉ trên bếp than (hoặc dùng lò, nồi chiên không dầu), quét dầu lên vỉ rồi xếp sườn lên.',
                         'Pha hỗn hợp dầu hào, mật ong và dầu ăn; mỗi 2-3 phút trở sườn thì quét một lớp. Nướng đến khi sườn chín, vàng '
                         'đậm đều hai mặt.']),
 'tau_hu_ky_cuon_thit': ('Tàu hũ ky cuốn chả tôm thịt quết dai rồi chiên vàng giòn, chấm tương ớt hoặc nước mắm chua ngọt.',
                         ['Rửa sạch tôm và thịt, để ráo, xay cùng bột năng đến khi quyện và nhuyễn mịn.',
                          'Ướp hỗn hợp với nước cốt hành tím, hạt nêm, nước mắm, đường, tiêu, dầu mè và dầu ăn, quết đều.',
                          'Bọc lại, để tủ lạnh 30 phút rồi lấy ra quết thêm một lần cho dai.',
                          'Cắt tàu hũ ky miếng vừa cuốn, cuốn một lớp mỏng nhân để vỏ giòn và nhanh chín.',
                          'Chiên vàng, vớt ra giấy thấm dầu. Dùng kèm tương ớt hoặc nước mắm chua ngọt.']),
 'thit_chung_mam_tep': ('Thịt xay ướp riềng sả tỏi, đảo lửa to rồi rim với mắm tép đến khi khô, đậm đà thơm nồng.',
                        ['Xay mịn riềng, tỏi, sả (có thể lọc riềng lấy nước cốt).',
                         'Ướp thịt với các gia vị trừ dầu ăn và mắm tép, thêm nước cốt riềng và hai phần ba hỗn hợp hành tỏi sả; để ngăn '
                         'mát tủ lạnh 2 giờ.',
                         'Phi thơm phần hành tỏi sả còn lại với dầu, cho thịt vào đảo lửa to đến khi cạn nước.',
                         'Hạ nhỏ lửa, thêm mắm tép, rim đến khi thịt khô như ý.']),
 'thit_kho_dua_cai': ('Thịt ba chỉ kho cùng dưa cải chua với muối đường, thịt ngậy mỡ thấm vào dưa, càng hâm càng ngon.',
                      ['Rửa dưa cải cho bớt chua, cắt khúc khoảng 3 cm. Rửa sạch thịt ba chỉ, thái miếng 2x3 cm.',
                       'Trộn thịt với dưa cải trong nồi rồi bắc lên bếp nấu.',
                       'Khi thịt săn lại, cho muối và đường vào đảo đều, nêm vừa ăn.',
                       'Đậy nắp, kho trong 45 phút. Những lần ăn sau hâm lại khoảng 10 phút.']),
 'thit_quay_gion_bi': ('Ba chỉ ướp ngũ vị, nướng nồi chiên không dầu qua ba mức nhiệt với lớp muối phủ bì, bì nổ giòn.',
                       ['Luộc sơ thịt trong nước có muối và giấm khoảng 5 phút, úp mặt bì xuống cho bì co lại.',
                        'Pha sốt ướp từ ngũ vị hương, hạt nêm, mì chính và dầu hào; ướp phần thịt 30 phút, không để sốt dính lên bì.',
                        'Lau thật khô mặt bì, xăm hoặc khứa nông; bọc giấy bạc quanh thịt, chừa mặt bì, nướng nồi chiên không dầu 150°C '
                        'trong 3 phút.',
                        'Quét giấm lên bì, phủ một lớp muối dày, nướng tiếp 180°C trong 15 phút.',
                        'Gạt bỏ lớp muối, nướng lần cuối 200°C trong 10 phút, lấy ra thái miếng vừa ăn.']),
 'tim_cat_xao_can_toi': ('Tim cật heo xào tái rồi đảo cùng hành tây, cà rốt, giòn ngọt và đậm vị.',
                         ['Bóc vỏ, rửa sạch hành tây, thái múi cau; gọt cà rốt, tỉa hoa rồi thái lát mỏng.',
                          'Xào tim cật với dầu, nêm chút mì chính và hạt nêm, đến khi chín tái thì trút ra bát.',
                          'Thêm dầu vào chảo, xào sơ hành tây và cà rốt với chút gia vị.',
                          'Cho tim cật trở lại chảo, nêm vừa ăn, xào thêm 3 phút rồi tắt bếp, múc ra đĩa.']),
 'tom_chien_xu': ('Tôm ướp muối tiêu bột tỏi, nhúng bột chiên giòn, trứng rồi lăn bột chiên xù, chiên vàng giòn.',
                  ['Lột vỏ tôm, bỏ chỉ đen, ướp muối, tiêu và bột tỏi.',
                   'Pha bột chiên giòn với nước thành hỗn hợp sệt; đánh tan trứng.',
                   'Nhúng tôm lần lượt qua bột chiên giòn, trứng, cuối cùng lăn qua bột chiên xù.',
                   'Chiên tôm trong dầu nóng đến khi vàng giòn.']),
 'tom_rang_chay_canh': ('Tôm rang cùng thịt ba chỉ xém cạnh, nêm mắm và bột canh, thơm lá chanh, rất đưa cơm.',
                        ['Rửa sạch nguyên liệu, cắt thịt ba chỉ thành miếng nhỏ dài.',
                         'Rang tôm trên chảo nóng, đảo kỹ đến khi ráo nước và tôm giòn vỏ thì trút ra đĩa.',
                         'Cho thịt ba chỉ vào đảo đến khi ra mỡ và xém cạnh, đổ tôm vào đảo tiếp.',
                         'Nêm bột canh và nước mắm vừa ăn; khi gần chín cho lá chanh thái sợi (hoặc hành lá) vào đảo qua rồi tắt bếp.']),
 'trung_hap_van': ('Trứng hấp vân tráng mỏng, phết giò sống, cuộn mộc nhĩ nấm hương rồi gói lá chuối hấp chín, lát cắt có vân đẹp mắt.',
                   ['Tách riêng lòng đỏ và lòng trắng, đánh đều từng phần rồi tráng thành các lá trứng mỏng.',
                    'Ngâm nở mộc nhĩ và nấm hương, rửa sạch, để ráo; thái nấm hương thành lát mỏng, mộc nhĩ thái sợi nhỏ.',
                    'Trải lá trứng lòng đỏ ra, phết một lớp giò sống mỏng lên trên.',
                    'Xếp mộc nhĩ, nấm hương xen với giò sống theo cách tương tự rồi cuộn chặt trứng lại.',
                    'Hơ lá chuối trên lửa cho mềm, lau sạch, gói cuộn trứng thành hình đòn bánh tét, buộc lại và hấp 25 phút.']),
 'trung_xao_ca_chua': ('Trứng gà đảo cùng cà chua thái hạt lựu, nêm bột canh, hạt nêm, món nhanh gọn chua ngọt.',
                       ['Sơ chế cà chua, cắt hạt lựu.',
                        'Xào cà chua trước cho mềm.',
                        'Đập trứng vào chảo, nêm bột canh và hạt nêm, đảo đều khoảng 2 phút đến khi trứng chín.']),
 'vit_kho_gung': ('Vịt ướp gừng, hành tỏi vài giờ, xào săn rồi hầm nhỏ lửa trong nồi gang, thịt mềm, thấm vị.',
                  ['Rửa vịt với chanh hoặc giấm để khử mùi, chặt miếng vừa ăn. Băm nhỏ gừng, hành tím và tỏi.',
                   'Ướp vịt với gừng, hành, tỏi, nước mắm, hạt nêm và tiêu trong 2–3 tiếng.',
                   'Cho vịt vào nồi gang, xào lửa lớn và đảo đều khoảng 10 phút cho thấm gia vị.',
                   'Đổ nước xâm xấp mặt thịt, sôi thì hớt bọt, đậy nắp và hạ lửa nhỏ nhất, hầm khoảng 45 phút không mở nắp.',
                   'Tắt bếp sau 45–50 phút, nêm lại cho vừa rồi múc ra.']),
 'vit_om_sau': ('Vịt ướp sấu dầm, sả, hành tỏi rồi om với nước dừa, chua thanh, ăn kiểu lẩu nhúng đậu phụ, rau muống, nấm.',
                ['Rửa vịt, xát muối cho bớt hôi, chặt miếng rồi luộc sơ, rửa sạch bọt và để ráo.',
                 'Băm nhuyễn hành, tỏi và một cây sả; cây sả còn lại đập dập, cắt khúc. Luộc sấu đến khi chín mềm rồi vớt ra dằm nát.',
                 'Ướp vịt với hành tỏi sả, sấu dằm, bột canh, mì chính, hạt nêm và chút đường, bóp đều và để 30 phút.',
                 'Nhặt rửa rau muống, ngò gai; ngâm nấm hương 15 phút rồi rửa sạch; cắt đậu phụ; cắt chân và rửa nấm kim châm.',
                 'Đảo nồi vịt trên bếp cho săn rồi đổ nước lọc và nước dừa vào đun, vớt sạch bọt; nếu dùng khoai sọ thì cho vào ngay từ '
                 'đầu.',
                 'Đun 10-15 phút đến khi vịt chín tới để ăn lẩu, hoặc ninh thêm nếu ăn với cơm. Nhúng kèm đậu phụ, rau muống, nấm kim '
                 'châm.']),
 'xiu_mai_sot_ca': ('Viên xíu mại thịt trộn giò sống và củ đậu, hấp chín rồi rim trong sốt cà chua sền sệt.',
                    ['Trộn thịt xay với giò sống, củ đậu cắt nhỏ, hành tỏi băm, nước mắm, dầu hào và đường, để thấm 15 phút.',
                     'Vo thành viên, xếp vào xửng và hấp chín trên nồi nước sôi.',
                     'Chần cà chua, bóc vỏ, cắt nhỏ; phi thơm hành, cho cà chua vào đảo cùng nước mắm và đường.',
                     'Khi cà chua nhừ, thêm tương cà và chút nước sôi.',
                     'Cho xíu mại vào rim 5–7 phút đến khi sốt sền sệt, rắc hành lá, rau mùi, tiêu và dùng nóng.']),
 'xoi_gac': ('Xôi nếp trộn thịt gấc hấp lá dứa, rưới nước cốt dừa đường rồi hấp lại, dẻo thơm, đỏ đẹp mắt.',
             ['Vo sạch nếp, ngâm ngập nước qua đêm; xả lại, để ráo rồi trộn đều với muối.',
              'Bóp thịt gấc với rượu trắng cho tách khỏi hạt, sau đó trộn đều với nếp.',
              'Đun sôi nước trong xửng hấp có lá dứa, lót khăn xô, đổ nếp vào, đậy nắp hấp 30 phút.',
              'Khuấy nước cốt dừa với đường. Đổ xôi ra nồi sạch, rưới hỗn hợp này vào đảo đều.',
              'Cho xôi lại vào xửng hấp thêm 15 phút, tắt bếp, ủ thêm 5 phút rồi xới ra đĩa.'])}

# Món nhóm Cookpad (không thuộc lô) trước đây cách làm tự soạn – nay theo bài đã chọn.
CT.update({
    "cuu_nuong": ("Sườn cừu ướp nước tương, sa tế, dầu mè, hành tỏi rồi nướng lò – đậm vị, hơi cay.",
                  ["Trộn sườn cừu với nước tương, sa tế, đường, dầu mè, hành tỏi; nêm theo khẩu vị.",
                   "Cho vào lò nướng ở 475°F (khoảng 245°C) trong 25 phút đến khi thịt chín.",
                   "Bày ra đĩa, ăn cùng rau xào và cơm."]),
    "gia_xao_he": ("Giá, hẹ đảo nhanh trong nước thịt rang, thêm tỏi phi và tiêu – giòn, đậm.",
                   ["Rửa giá, để ráo; hẹ rửa sạch, cắt khúc vừa ăn.",
                    "Đun sôi nước thịt rang trong chảo, cho giá và hẹ vào đảo cho thấm.",
                    "Rắc tiêu xay và tỏi phi rồi tắt bếp."]),
    "xa_lach_tron_dau_giam": ("Xà lách trộn nước sốt dầu ô liu, giấm nho, tỏi ớt, ăn kèm trứng luộc.",
                              ["Rửa xà lách kỹ 3 lần, để ráo.",
                               "Luộc trứng 7 phút; băm nhuyễn tỏi, ớt.",
                               "Pha sốt: tỏi ớt, dầu ô liu, giấm nho, đường, nước mắm khuấy đều trong chén.",
                               "Rưới sốt lên xà lách, trộn và bóp nhẹ cho rau ngấm.",
                               "Bổ trứng làm 4, xếp lên trên."]),
    "mang_tay_luoc_cham_xi_dau_trung": ("Măng tây luộc trong nước có muối, đường, chanh, dầu ăn cho xanh mướt – ăn kèm món mặn.",
                                        ["Bẻ bỏ phần gốc già, ngâm măng tây nước muối loãng, rửa lại, để ráo.",
                                         "Đun sôi nước với chút muối, đường, nước chanh, dầu ăn để măng giữ màu xanh.",
                                         "Thả măng tây vào luộc đến khi chín, vớt ra đĩa."]),
    "canh_dau_phu_ca_chua": ("Canh cà chua với đậu phụ non, nấu nhanh, thanh nhẹ.",
                             ["Rửa cà chua, cắt hạt lựu hoặc miếng vừa ăn; đậu phụ non để lạnh cho chắc rồi cắt miếng nhẹ tay.",
                              "Đun sôi nước, cho cà chua và đậu phụ vào, nêm nước mắm hoặc nước tương tùy khẩu vị.",
                              "Đậy nắp, vặn nhỏ lửa, sôi lại thì tắt bếp."]),
    "canh_cai_thao_dau_hu_nam": ("Canh cải thảo nấu đậu hũ non – thanh, ngọt rau, nấu nhanh.",
                                 ["Đậu hũ non rửa sạch, cắt miếng vuông; cải thảo rửa, cắt khúc.",
                                  "Đun sôi nước với muối, hạt nêm; cho cải thảo vào nấu lửa lớn rồi thêm đậu hũ, hạn chế khuấy cho đậu khỏi nát; nêm vừa ăn.",
                                  "Tắt bếp, thả hành lá."]),
    "canh_tom_nau_thom": ("Canh chua tôm xào thơm cà chua, thêm đậu bắp, giá – chua dịu, ngọt tôm.",
                          ["Bóc vỏ tôm, bỏ chỉ lưng, để nguyên hoặc cắt đôi; ướp với hành tím, bột nêm, nước mắm, đường, dầu ăn, chút ớt màu.",
                           "Rửa thơm, cà chua, đậu bắp, cắt khúc vừa ăn; hành lá cắt khúc, giá để ráo.",
                           "Phi dầu nóng, xào tôm dậy mùi rồi cho thơm, cà chua vào đảo đến khi thấm gia vị, đổ nước vào.",
                           "Nước sôi thì cho đậu bắp; sôi lại lần nữa thì tắt bếp ngay để rau không nhũn.",
                           "Nêm lại, cho giá và hành lá vào."]),
})

# Canh khổ qua nhồi thịt: đổi sang bài có đủ khổ qua trong bảng nguyên liệu (bài trước thiếu).
CT["kho_qua_nhoi_thit_hap"] = ("Khổ qua nhồi thịt nạc dăm trộn nấm mèo, buộc lá hành, hầm lửa nhỏ đến mềm – canh đắng nhẹ, ngọt nước.",
    ["Ngâm nở nấm mèo, rửa sạch, băm nhỏ; trộn với thịt xay, đầu hành băm, hạt nêm, tiêu, dầu ăn cho dẻo.",
     "Rửa khổ qua, cắt đầu, bỏ hạt rồi nhồi nhân vào; trụng sơ lá hành để buộc quanh trái.",
     "Đun sôi nước, thả khổ qua vào, cho thêm thân và rễ ngò, hầm lửa nhỏ.",
     "Nêm đường, nước mắm, hạt nêm vừa ăn; hầm tiếp đến khi khổ qua mềm.",
     "Múc ra, rắc hành lá và ngò rí thái nhỏ."])

CT["tom_nuong_muoi_ot"] = ("Tôm biển ướp muối hạt, ớt bột, tỏi, chanh, mật ong rồi xiên que nướng đến khi đỏ vỏ – mặn cay, thơm.",
    ["Cắt đầu tôm, rửa sạch, để ráo.",
     "Trộn muối hạt, ớt bột, tỏi băm, nước cốt chanh, dầu ô liu, mật ong, đường và bột ngọt; cho tôm vào trộn đều, để 20 phút cho thấm rồi xiên que.",
     "Nướng trên bếp than hoặc bếp điện, trở đều tay; tôm chuyển đỏ là được, không nướng lâu kẻo thịt dính vỏ.",
     "Ăn với cơm nóng."])

# Nguồn ưu tiên: Món Ngon Mỗi Ngày (monngonmoingay.com) – món có bài ở đó dùng bài đó (đè các mục trên).
CT.update({'bo_kho': ('Thịt nạm bò ướp gia vị bò kho, xào săn rồi hầm mềm cùng sả, quế, hồi và cà rốt.',
            ['Làm sạch thịt bò với rượu trắng và gừng, cắt khối vuông cạnh 4cm. Ướp với muối, đường, hạt nêm, bột bò kho và dầu điều trong '
             '30 phút.',
             'Rang sơ quế và tai vị bằng lửa nhỏ rồi cho vào túi vải nhỏ. Cắt cà rốt khúc 5-6cm, đập dập sả.',
             'Phi thơm hành tím, tỏi, gừng và ớt băm, cho bò vào thêm dầu điều, xào lửa lớn cho săn. Rắc bột mì vào để thịt săn hơn.',
             'Khi thịt săn, đổ nước vào cùng bó sả và túi gia vị, hầm đến khi bò gần chín.',
             'Cho cà rốt, nêm thêm hạt nêm và thả lá thơm vào, nấu đến khi chín.',
             'Múc bò kho ra, trang trí với hành tây cắt lát, ngò gai và rau quế.',
             'Mẹo: Khử mùi bò bằng rượu trắng và gừng rồi rửa lại; dùng nạm bò sẽ nhanh mềm và ngon hơn bắp bò.']),
 'bo_nhung_giam': ('Bò thái mỏng nhúng nồi nước dừa giấm thơm sả hành, cuốn bánh tráng rau sống chấm mắm nêm.',
                   ['Rửa sạch thịt bò, thấm khô, cắt lát mỏng ngang thớ, xếp ra dĩa.',
                    'Hành tây cắt múi cau, hành tím đập dập. Sả đập dập, chừa một cây băm nhuyễn. Ớt, tỏi, thơm băm nhuyễn.',
                    'Pha nước giấm: trộn nước dừa với giấm gạo, đường, muối, bột ngọt, hành tây, hành tím và sả đập dập.',
                    'Pha mắm nêm: phi thơm sả, ớt, tỏi với dầu, cho mắm nêm, nước, đường vào đun sôi, hớt bọt. Để nguội rồi cho thơm băm '
                    'vào.',
                    'Đổ nước giấm vào nồi lẩu trên bếp, nhúng bò chín rồi cuốn bánh tráng với xà lách, rau thơm, dưa leo, khế, chuối chát, '
                    'bún, chấm mắm nêm.',
                    'Mẹo: Để thịt bò trong ngăn đá một ngày, rã đông khi còn hơi cứng sẽ dễ thái mỏng và mềm hơn.']),
 'bun_thit_nuong': ('Thịt nạc dăm ướp sả, mật ong nướng vàng, ăn cùng bún, rau sống, mỡ hành, đậu phộng và nước mắm chua ngọt.',
                    ['Cắt thịt mỏng vừa ăn, ướp với đường, nước tương, hạt nêm, muối, hành, tỏi, sả băm, dầu ăn, dầu điều, rượu ngũ vị '
                     'hương và mật ong trong 20 phút.',
                     'Rửa sạch rau thơm, xà lách, giá rồi cắt nhỏ. Rang vàng đậu phộng, giã nhỏ. Hành lá cắt nhỏ, dưa leo cắt sợi.',
                     'Xiên thịt, nướng trên than hoặc bếp gas đến khi chín vàng.',
                     'Pha nước mắm chua ngọt từ giấm gạo, đường, nước mắm, nước lọc, tỏi ớt băm. Đun nóng mỡ nước, đổ vào chén hành lá, '
                     'trộn đều làm mỡ hành.',
                     'Xếp bún, xà lách, rau thơm, dưa leo, giá vào tô, đặt thịt nướng lên, rưới mỡ hành, rắc đậu phộng. Ăn kèm đồ chua và '
                     'nước mắm.',
                     'Mẹo: Làm mỡ hành bằng cách cho chút muối vào hành lá rồi đổ dầu sôi vào; khi nướng thỉnh thoảng phết nước ướp lên '
                     'thịt cho thấm đều.']),
 'ca_chuon_kho_man': ('Cá chuồn kho cùng thịt ba chỉ, mít non, cà chua và nước mía, đậm vị cay mặn.',
                      ['Giã nhuyễn 3 đầu hành lá với 2 trái ớt hiểm. Cắt đôi cá, thịt ba chỉ cắt khối 1cm, ướp với hỗn hợp vừa giã cùng '
                       'bột ngọt, muối, ớt bột, nước mắm.',
                       'Giã dập 2 đầu hành còn lại nhét vào bụng cá. Hành lá cắt khúc 1cm, mít cắt khối 3–4cm.',
                       'Phi nóng dầu, xào một nửa cà chua hạt lựu với đường, muối đến khi mềm. Cho cá và thịt vào đảo đến khi săn lại, '
                       'thêm nước màu điều.',
                       'Đổ nước mía và nước vào sâm sấp mặt cá, cho mít, phần cà chua còn lại và 2 trái ớt hiểm đập dập vào.',
                       'Kho lửa vừa đến khi nước sánh lại, thêm cà chua bi kho tiếp 2 phút, cuối cùng cho hành lá. Múc ra đĩa, ăn với cơm '
                       'nóng.',
                       'Mẹo: Nhét đầu hành đập dập vào bụng cá để cá thơm và không bị bể khi kho.']),
 'ca_duc_chien_gion': ('Cá đục nhỏ tẩm bột chiên giòn vàng, ăn kèm thơm và cà chua trộn sốt chua cay.',
                       ['Hòa muối và rượu trắng vào nước lạnh, ngâm cá đục khoảng 15 phút rồi vớt ra thấm ráo.',
                        'Cắt thơm, cà chua hạt lựu. Cắt nhỏ ngò rí.',
                        'Đun nóng dầu, lăn cá qua bột tẩm khô chiên giòn rồi chiên vàng giòn, để ráo dầu.',
                        'Pha sốt từ hành tím băm, ớt sừng, muối, đường, giấm gạo, tương ớt và dầu ăn. Cho thơm, cà chua, ngò rí vào trộn '
                        'đều, để lạnh.',
                        'Xếp cá ra đĩa, ăn kèm phần thơm cà chua trộn.',
                        'Mẹo: Ngâm cá trong nước lạnh có muối và rượu để cá hết tanh, thấm vị và chắc thịt; tẩm bột chiên giòn giúp cá '
                        'vàng đều, không bị khô.']),
 'canh_bo_kim_chi': ('Bắp bò nấu nồi áp suất với nước kim chi, nấm đông cô, thêm kim chi, boa rô và ớt.',
                     ['Cắt bắp bò khối vuông 3cm, ướp với hạt nêm, tiêu và đường. Tỏi đập dập.',
                      'Cắt kim chi khúc 5cm, giữ lại nước kim chi. Nấm đông cô ngâm nở, bỏ chân, trộn với hạt nêm. Boa rô cắt xéo, ớt sừng '
                      'đập dập rồi cắt đôi.',
                      'Cho nước vào nồi áp suất cùng bắp bò, tỏi, nước kim chi và nấm, nấu khoảng 20 phút cho bò mềm.',
                      'Thêm kim chi, boa rô và ớt sừng, nấu thêm 5 phút rồi tắt bếp. Múc ra tô, dùng nóng với cơm, mì hoặc bún.',
                      'Mẹo: Cho tỏi đập dập vào nấu để tăng hương vị cho món canh.']),
 'canh_ca_nau_ngot': ('Canh cá chim trắng nấu ngót với cà chua, chua nhẹ vị giấm, thơm hành lá và cần tàu.',
                      ['Làm sạch cá, nhét hành lá và cần tàu đập dập vào bụng, ướp với giấm gạo, muối, bột ngọt.',
                       'Cà chua một trái cắt múi, một trái băm nhỏ. Phi thơm tỏi với dầu, xào cà chua băm, nêm muối và đường. Hành lá, cần '
                       'tàu cắt khúc 3cm, ớt sừng cắt lát.',
                       'Đun sôi nước, cho cá vào. Khi sôi lại, cho cà chua múi vào, nêm muối, đường, giấm gạo, bột ngọt.',
                       'Cho cà chua xào vào, tắt lửa, nêm nước mắm, thêm ớt và rau thơm. Múc ra tô, dùng nóng với cơm.',
                       'Mẹo: Ướp giấm để khử tanh và tạo vị chua; mua cà chua trước 2–3 ngày để chín hẳn ở nhiệt độ thường thì xào lên màu '
                       'đẹp.']),
 'canh_ca_ngu_nau_ca_thom': ('Canh cá ngừ ướp gia vị giã, nấu cùng cà chua, thơm, bắp chuối và sả dầu điều.',
                             ['Giã chung muối, hạt nêm, đầu hành lá, ớt hiểm và ớt bột. Ướp cá với hỗn hợp này 15 phút.',
                              'Cắt cà chua múi cau, thơm cắt lát, hành lá cắt khúc, sả đập dập cắt khúc.',
                              'Đun nóng dầu điều, xào thơm sả, cho hành tỏi băm vào xào hơi vàng, thêm cá vào xóc đều rồi tắt lửa.',
                              'Đun sôi nước, cho cá vào nấu sôi 4 phút. Thêm cà chua, thơm, nêm hạt nêm, đường, muối và khuấy đều.',
                              'Cho bắp chuối vào rồi tắt lửa, nêm thêm nước mắm, rắc hành lá.',
                              'Ăn với cơm trắng hoặc bún tươi, kèm nước mắm dầm ớt hoặc muối ớt.',
                              'Mẹo: Giã gia vị rồi ướp cá giúp cá thơm và thấm vị sau khi nấu.']),
 'canh_chua_ca_dieu_hong': ('Canh chua cá diêu hồng rán vàng ninh nhỏ lửa với cà chua, dọc mùng, dứa và thì là.',
                            ['Cắt khúc cá, rửa sạch, đầu cá bổ đôi. Thái dọc mùng, ngâm nước muối rồi rửa sạch. Bổ cau cà chua, thái miếng '
                             'dứa, thái nhỏ hành và thì là.',
                             'Rán cá vàng với dầu ăn rồi để riêng.',
                             'Phi thơm hành, cho cà chua vào xào chín, đổ nước vào đun sôi.',
                             'Thả cá vào ninh nhỏ lửa khoảng 30 phút cho nước ngọt.',
                             'Nêm gia vị lẩu Thái nêm sẵn, cho dọc mùng và dứa vào đun sôi rồi tắt lửa. Múc ra bát, thêm rau thơm, ăn '
                             'nóng.',
                             'Mẹo: Nên nấu cả đầu cá vì phần này nhiều mỡ, giúp canh béo hơn; lượng dứa gia giảm theo độ chua mong muốn.']),
 'canh_khoai_so_suon': ('Canh sườn non xào săn nấu nồi áp suất cùng khoai sọ, cà rốt, rắc ngò gai ngò om.',
                        ['Gọt sạch khoai sọ, củ lớn cắt đôi. Cà rốt tỉa hoa, cắt lát dày 3 li. Ngò gai, ngò om rửa sạch, cắt nhỏ. Đầu hành '
                         'trắng băm, phần lá cắt khúc.',
                         'Chặt sườn khúc 2cm, ướp với đầu hành trắng, hạt nêm và tiêu cho thấm.',
                         'Phi thơm tỏi trong nồi áp suất, cho sườn vào xào săn.',
                         'Thêm nước, khoai sọ, cà rốt, nêm hạt nêm, đậy nắp nấu sôi khoảng 7 phút.',
                         'Múc canh ra tô, rắc ngò gai, ngò om, hành lá và tiêu, dùng nóng.',
                         'Mẹo: Rửa khoai sọ bằng nước bột năng hoặc nước vo gạo để sạch cát, đỡ ngứa tay; xào sườn trước để thịt ngọt, mau '
                         'nhừ.']),
 'canh_muc_nau_chua': ('Canh chua khế, thơm, cà chua thả viên mực trộn thịt heo, thơm ngò gai lá quế, ăn kèm bún.',
                       ['Băm nhỏ mực. Khế cắt lát mỏng, thơm cắt rẻ quạt, hành tây và cà chua cắt múi cau, hành tím cắt lát, đầu hành lá '
                        'băm, chanh vắt lấy nước, ngò gai và lá quế cắt khúc, ớt sừng cắt lát mỏng.',
                        'Trộn đều mực băm với thịt xay, đầu hành lá, hạt nêm, tiêu, bột ngọt và dầu ăn.',
                        'Phi thơm hành tím, cho thơm và cà chua vào xào mềm, thêm khế và hành tây xào tiếp, nêm bột ngọt và muối.',
                        'Đổ nước vào đun sôi, nêm đường, hạt nêm, nước mắm, nước cốt chanh. Khi sôi lại, dùng muỗng múc nhân mực thành '
                        'viên thả vào nồi.',
                        'Đợi sôi lại, vớt bọt, cho ngò gai, lá quế, ớt vào rồi tắt lửa. Múc ra tô, trang trí ớt lát và húng quế, dùng với '
                        'bún.',
                        'Mẹo: Trộn thêm dầu vào mực để viên mực không bị khô.']),
 'canh_muop_mong_toi': ('Canh mồng tơi và mướp hương nấu với tôm băm xào hành phi, ngọt mát, dễ ăn.',
                        ['Cắt mồng tơi thành khúc vừa ăn. Bào vỏ mướp hương, cắt miếng vừa ăn.',
                         'Phi thơm hành tím băm với dầu ăn, cho tôm băm vào xào thơm.',
                         'Đổ nước vào nồi, đun sôi rồi cho mướp và mồng tơi vào nấu chín.',
                         'Nêm bột canh, hạt nêm và bột ngọt, khuấy đều rồi tắt lửa.',
                         'Múc canh ra tô, ăn nóng với cơm trắng.',
                         'Mẹo: Xào tôm với hành tím cho canh thơm hơn; chọn mướp hương để canh ngọt và ngon hơn.']),
 'cha_la_lot': ('Chả thịt heo trộn giò sống, mỡ và lá lốt thái nhuyễn, ép khuôn vuông chiên vàng.',
                ['Thái lá lốt thành sợi nhuyễn. Cắt nhỏ mỡ heo.',
                 'Trộn đều thịt băm, giò sống, mỡ heo, lá lốt, hành tỏi băm; nêm tiêu, đường, nước mắm, bột ngọt và để 15 phút cho thấm.',
                 'Chia hỗn hợp thành 8 phần, dùng khuôn inox vuông để tạo hình.',
                 'Đun nóng dầu, chiên chả đến khi vàng, vớt ra để ráo dầu.',
                 'Xếp chả ra đĩa, rưới sốt mayonnaise, trang trí ớt băm; ăn cùng xôi đậu xanh và bắp cải cà rốt bóp chua.',
                 'Mẹo: Cho lá lốt vào nhân để món thêm hương vị.']),
 'chao_ech': ('Cháo trắng gạo tẻ pha nếp nấu lá dứa, ăn kèm ếch kho sệt cay thơm gừng ớt.',
              ['Nấu cháo từ hai phần gạo tẻ, một phần gạo nếp với chút muối và hai lá dứa.',
               'Làm sạch ếch với rượu trắng và muối, cắt miếng vừa ăn. Ướp với ớt bột, bột ngọt, hạt nêm, rượu mai quế lộ và gừng trong 15 '
               'phút.',
               'Pha hỗn hợp kho gồm nước dùng gà, nước tương, hắc xì dầu, đường và hạt nêm.',
               'Đun sôi hỗn hợp kho, thêm ớt khô, gừng băm, cho ếch vào kho lửa lớn đến khi săn. Hạ lửa vừa, kho đến khi ếch chín săn, '
               'thấm vị và nước hơi sánh.',
               'Cho dầu mè vào trộn đều, thêm hành lá rồi tắt lửa.',
               'Múc cháo ra nồi đất, làm nóng, dọn kèm nồi ếch kho.',
               'Mẹo: Kho ếch lửa lớn với nhiều gia vị để thịt chín săn và thấm vị.']),
 'chao_trung_thit_bam': ('Cháo gạo tẻ và nếp nấu nhừ với thịt heo băm xào tơi, kèm trứng gà chần nguyên quả.',
                         ['Vo sạch gạo tẻ và nếp, nấu với nước đến khi cháo nở đặc sệt.',
                          'Hành lá lấy đầu trắng băm nhuyễn, phần lá cắt nhỏ cùng ngò rí. Băm nhuyễn thịt heo, ướp với hành tím băm, hạt '
                          'nêm, tiêu và chút nước lọc trong 15 phút.',
                          'Đun sôi nước có pha giấm gạo, hạ lửa, đập trứng thả nhẹ cho lòng trắng bao quanh lòng đỏ. Luộc đến khi trứng '
                          'nổi, vớt ra rửa nước lạnh, bóc bớt màng lòng trắng dính quanh.',
                          'Thêm nước lạnh vào nồi cháo, nấu tiếp đến khi cháo nhừ.',
                          'Phi thơm hành tím băm với dầu ăn, xào thịt vừa chín và tơi rồi cho vào nồi cháo. Nêm hạt nêm và nước mắm cho '
                          'vừa ăn.',
                          'Múc cháo ra tô, đặt trứng vào, rắc hành lá, ngò rí và tiêu, ăn nóng.',
                          'Mẹo: Ướp thịt với ít nước lạnh để khi xào thịt tơi đều.']),
 'chim_cut_ro_ti': ('Chim cút chiên săn rồi rim lửa nhỏ với nước dừa, sả, hành tỏi và trứng cút.',
                    ['Rửa cút với ít muối, để ráo, chặt đôi. Cắt hành tây múi cau 0.5cm, hành lá khúc 2cm, sả đập dập cắt khúc. Luộc chín '
                     'trứng cút, bóc vỏ.',
                     'Ướp cút với nước hành tỏi, bột ngọt, muối, hạt nêm, ngũ vị hương và nước tương cho thấm.',
                     'Đun dầu, chiên sơ cút cho săn và vàng đều hai mặt. Cho dầu điều, xác hành tỏi và sả vào đảo đều.',
                     'Thêm trứng cút và nước dừa, rim lửa nhỏ cho cút thấm gia vị.',
                     'Khi cút gần chín, cho hành tây vào rim thêm 2 phút đến khi nước sánh, rắc hành lá, ngò rí rồi tắt bếp.',
                     'Bày cút ra đĩa cùng xà lách, cà chua, rau răm; ăn với cơm, bánh mì hoặc xôi.',
                     'Mẹo: Chiên sơ cút trước khi rô ti giúp thịt săn và thấm vị hơn; sả đập dập tạo mùi thơm cho món.']),
 'com_chien_kim_chi': ('Cơm chiên kim chi kiểu Hàn với bò, bắp, tương ớt gochujang, phủ trứng ốp la, mè và rong biển.',
                       ['Nấu cơm khô ráo để chiên. Cắt bò khối 5mm, ướp gừng và nước tương. Kim chi cắt sợi ngang 3mm, vắt ráo, giữ nước. '
                        'Hành lá cắt nhỏ, để riêng phần đầu. Chiên trứng ốp la.',
                        'Phi thơm một phần tỏi với dầu, xào bò chín tái rồi trút ra.',
                        'Thêm dầu, phi thơm phần tỏi còn lại với đầu hành. Cho kim chi, bắp vào xào thơm, thêm tương ớt Hàn Quốc và nước '
                        'kim chi khuấy tan.',
                        'Cho cơm, bột ngọt, nước tương vào trộn đều, nêm vừa ăn, chiên lửa vừa đến khi hạt cơm rám mặt. Cho bò, hành lá, '
                        'dầu mè vào xóc đều.',
                        'Nén cơm vào chén, úp ra đĩa, đặt trứng ốp la lên, rắc mè rang và rong biển. Dùng nóng, chan nước tương tùy thích.',
                        'Mẹo: Xào kim chi đã vắt ráo trước để thơm, bớt chua gắt; cho dầu mè sau cùng để giữ mùi thơm và hạt cơm bóng.']),
 'ga_rang_muoi': ('Gà ta tẩm bột chiên vàng, xóc muối nếp đậu xanh rang xay, thêm sả, gừng, lá chanh chiên giòn.',
                  ['Chặt gà miếng vừa ăn, ướp với hạt nêm, bột ngọt, nước mắm, tiêu, lòng đỏ trứng và dầu ăn, để tủ lạnh 30 phút. Sả cắt '
                   'khúc đập dập, chẻ sợi mỏng; gừng và lá chanh thái sợi nhuyễn.',
                   'Ngâm gạo nếp và đậu xanh 10–15 phút, để ráo, rang lần lượt đến chín thơm. Xay cùng muối hột cho nhỏ nhưng không quá '
                   'mịn.',
                   'Đun nóng dầu, chiên giòn lần lượt sả, gừng, lá chanh rồi vớt ra để ráo dầu.',
                   'Tẩm gà qua bột năng, chiên chín vàng, vớt ra thấm dầu rồi cho muối vào xóc đều cho bám khắp miếng gà.',
                   'Cho gà ra dĩa, rải sả, gừng, lá chanh lên trên, trộn đều khi ăn.',
                   'Mẹo: Rang nếp và đậu xanh vừa thơm, không để vàng; xóc muối khi gà còn nóng để muối bám tốt hơn.']),
 'khoai_tay_xao_bo': ('Bò mềm ướp mayonnaise xào cùng khoai tây hấp áp chảo vàng, cà chua và rau cần tàu.',
                      ['Cắt nhỏ thịt bò, ướp với hạt nêm, đường, tỏi băm, tiêu và xốt mayonnaise.',
                       'Cắt khoai tây thành 6 múi, trộn với muối, bột ngọt và chút nước, bọc vải mùng quanh tô rồi hấp chín (hoặc dùng lò '
                       'vi sóng). Cà chua cắt 6 múi, rau cần tàu cắt khúc khoảng 4cm.',
                       'Đun nóng chút dầu, áp chảo nhanh khoai tây cho vàng nâu rồi lấy ra dĩa.',
                       'Phi vàng tỏi, cho bò vào đảo đều, tiếp đến cà chua và khoai tây. Thêm nước, tương cà, mayonnaise, nước mắm, cuối '
                       'cùng cho rau cần tàu vào rồi tắt lửa.',
                       'Xếp khoai tây, cà chua quanh dĩa, bò ở giữa, trang trí ngò và dùng nóng.',
                       'Mẹo: Ướp bò với mayonnaise giúp thịt mềm, thơm; hấp chín khoai trước khi xào để khoai mềm dẻo hơn.']),
 'long_ga_xao_gia_dua': ('Lòng gà khử mùi, ướp đậm, xào nhanh lửa lớn cùng giá, hẹ và cà rốt giòn ngọt.',
                         ['Rửa lòng gà bằng nước muối, xả lại nước lạnh, chần qua nước sôi có rượu để khử tanh. Để ráo, cắt miếng vừa ăn; '
                          'mề gà chẻ đôi, khứa caro mặt cắt.',
                          'Ướp lòng gà với muối, tiêu, nước mắm và bột ngọt cho thấm.',
                          'Rửa giá, hẹ bằng nước đá pha muối; hẹ cắt khúc 5cm. Cà rốt cắt sợi bằng cọng giá, ngò rí rửa để ráo, ớt cắt '
                          'lát.',
                          'Phi thơm một nửa hành tím với dầu ăn, xào lòng gà chín rồi trút ra đĩa.',
                          'Phi thơm phần hành tím còn lại, xào cà rốt chín, thêm giá xào lửa lớn, nêm đường, muối, tiêu, bột ngọt. Cho hẹ '
                          'và lòng gà vào đảo nhanh, nếm vừa ăn rồi tắt bếp.',
                          'Múc ra đĩa, rắc tiêu và ngò rí, ăn nóng kèm nước tương và ớt.',
                          'Mẹo: Khứa caro mề gà để dễ thấm và không dai; rửa giá, hẹ bằng nước đá có muối cho sạch và giòn hơn.']),
 'luon_om_chuoi_dau': ('Lươn om cùng thịt ba chỉ, chuối xanh, đậu hũ chiên với nghệ, mắm tôm, lá lốt và tía tô.',
                       ['Cắt lươn khúc 3cm, ướp với nước nghệ, hành tỏi băm, bột ngọt, muối, tiêu và đường. Cắt thịt ba chỉ miếng vừa ăn, '
                        'ướp giống lươn.',
                        'Cắt khúc chuối xanh, ngâm nước, chần qua nước sôi có chanh hoặc muối, để ráo rồi trộn nước nghệ khi còn nóng.',
                        'Thái sợi lá lốt, tía tô. Cắt đậu hũ chiên thành miếng vuông nhỏ.',
                        'Phi thơm hành tỏi băm, cho thịt vào xào săn. Thêm lươn và chuối, om khoảng 5 phút.',
                        'Cho đậu hũ, ớt hiểm, mắm tôm, giấm gạo và nước vào, đậy nắp om khoảng 10 phút. Trộn tía tô, lá lốt, ớt sợi rồi '
                        'tắt lửa, ăn với cơm trắng.',
                        'Mẹo: Trộn chuối với nghệ khi còn nóng cho chuối lên màu đẹp; xào thịt săn tươm mỡ để món hấp dẫn hơn.']),
 'nui_xao_bo': ('Nui xào se mặt chiên cùng trứng thành bánh nhỏ, phủ bò xào hành tây và cải ngọt.',
                ['Luộc mềm nui trong nước có ít dầu, xả nước lạnh, để ráo rồi trộn với chút hạt nêm và xốt cà chua.',
                 'Băm gừng, tỏi, thêm nước ấm vắt lấy nước; bột năng hòa với nước. Hành tây cắt múi cau, cải ngọt cắt khúc 7cm để riêng '
                 'thân và lá, ngò rí cắt nhỏ.',
                 'Thái mỏng thịt bò, ướp với nước gừng, nước tỏi, rượu ngũ vị, hạt nêm, nước tương, tiêu và nước bột năng.',
                 'Đun nóng dầu, nêm hạt nêm, xào nui đến khi se mặt. Chia nui thành từng phần, đập trứng vào chiên thành bánh nhỏ, xếp ra '
                 'dĩa, giữ nóng.',
                 'Xào chín hành tây và cải ngọt rồi trút ra. Xào bò vừa chín tới, cho rau trở lại trộn đều, nêm hạt nêm, tiêu, tắt bếp.',
                 'Cho bò lên nui, rắc tiêu, trang trí ngò rí, chấm nước tương pha tương ớt.',
                 'Mẹo: Xào nui khi đã nguội để dễ rám mặt, không dính chảo; áo bột năng cho bò để thịt không khô, giữ vị ngọt.']),
 'pho_ga': ('Phở gà nước dùng hầm xương gà, xương heo trong ngọt, thịt gà xé, thơm lá chanh.',
            ['Rửa sạch xương gà, xương heo, chần qua nước sôi rồi rửa lại bằng nước lạnh. Ướp thịt gà với muối, tiêu, bột ngọt và nước '
             'mắm.',
             'Nướng sơ gừng, hành tím, rễ ngò rồi bọc trong vải mùng, buộc lại.',
             'Cho xương vào nồi nước lạnh, đun sôi rồi hạ lửa, hớt bọt kỹ. Thêm cần tây, hành boaro và túi gia vị nướng, ninh nhỏ lửa 2-3 '
             'giờ rồi lọc lấy nước dùng.',
             'Hành lá lấy đầu trắng trụng nước sôi, phần lá cắt nhỏ. Hành tây thái mỏng, lá chanh thái sợi nhỏ, ngò gai rửa sạch để ráo.',
             'Đun sôi nước dùng, nêm muối hột, nước mắm, hạt nêm, đường phèn và bột ngọt. Cho thịt gà vào luộc chín, vớt ngâm nước đá rồi '
             'xé sợi.',
             'Trụng bánh phở qua nước nóng, vẩy ráo cho vào tô, xếp gà, hành lá, hành tây, ngò gai, lá chanh lên. Chan nước dùng đang sôi, '
             'ăn nóng kèm nước mắm, ớt và chanh.',
             'Mẹo: Nêm muối hột và đường phèn để nước dùng ngọt thanh.']),
 'suon_ram_man_ngot': ('Sườn non ướp hành tỏi, xào săn trong nước màu rồi ram lửa vừa đến mềm, sốt sánh mặn ngọt.',
                       ['Rửa sạch sườn, chặt miếng dài khoảng 3cm, ướp với hạt nêm, đường, muối, hành tỏi băm, nước mắm, đảo đều và để 15 '
                        'phút.',
                        'Cắt sợi hành lá và ớt sừng, dưa leo cắt lát.',
                        'Thắng nước màu với dầu và chút đường, nêm ít nước mắm rồi cho sườn vào xào săn.',
                        'Thêm nước, đậy vung, nấu lửa vừa đến khi sườn mềm và nước sánh lại.',
                        'Cho sườn ra dĩa, trang trí ớt, dưa leo và chút ngò. Ăn kèm cơm, rau, dưa.',
                        'Mẹo: Thắng nước màu trực tiếp với dầu trong chảo rồi thêm nước mắm để có sốt sánh, thơm; chọn sườn có sụn nhỏ, '
                        'nhiều thịt.']),
 'suon_xao_chua_ngot': ('Sườn non áo bột năng chiên vàng, sốt chua ngọt cùng hành tây và ớt chuông ba màu.',
                        ['Cắt hành tây, ớt chuông thành miếng vuông cạnh 3cm. Chẻ dọc sườn non, chặt khúc dài 4cm.',
                         'Ướp sườn với đường, muối, bột ngọt, nước tương, tiêu và hành tím băm khoảng 10 phút, rồi trộn lòng trắng trứng '
                         'và lăn qua một lớp bột năng mỏng.',
                         'Pha nước sốt gồm giấm gạo, đường, nước tương, hạt nêm, nước và tương cà.',
                         'Xào sơ hành tây, ớt chuông rồi trút ra đĩa. Đun nóng dầu, chiên sườn vàng, vớt ra để ráo dầu.',
                         'Phi thơm tỏi, đổ nước sốt vào, cho sườn vào xào lửa nhỏ khoảng 5 phút đến khi chín mềm. Thêm chút nước bột năng '
                         'cho sốt sệt, cho hành tây, ớt chuông vào, nêm lại cho vị chua ngọt dịu.',
                         'Bày sườn ra đĩa, rắc tiêu, trang trí ngò rí, ăn nóng với cơm.',
                         'Mẹo: Áo bột năng sau khi ướp giúp gia vị thấm, giữ nước ngọt trong thịt nên sườn xào xong không bị khô.']),
 'tom_nuong_muoi_ot': ('Tôm sú ướp sốt ớt và gấc xay nhuyễn, nướng lò 220 độ C đỏ đẹp, cay thơm.',
                       ['Cắt bỏ chân, phần nhọn ở đầu và đuôi tôm, dùng kéo xẻ dọc lưng tôm.',
                        'Xay nhuyễn cơm gấc, ớt sừng, ớt Ba Tri, tỏi băm, đường, muối, nước mắm, ớt bột, dầu điều và bột ngọt thành sốt.',
                        'Cho sốt vào tôm, ướp 20 phút cho thấm.',
                        'Xếp tôm lên vỉ, nướng lò 220 độ C trong 15 phút, thường xuyên phết sốt lên tôm.',
                        'Bày tôm ra đĩa, ăn nóng với bánh mì.',
                        'Mẹo: Xay thật nhuyễn sốt để dễ bám và thấm vào tôm; cơm gấc tạo màu đỏ đẹp khi tôm chín.']),
 'vit_nau_thom': ('Vịt chiên bớt mỡ rồi nấu cùng thơm, nước dừa, quế, đinh hương đến chín mềm, nước sốt sánh nhẹ.',
                  ['Rửa da vịt bằng gừng giã và rượu cho hết mùi hôi, xả sạch, để ráo. Khứa vài đường trên da rồi chiên cho ra bớt mỡ; '
                   'khứa dọc phía trong má đùi và đùi cho dễ thấm.',
                   'Ướp vịt với nước cốt hành tím, nước tương, muối, tiêu, hạt nêm trong 30 phút. Thơm gọt vỏ, tỉa sọc, bỏ lõi, cắt miếng '
                   'vừa ăn rồi ướp chút đường, muối; dừa chặt lấy nước; hành tây cắt múi, ớt sừng cắt lát; bột năng hòa với nước.',
                   'Cho vịt vào nồi không cần dầu, thêm dầu điều, quế, đinh hương, lá thơm, nước ép thơm và nước dừa. Nấu lửa to đến khi '
                   'sôi rồi giảm lửa.',
                   'Nêm hạt nêm, cho thơm và hành tây vào, nấu đến khi vịt chín mềm. Rót từ từ nước bột năng, khuấy đến khi nước sánh vừa '
                   'thì tắt bếp.',
                   'Múc vịt ra đĩa sâu lòng, rắc tiêu, trang trí ngò rí. Ăn kèm bánh mì, nước tương và ớt lát.',
                   'Mẹo: Khứa các đường song song trên da để mỡ chảy ra bớt khi chiên; thích béo thì giữ lại mỡ chiên để nấu.'])})

# Món nhà nấu 10/2026. Cá liệt kho theo bài cá đối kho cà chua (chủ nhà: kho như mọi loại cá biển khác).
CT["ca_liet_kho_ca_chua"] = ("Cá biển ướp nước mắm, giấm, hành tỏi rồi kho với cà chua phi thơm trong dầu điều – nước kho đỏ, chua ngọt, cá chắc thịt.",
    ["Cá làm sạch, để nguyên con hoặc cắt đôi. Ướp với 1/2 muỗng canh muối, chút tiêu, 1 muỗng canh hành tỏi băm, "
     "1 muỗng canh nước mắm, 1 muỗng canh giấm gạo (bài gốc thêm 1/2 muỗng canh bột ngọt).",
     "Cà chua: 2 quả cắt múi cau, 1 quả cắt nhỏ. Ớt hiểm đập dập, hành lá cắt khúc.",
     "Đun nóng 2 muỗng canh dầu điều, phi thơm phần hành tỏi băm còn lại, cho cà chua cắt nhỏ vào xào sơ cùng chút muối, đường.",
     "Xếp cá vào, chế nước sôi ngập cá, nêm 2 muỗng canh nước mắm. Kho lửa lớn đến khi cá săn lại.",
     "Cho cà chua múi cau và ớt vào, hạ lửa nhỏ kho tiếp cho cá chín, thấm gia vị. Nước sệt lại thì thêm hành lá, rắc tiêu, tắt bếp.",
     "Mẹo: cà chua băm cho màu và vị, cà chua múi cho đẹp; giấm lúc ướp giúp cá thơm, chua nhẹ."])
CT["canh_bo_nau_dua_ca_chua"] = ("Canh chua bò nấu dứa, cà chua, dọc mùng, me – thịt bò thả sau cùng nên mềm, nước canh chua thanh.",
    ["Rửa sạch dọc mùng, dứa, cà chua, giá, rau ngổ, ớt. Dọc mùng tước vỏ, cắt khúc vắt ráo; cà chua bổ 4; dứa cắt miếng vừa ăn; ớt thái mỏng.",
     "Me dầm với nửa bát nước lấy nước cốt. Thịt bò rửa nước muối, thái mỏng.",
     "Đun nồi nước cùng nước cốt me, cho dọc mùng, dứa, cà chua vào nấu sôi 2–3 phút.",
     "Thả thịt bò, nêm nước mắm, hạt nêm, đường.",
     "Cho giá, rau ngổ, ớt, đun sôi lại một dạo, nêm lại cho vừa rồi tắt bếp."])
