"""Lô 1 – 44 món khẩu vị miền Bắc, nguyên liệu có quanh năm ở Phan Rang.

Cùng quy ước với scripts/recipes.py:
  Nguyên liệu: (mã hoặc "", tên, số lượng, đơn vị, "n"=theo_nguoi / "x"=theo_noi, vai trò)
Định lượng cho 4 người (đồ uống 2 phần). Cách làm viết lại bằng lời của Cá Chef,
link Cookpad ở cột nguon chỉ để tham khảo. Tất cả "chua_nau_thu".
"""

CP = "https://cookpad.com/vn/cong-thuc/"
TK = "https://cookpad.com/vn/tim-kiem/"
MC, MCF = "muỗng canh", "muỗng cà phê"
Q = [1] * 12  # có hàng quanh năm


def ro(*thang):
    """Có hàng quanh năm, ngon/rộ nhất (2) vào các tháng cho trước."""
    return [2 if t in thang else 1 for t in range(1, 13)]


MUA_MUA = (9, 10, 11)  # mùa mưa Phan Rang (mưa tập trung tháng 9–11)

# Nguyên liệu mới: (mã, tên, nhóm, vùng, lịch 12 tháng, nơi mua, tin cậy, ghi chú)
NGUYEN_LIEU = [
    ("thit_bo", "Thịt bò", "thịt", "chung", Q, "GO!/chợ", "A", "Bán quanh năm ở chợ và GO!"),
    ("ech", "Ếch", "thịt", "chung", ro(*MUA_MUA), "chợ", "C", "Ếch nuôi có quanh năm; ếch đồng nhiều, béo vào đầu mùa mưa"),
    ("cua_dong", "Cua đồng", "hải sản", "chung", ro(*MUA_MUA), "chợ", "C", "Cua đồng xay sẵn/đông lạnh quanh năm; cua tươi nhiều, chắc vào mùa mưa"),
    ("dau_phu", "Đậu phụ", "đậu", "chung", Q, "GO!/chợ", "A", "Sản phẩm chế biến, có quanh năm"),
    ("rau_muong", "Rau muống", "rau củ", "Ninh Thuận", ro(8, 9, 10), "chợ/GO!", "C", "Trồng quanh năm; mùa mưa ra ngọn non, rẻ – chưa có nguồn riêng"),
    ("mong_toi", "Mồng tơi", "rau củ", "Ninh Thuận", ro(7, 8, 9, 10), "chợ", "C", "Rau mùa hè–mưa, lá dày ngon nhất tháng 7–10 – chưa có nguồn riêng"),
    ("rau_day", "Rau đay", "rau củ", "chung", ro(5, 6, 7, 8), "chợ", "C", "Rau mùa hè; ít gặp hơn ở miền Nam – chưa có nguồn"),
    ("rau_ngot", "Rau ngót", "rau củ", "chung", Q, "chợ", "C", "Chưa có nguồn riêng"),
    ("la_lot", "Lá lốt", "rau củ", "chung", Q, "chợ", "C", "Chưa có nguồn riêng"),
    ("chuoi_xanh", "Chuối xanh (chuối chát)", "trái cây", "chung", Q, "chợ", "C", "Chưa có nguồn riêng"),
    ("ngo", "Ngô (bắp)", "rau củ", "Ninh Thuận", Q, "chợ/GO!", "C", "Bắp nếp/bắp Mỹ có quanh năm – chưa có nguồn riêng"),
    ("khoai_mon", "Khoai sọ / khoai môn", "rau củ", "chung", Q, "chợ", "C", "Chưa có nguồn riêng"),
    ("khoai_lang", "Khoai lang", "rau củ", "chung", Q, "chợ/GO!", "C", "Chưa có nguồn riêng"),
    ("dau_bap", "Đậu bắp", "rau củ", "Ninh Thuận", Q, "chợ", "C", "Chưa có nguồn riêng"),
    ("dau_co_ve", "Đậu cô ve (đậu que)", "rau củ", "Đà Lạt", Q, "GO!/chợ", "A", "Rau Đà Lạt có quanh năm"),
    ("sup_lo_trang", "Súp lơ trắng", "rau củ", "Đà Lạt", Q, "GO!/chợ", "A", "Rau Đà Lạt có quanh năm"),
    ("su_hao", "Su hào", "rau củ", "Đà Lạt", Q, "GO!/chợ", "A", "Rau Đà Lạt có quanh năm"),
    ("cu_cai", "Củ cải trắng", "rau củ", "Đà Lạt", Q, "GO!/chợ", "A", "Rau Đà Lạt có quanh năm"),
    ("can_tay", "Cần tây", "rau củ", "Đà Lạt", Q, "GO!/chợ", "A", "Rau Đà Lạt có quanh năm"),
    ("bi_dao", "Bí đao", "rau củ", "chung", Q, "chợ/GO!", "C", "Chưa có nguồn riêng"),
    ("bi_do", "Bí đỏ (bí ngô)", "rau củ", "chung", Q, "chợ/GO!", "C", "Chưa có nguồn riêng"),
    ("bau", "Bầu", "rau củ", "chung", Q, "chợ", "C", "Chưa có nguồn riêng"),
    ("muop", "Mướp hương", "rau củ", "chung", Q, "chợ", "C", "Chưa có nguồn riêng"),
    ("ca_tim", "Cà tím", "rau củ", "chung", Q, "chợ/GO!", "C", "Chưa có nguồn riêng"),
    # Bổ sung lịch mùa vụ (07/10/2026): nguyên liệu chính của các món trước đây chưa có mã
    ("ca_loc", "Cá lóc", "thủy sản", "chung", ro(*MUA_MUA), "chợ", "C", "Cá nuôi có quanh năm; cá đồng nhiều, rẻ vào mùa mưa"),
    ("ca_bac_ma", "Cá bạc má", "hải sản", "Ninh Thuận", ro(12, 1, 2, 3), "chợ", "C", "Có quanh năm; tạm coi rộ mùa gió bấc – chưa có nguồn"),
    ("ca_chim", "Cá chim", "hải sản", "chung", Q, "chợ/GO!", "C", "Chưa có nguồn riêng"),
    ("ghe", "Ghẹ", "hải sản", "Ninh Thuận", ro(4, 5, 6, 7, 8), "chợ/vựa", "C", "Ghẹ chắc, nhiều khi biển êm (tháng 4–8); nguồn tham khảo vùng khác"),
    ("cua_bien", "Cua biển", "hải sản", "chung", Q, "chợ/vựa", "C", "Cua nuôi có quanh năm"),
    ("ngheu", "Nghêu / ngao / sò", "hải sản", "chung", Q, "chợ/GO!", "B", "Chủ yếu là hàng nuôi, có quanh năm"),
    ("oc", "Ốc (ốc hương, ốc biển)", "hải sản", "Ninh Thuận/Khánh Hòa", Q, "chợ/vựa", "B", "Ốc hương nuôi ở Ninh Thuận, Khánh Hòa"),
    ("so_diep", "Sò điệp", "hải sản", "chung", Q, "chợ/GO!", "C", "Chưa có nguồn riêng"),
    ("dua_leo", "Dưa leo", "rau củ", "Ninh Thuận", Q, "chợ/GO!", "C", "Trồng quanh năm"),
    ("cai_xanh", "Rau cải (cải ngọt, chíp, ngồng, bẹ)", "rau củ", "chung", ro(12, 1, 2), "chợ/GO!", "C", "Có quanh năm; mùa lạnh cải ngồng, cải bẹ ngon hơn – chưa có nguồn"),
    ("rau_bi", "Ngọn bí", "rau củ", "chung", ro(8, 9, 10, 11), "chợ", "C", "Mùa mưa bí ra ngọn nhiều – chưa có nguồn"),
    ("rau_den", "Rau dền", "rau củ", "chung", ro(5, 6, 7, 8), "chợ", "C", "Rau mùa hè – chưa có nguồn"),
    ("rau_lang", "Rau lang", "rau củ", "chung", Q, "chợ", "C", "Chưa có nguồn riêng"),
    ("rau_ma", "Rau má", "rau củ", "chung", ro(*MUA_MUA), "chợ", "C", "Mùa mưa rau má mọc tốt, lá to – chưa có nguồn"),
    ("gia_do", "Giá đỗ", "rau củ", "chung", Q, "chợ/GO!", "A", "Giá ủ, có quanh năm"),
    ("ca_phao", "Cà pháo", "rau củ", "chung", Q, "chợ", "C", "Chưa có nguồn riêng"),
    ("buoi", "Bưởi", "trái cây", "chung", ro(8, 9, 10), "chợ/GO!", "B", "Bưởi chính vụ quanh Trung thu (8–10); da xanh có quanh năm"),
    ("dua", "Dừa", "trái cây", "chung", Q, "chợ/GO!", "A", "Có quanh năm"),
    ("mia", "Mía", "khác", "chung", ro(12, 1, 2, 3), "chợ", "B", "Vụ ép mía từ cuối năm đến đầu năm sau"),
    ("nha_dam", "Nha đam", "rau củ", "Ninh Thuận", Q, "chợ/vựa", "A", "Đặc sản Ninh Thuận, thu hoạch quanh năm"),
    ("hat_sen", "Hạt sen", "hàng khô", "chung", ro(6, 7, 8), "chợ/GO!", "B", "Sen tươi vào mùa hè; hạt sen khô có quanh năm"),
    ("dau_hat", "Đậu xanh / đỏ / đen", "hàng khô", "chung", Q, "chợ/GO!", "A", "Hàng khô"),
    ("gao_nep", "Gạo nếp / nếp cẩm", "tinh bột", "chung", Q, "chợ/GO!", "A", "Hàng khô"),
    ("suong_sao", "Sương sáo", "khác", "chung", Q, "chợ", "A", "Hàng làm sẵn"),
]


def R(ma, ten, loai, nhiet, do_nang, dau_mo, chinh, thoi_tiet, phut, do_kho, mo_ta,
      cach_lam, pho_bien, nguon, nguyen_lieu, khau_phan=4):
    return dict(ma=ma, ten=ten, loai=loai, nhiet=nhiet, do_nang=do_nang, dau_mo=dau_mo,
                chinh=chinh, thoi_tiet=thoi_tiet, khau_phan=khau_phan, phut=phut,
                do_kho=do_kho, mo_ta=mo_ta, cach_lam=cach_lam, pho_bien=pho_bien,
                nguon=nguon, nguyen_lieu=nguyen_lieu)


# Gia vị hay dùng
MAM = lambda n: ("mam_ca_na", "Nước mắm", n, MC, "x", "gia_vi")
TOI = lambda n: ("toi_pr", "Tỏi", n, "tép", "x", "gia_vi")
HANH = lambda n: ("hanh_tim", "Hành tím", n, "củ", "x", "gia_vi")
DUONG = lambda n: ("", "Đường", n, MC, "x", "gia_vi")
DAU = lambda n: ("", "Dầu ăn", n, MC, "x", "gia_vi")
HAT_NEM = lambda n: ("", "Hạt nêm", n, MCF, "x", "gia_vi")
TIEU = ("", "Tiêu", None, "vừa đủ", "x", "gia_vi")
HANH_LA = ("", "Hành lá", 1, "bó", "x", "phu")

RECIPES = [
    # ---------- Bò ----------
    R("pho_bo_tai_chin", "Phở bò tái chín", "mon_chinh", "nong", "nhe", "it", "thit_bo", "mua", 180, "vua",
      "Nước dùng xương bò ninh quế hồi, thịt bò chín và tái thái mỏng – món ấm bụng ngày mưa (kiểu Bắc).",
      ["Xương bò chần nước sôi 5 phút, đổ nước, rửa sạch.",
       "Nướng gừng và hành tím đến thơm, cạo phần cháy; rang quế, hồi, thảo quả rồi cho vào túi lọc.",
       "Ninh xương với khoảng 3,5 lít nước, gừng, hành, túi gia vị và miếng nạm; hớt bọt thường xuyên. Nạm chín (khoảng 1 tiếng) thì vớt ra ngâm nước lạnh, xương ninh tiếp tổng 2,5–3 tiếng.",
       "Nêm nước dùng bằng nước mắm, muối, đường phèn cho vừa.",
       "Thăn bò thái thật mỏng để làm tái, nạm thái mỏng.",
       "Trụng bánh phở, xếp nạm, thăn bò, hành lá, rau thơm; chan nước dùng đang sôi cho bò tái chín tới. Ăn kèm chanh, ớt."],
      266, CP + "24317699",
      [("bun", "Bánh phở tươi", 800, "g", "n", "phu"),
       ("thit_bo", "Xương ống bò", 1500, "g", "x", "phu"),
       ("thit_bo", "Bò nạm", 400, "g", "n", "chinh"),
       ("thit_bo", "Thăn bò", 300, "g", "n", "chinh"),
       ("sa_ot", "Gừng", 1, "củ", "x", "gia_vi"),
       HANH(4),
       ("", "Quế, hồi, thảo quả", 1, "gói", "x", "gia_vi"),
       MAM(3),
       ("", "Đường phèn", 20, "g", "x", "gia_vi"),
       ("rau_thom", "Hành lá, ngò gai, húng quế", 1, "bó", "x", "phu"),
       ("khe_me", "Chanh", 2, "quả", "x", "gia_vi")]),

    R("bo_sot_vang", "Bò sốt vang", "mon_chinh", "nong", "nang", "vua", "thit_bo", "mua", 120, "vua",
      "Bò om rượu vang với cà rốt, sả, quế hồi đến mềm, nước sốt sánh – ăn với bánh mì hoặc bún (kiểu Bắc).",
      ["Thịt bò (bắp hoặc nạm) cắt miếng vuông 3cm, ướp với rượu vang, nước mắm, tỏi băm, sả đập dập, ngũ vị hương, đường trong 1 tiếng.",
       "Phi thơm tỏi, cho bò vào xào săn mặt ngoài.",
       "Thêm cà chua băm và tương cà, đảo đến khi ra màu đỏ.",
       "Đổ phần nước ướp và nước lọc ngập thịt, thả quế, hồi; om lửa nhỏ khoảng 1 tiếng đến khi bò mềm.",
       "Cho cà rốt vào om thêm 15 phút; nếu nước sốt loãng thì hoà ít bột năng cho sánh.",
       "Nêm lại, rắc rau mùi, ăn nóng với bánh mì."],
      50, CP + "15848383",
      [("thit_bo", "Bắp bò hoặc nạm", 800, "g", "n", "chinh"),
       ("ca_rot", "Cà rốt", 2, "củ", "n", "phu"),
       ("ca_chua", "Cà chua", 2, "quả", "x", "phu"),
       ("", "Rượu vang đỏ", 200, "ml", "x", "gia_vi"),
       ("sa_ot", "Sả", 2, "cây", "x", "gia_vi"),
       ("", "Quế, hồi", 1, "gói", "x", "gia_vi"),
       ("", "Ngũ vị hương", 1, MCF, "x", "gia_vi"),
       ("", "Tương cà", 2, MC, "x", "gia_vi"),
       TOI(4), MAM(2), DUONG(1), DAU(2),
       ("", "Bột năng", 1, MC, "x", "gia_vi")]),

    R("bo_xao_can_toi", "Bò xào cần tỏi", "mon_chinh", "am", "nhe", "vua", "thit_bo", "moi", 20, "de",
      "Thịt bò mềm xào nhanh với cần tây, tỏi tây và hành tây – món nhanh cho bữa cơm.",
      ["Bò thái mỏng ngang thớ, ướp với dầu hào, tỏi băm, tiêu, 1 thìa dầu ăn trong 15 phút.",
       "Cần tây cắt khúc 4cm, tỏi tây cắt xéo, hành tây bổ múi cau.",
       "Phi tỏi, xào bò lửa lớn đến tái thì trút ra đĩa.",
       "Xào cần tây, hành tây với ít nước mắm khoảng 1–2 phút, vẫn giữ giòn.",
       "Cho bò vào đảo nhanh, thêm tỏi tây, nêm lại rồi tắt bếp."],
      117, CP + "3040261",
      [("thit_bo", "Thịt bò thăn", 400, "g", "n", "chinh"),
       ("can_tay", "Cần tây", 300, "g", "n", "phu"),
       ("", "Tỏi tây", 2, "cây", "n", "phu"),
       ("", "Hành tây", 1, "củ", "n", "phu"),
       ("", "Dầu hào", 2, MC, "x", "gia_vi"),
       TOI(4), MAM(1), DAU(3), TIEU]),

    R("rau_muong_xao_bo", "Rau muống xào thịt bò", "mon_chinh", "am", "nhe", "vua", "rau_muong|thit_bo", "moi", 20, "de",
      "Rau muống xanh giòn xào lửa lớn cùng thịt bò mềm và tỏi.",
      ["Rau muống nhặt lấy ngọn và cọng non, rửa sạch, để ráo; trụng sơ qua nước sôi có chút muối rồi xả nước lạnh để giữ màu xanh.",
       "Bò thái mỏng, ướp dầu hào, tỏi băm, tiêu khoảng 10 phút.",
       "Phi tỏi, xào bò lửa lớn vừa tái thì trút ra.",
       "Cho rau muống vào chảo nóng, đảo nhanh với ít nước mắm và hạt nêm.",
       "Trút bò vào đảo đều 30 giây, tắt bếp."],
      27, CP + "15409009",
      [("rau_muong", "Rau muống", 600, "g", "n", "chinh"),
       ("thit_bo", "Thịt bò", 250, "g", "n", "chinh"),
       ("", "Dầu hào", 1, MC, "x", "gia_vi"),
       TOI(6), MAM(1), HAT_NEM(1), DAU(3)]),

    R("bun_bo_nam_bo", "Bún bò Nam Bộ (bún bò trộn)", "mon_chinh", "mat", "nang", "vua", "thit_bo", "nang", 40, "de",
      "Bún trộn bò xào sả, rau sống, đậu phộng, hành phi, nước mắm chua ngọt – món mát của Hà Nội.",
      ["Bò thái mỏng, ướp nước mắm, đường, tỏi, sả băm, tiêu 15 phút.",
       "Pha nước trộn: nước mắm, đường, nước lọc, chanh, tỏi ớt theo tỉ lệ 1:1:3, nếm vừa chua ngọt.",
       "Xào bò lửa thật lớn với hành tây cho nhanh chín, không ra nước.",
       "Xếp vào tô: rau sống, giá, bún, bò xào; rắc đậu phộng rang, hành phi.",
       "Chan nước trộn, ăn kèm đu đủ hoặc cà rốt ngâm chua."],
      18, CP + "15490385-bun-bo-nam-b%E1%BB%99",
      [("bun", "Bún tươi", 800, "g", "n", "phu"),
       ("thit_bo", "Thịt bò thăn", 400, "g", "n", "chinh"),
       ("rau_thom", "Xà lách, húng, kinh giới", 300, "g", "n", "phu"),
       ("", "Giá đỗ", 200, "g", "n", "phu"),
       ("dau_phong", "Đậu phộng rang", 80, "g", "n", "phu"),
       ("", "Hành tây", 1, "củ", "n", "phu"),
       ("", "Hành phi", 4, MC, "x", "gia_vi"),
       ("sa_ot", "Sả", 2, "cây", "x", "gia_vi"),
       MAM(5), DUONG(4), TOI(4),
       ("khe_me", "Chanh", 2, "quả", "x", "gia_vi")]),

    R("bo_cuon_la_lot", "Bò cuốn lá lốt", "mon_chinh", "am", "nang", "vua", "thit_bo|la_lot", "moi", 45, "vua",
      "Thịt bò băm trộn mỡ heo, cuốn lá lốt rồi áp chảo hoặc nướng – thơm lừng, ăn với bún, rau sống.",
      ["Bò và mỡ heo băm nhỏ, trộn hành tím, tỏi, sả băm, nước mắm, đường, tiêu; để 20 phút.",
       "Lá lốt rửa, lau khô, cắt bớt cuống.",
       "Đặt lá mặt bóng xuống dưới, cho một thìa thịt, cuộn chặt.",
       "Xếp cuốn vào chảo có ít dầu, mép lá úp xuống trước; áp chảo lửa vừa đến khi lá se và thịt chín (khoảng 10 phút). Có thể nướng than hoặc nồi chiên không dầu.",
       "Rắc mỡ hành, đậu phộng; ăn với bún, rau sống, nước mắm chua ngọt."],
      None, CP + "25495015",
      [("thit_bo", "Thịt bò", 400, "g", "n", "chinh"),
       ("thit_heo", "Mỡ heo", 80, "g", "n", "phu"),
       ("la_lot", "Lá lốt", 40, "lá", "n", "chinh"),
       ("bun", "Bún tươi", 500, "g", "n", "phu"),
       ("rau_thom", "Rau sống", 200, "g", "n", "phu"),
       ("dau_phong", "Đậu phộng rang", 50, "g", "x", "phu"),
       ("sa_ot", "Sả", 2, "cây", "x", "gia_vi"),
       HANH(3), TOI(3), MAM(2), DUONG(1), DAU(2), TIEU]),

    R("khoai_tay_xao_bo", "Khoai tây xào thịt bò", "mon_chinh", "am", "nang", "vua", "khoai_tay|thit_bo", "moi", 30, "de",
      "Khoai tây Đà Lạt chiên sơ cho bùi, xào cùng thịt bò, hành tây, cà chua.",
      ["Khoai tây gọt vỏ, thái thanh dày, ngâm nước muối loãng 10 phút, vớt ra để ráo.",
       "Bò thái mỏng, ướp dầu hào, tỏi, tiêu 15 phút.",
       "Chiên khoai trong ít dầu đến vàng nhạt, gắp ra.",
       "Xào bò lửa lớn vừa tái, trút ra.",
       "Xào hành tây, cà chua cho mềm, cho khoai và bò vào đảo đều, nêm nước mắm, rắc hành lá, tiêu."],
      675, CP + "4495704-khoai-tay-xao-th%E1%BB%8Bt-bo",
      [("khoai_tay", "Khoai tây", 600, "g", "n", "chinh"),
       ("thit_bo", "Thịt bò", 300, "g", "n", "chinh"),
       ("", "Hành tây", 1, "củ", "n", "phu"),
       ("ca_chua", "Cà chua", 1, "quả", "n", "phu"),
       ("", "Dầu hào", 1, MC, "x", "gia_vi"),
       TOI(4), MAM(1), DAU(5), HANH_LA, TIEU]),

    R("sup_lo_trang_xao_bo", "Súp lơ trắng xào thịt bò", "mon_chinh", "am", "nhe", "vua", "sup_lo_trang|thit_bo", "moi", 25, "de",
      "Súp lơ trắng trụng giòn, xào nhanh cùng bò và cà rốt.",
      ["Súp lơ cắt bông nhỏ, ngâm nước muối 10 phút, trụng sôi 1 phút rồi xả nước lạnh.",
       "Bò thái mỏng, ướp dầu hào, tỏi, tiêu.",
       "Xào bò lửa lớn vừa tái, trút ra.",
       "Xào súp lơ và cà rốt thái lát với ít nước khoảng 2 phút, nêm nước mắm, hạt nêm.",
       "Cho bò vào đảo đều, hoà chút bột năng cho sốt sánh nhẹ."],
      26, CP + "25269890",
      [("sup_lo_trang", "Súp lơ trắng", 500, "g", "n", "chinh"),
       ("thit_bo", "Thịt bò", 250, "g", "n", "chinh"),
       ("ca_rot", "Cà rốt", 1, "củ", "n", "phu"),
       ("", "Dầu hào", 1, MC, "x", "gia_vi"),
       ("", "Bột năng", 1, MCF, "x", "gia_vi"),
       TOI(4), MAM(1), HAT_NEM(1), DAU(3)]),

    R("su_hao_xao_bo", "Su hào xào thịt bò", "mon_chinh", "am", "nhe", "vua", "su_hao|thit_bo", "moi", 25, "de",
      "Su hào thái sợi giòn ngọt xào thịt bò – món quen của mâm cơm miền Bắc.",
      ["Su hào gọt vỏ, thái sợi hoặc thanh mỏng; cà rốt thái sợi.",
       "Bò thái mỏng, ướp nước mắm, tỏi, tiêu, chút dầu.",
       "Xào bò lửa lớn vừa tái, trút ra.",
       "Phi tỏi, xào su hào và cà rốt, thêm 3–4 thìa nước, đảo đến khi su hào hơi trong nhưng còn giòn.",
       "Cho bò vào, nêm dầu hào, nước mắm, rắc rau mùi."],
      20, CP + "16795923",
      [("su_hao", "Su hào", 2, "củ", "n", "chinh"),
       ("thit_bo", "Thịt bò", 250, "g", "n", "chinh"),
       ("ca_rot", "Cà rốt", 1, "củ", "n", "phu"),
       ("", "Dầu hào", 1, MC, "x", "gia_vi"),
       ("rau_thom", "Rau mùi", 1, "nhánh", "x", "phu"),
       TOI(4), MAM(1), DAU(3), TIEU]),

    # ---------- Rau muống, rau lá ----------
    R("rau_muong_luoc", "Rau muống luộc chấm nước luộc chua", "canh", "mat", "nhe", "it", "rau_muong", "nang", 15, "de",
      "Rau muống luộc xanh giòn; nước luộc vắt chanh hoặc dầm me thay sấu thành bát canh chua mát (kiểu Bắc).",
      ["Rau muống nhặt bỏ lá già, cọng già; rửa sạch.",
       "Đun sôi khoảng 2 lít nước với 1 thìa muối, cho rau vào, đảo đều, luộc 2–3 phút đến khi cọng vừa chín.",
       "Vớt rau ra đĩa (có thể xả qua nước lạnh cho giòn).",
       "Múc nước luộc ra bát, dầm me chín hoặc vắt chanh, nêm chút muối, hạt nêm thành canh chua.",
       "Chấm rau với nước mắm tỏi ớt hoặc tương bần, ăn kèm trứng luộc dầm vào nước mắm."],
      48, CP + "17059070",
      [("rau_muong", "Rau muống", 700, "g", "n", "chinh"),
       ("trung", "Trứng gà", 2, "quả", "n", "phu"),
       ("khe_me", "Me chín hoặc chanh", 2, "quả", "x", "gia_vi"),
       MAM(3), TOI(2), ("sa_ot", "Ớt", 1, "quả", "x", "gia_vi"),
       ("", "Muối", 1, MC, "x", "gia_vi")]),

    R("rau_muong_xao_toi", "Rau muống xào tỏi", "mon_chinh", "am", "nhe", "vua", "rau_muong", "moi", 15, "de",
      "Rau muống xào lửa thật lớn với nhiều tỏi – xanh, giòn, thơm.",
      ["Nhặt rau lấy phần ngọn và cọng non bẻ gãy giòn, rửa sạch, để thật ráo.",
       "Đập dập và băm tỏi.",
       "Đun chảo thật nóng với dầu, phi một nửa lượng tỏi đến vàng thơm.",
       "Cho rau vào đảo nhanh tay trên lửa lớn, nêm nước mắm và hạt nêm.",
       "Khi rau vừa chín tái, cho nốt tỏi sống vào đảo vài giây rồi tắt bếp, bày ra đĩa ngay."],
      None, CP + "14845984-rau-mu%E1%BB%91ng-xao-t%E1%BB%8Fi",
      [("rau_muong", "Rau muống", 700, "g", "n", "chinh"),
       TOI(8), MAM(1), HAT_NEM(1), DAU(3)]),

    R("nom_rau_muong_tai_heo", "Nộm rau muống tai heo", "goi", "mat", "nhe", "it", "rau_muong", "nang", 40, "vua",
      "Cọng rau muống chẻ trụng giòn, tai heo luộc thái mỏng, trộn chua ngọt với lạc rang, rau thơm.",
      ["Tai heo cạo sạch, chà muối, luộc với gừng khoảng 20 phút; vớt ra ngâm nước đá rồi thái mỏng.",
       "Cọng rau muống chẻ nhỏ, trụng nhanh qua nước sôi rồi ngâm nước đá cho giòn, vắt ráo.",
       "Pha nước trộn: nước mắm, đường, nước cốt chanh, tỏi ớt băm.",
       "Trộn rau muống, tai heo, cà rốt sợi với nước trộn, để 5 phút cho thấm.",
       "Thêm rau kinh giới, húng, rắc đậu phộng rang giã dập."],
      3, CP + "11239372",
      [("rau_muong", "Rau muống (lấy cọng)", 500, "g", "n", "chinh"),
       ("thit_heo", "Tai heo", 300, "g", "n", "chinh"),
       ("ca_rot", "Cà rốt", 1, "củ", "n", "phu"),
       ("rau_thom", "Kinh giới, húng láng", 1, "bó", "x", "phu"),
       ("dau_phong", "Đậu phộng rang", 60, "g", "x", "phu"),
       ("sa_ot", "Gừng", 1, "nhánh", "x", "gia_vi"),
       MAM(3), DUONG(2), TOI(3),
       ("khe_me", "Chanh", 2, "quả", "x", "gia_vi")]),

    R("canh_cua_rau_day", "Canh cua rau đay mồng tơi", "canh", "mat", "nhe", "it", "cua_dong|rau_day|mong_toi", "nang", 45, "vua",
      "Riêu cua đồng nổi gạch, nấu rau đay, mồng tơi, mướp – bát canh giải nhiệt kinh điển của miền Bắc. Ăn kèm cà pháo.",
      ["Cua đồng (hoặc cua xay sẵn) lọc với khoảng 1,5 lít nước và chút muối, bỏ bã, lấy nước cua.",
       "Đun nước cua lửa vừa, khuấy nhẹ một chiều đến khi gần sôi để riêu cua đóng thành mảng; vặn nhỏ lửa.",
       "Rau đay, mồng tơi thái nhỏ; mướp gọt vỏ, cắt miếng.",
       "Cho mướp vào trước, sau đó rau đay, mồng tơi; nấu thêm 2–3 phút đến khi rau chín.",
       "Nêm muối, hạt nêm; không khuấy mạnh để giữ riêu."],
      39, CP + "9554958",
      [("cua_dong", "Cua đồng xay", 400, "g", "n", "chinh"),
       ("rau_day", "Rau đay", 200, "g", "n", "chinh"),
       ("mong_toi", "Mồng tơi", 200, "g", "n", "chinh"),
       ("muop", "Mướp hương", 1, "quả", "n", "phu"),
       ("", "Muối", 1, MCF, "x", "gia_vi"),
       HAT_NEM(1)]),

    R("canh_rau_ngot_thit_bam", "Canh rau ngót thịt băm", "canh", "mat", "nhe", "it", "rau_ngot", "nang", 20, "de",
      "Rau ngót vò dập nấu thịt băm – canh nhanh, ngọt nước, mát.",
      ["Rau ngót tuốt lá, rửa sạch, vò nhẹ cho dập để nhanh chín và ngọt nước.",
       "Thịt băm ướp chút nước mắm, hành tím băm.",
       "Phi hành, xào thịt băm cho săn, đổ khoảng 1,2 lít nước, đun sôi, hớt bọt.",
       "Cho rau ngót vào, nấu 3–4 phút đến khi rau chín mềm.",
       "Nêm nước mắm, hạt nêm vừa ăn."],
      24, CP + "251767",
      [("rau_ngot", "Rau ngót", 300, "g", "n", "chinh"),
       ("thit_heo", "Thịt heo xay", 150, "g", "n", "phu"),
       HANH(2), MAM(1), HAT_NEM(1), DAU(1)]),

    R("canh_muop_mong_toi", "Canh mướp mồng tơi nấu tôm", "canh", "mat", "nhe", "it", "muop|mong_toi", "nang", 20, "de",
      "Mướp hương ngọt, mồng tơi mát, tôm xào thơm – canh giải nhiệt mùa hè.",
      ["Tôm bóc vỏ, bỏ chỉ đen, băm sơ hoặc để nguyên con, ướp chút hạt nêm.",
       "Mướp gọt vỏ, cắt miếng vừa ăn; mồng tơi nhặt lá non, rửa sạch.",
       "Phi hành, xào tôm cho đỏ, đổ khoảng 1,2 lít nước, đun sôi.",
       "Cho mướp vào nấu 2 phút, tiếp mồng tơi nấu thêm 2 phút.",
       "Nêm nước mắm, hạt nêm, rắc tiêu."],
      18, CP + "15223211",
      [("muop", "Mướp hương", 2, "quả", "n", "chinh"),
       ("mong_toi", "Mồng tơi", 250, "g", "n", "chinh"),
       ("tom_the", "Tôm tươi", 150, "g", "n", "phu"),
       HANH(2), MAM(1), HAT_NEM(1), DAU(1), TIEU]),

    # ---------- Ếch ----------
    R("ech_om_chuoi_dau", "Ếch om chuối đậu", "mon_chinh", "nong", "nang", "vua", "ech|chuoi_xanh", "mua", 75, "vua",
      "Ếch om với chuối xanh, đậu phụ rán, mẻ, nghệ, tía tô, lá lốt, nhiều nước – ăn với bún thay cơm (kiểu Bắc), nấu một nồi ăn cả ngày.",
      ["Ếch làm sạch, chặt miếng; ướp với mẻ, mắm tôm, nghệ, riềng, nước mắm trong 30 phút.",
       "Chuối xanh gọt vỏ, cắt khúc, ngâm nước có chút muối và giấm cho khỏi thâm.",
       "Đậu phụ cắt miếng, rán vàng; thịt ba chỉ thái miếng, xào cho ra bớt mỡ.",
       "Cho ếch vào xào cùng ba chỉ đến săn; thêm chuối, đổ nước xâm xấp, om lửa nhỏ 20 phút.",
       "Cho đậu phụ vào om thêm 10 phút, nêm lại; tắt bếp thì thả tía tô, lá lốt thái nhỏ. Để nhiều nước, chan ăn với bún."],
      None, CP + "10331747",
      [("ech", "Ếch", 600, "g", "n", "chinh"),
       ("chuoi_xanh", "Chuối xanh", 5, "quả", "n", "chinh"),
       ("dau_phu", "Đậu phụ", 3, "bìa", "n", "phu"),
       ("thit_heo", "Thịt ba rọi", 150, "g", "n", "phu"),
       ("rau_thom", "Tía tô, lá lốt", 1, "bó", "x", "phu"),
       ("bun", "Bún tươi (ăn kèm)", 800, "g", "n", "phu"),
       ("", "Mẻ", 3, MC, "x", "gia_vi"),
       ("", "Mắm tôm", 1, MC, "x", "gia_vi"),
       ("", "Nghệ tươi", 1, "nhánh", "x", "gia_vi"),
       ("", "Riềng", 1, "nhánh", "x", "gia_vi"),
       MAM(1), DAU(3)]),

    R("ech_xao_sa_ot", "Ếch xào sả ớt", "mon_chinh", "nong", "nhe", "vua", "ech", "mua", 40, "de",
      "Ếch xào sả ớt cay thơm, thịt chắc ngọt – rất đưa cơm.",
      ["Ếch làm sạch, chặt miếng vừa ăn, ướp nước mắm, hạt nêm, đường, tiêu và một nửa sả băm trong 20 phút.",
       "Phi thơm tỏi, phần sả băm còn lại và ớt.",
       "Cho ếch vào đảo lửa lớn đến khi săn và chín (khoảng 8–10 phút); nếu khô thêm vài thìa nước.",
       "Nêm lại vừa ăn, cho hành lá, rau răm vào đảo vài giây rồi tắt bếp."],
      26, CP + "11872707",
      [("ech", "Ếch", 600, "g", "n", "chinh"),
       ("sa_ot", "Sả", 4, "cây", "x", "gia_vi"),
       ("sa_ot", "Ớt", 2, "quả", "x", "gia_vi"),
       ("rau_thom", "Rau răm, hành lá", 1, "bó", "x", "phu"),
       TOI(4), MAM(2), DUONG(1), DAU(3), TIEU]),

    R("ech_chien_gion", "Ếch chiên giòn", "an_vat", "am", "nang", "nhieu", "ech", "moi", 40, "de",
      "Đùi ếch tẩm bột chiên giòn, chấm tương ớt hoặc muối tiêu chanh.",
      ["Ếch làm sạch, chặt miếng (hoặc lấy đùi), ướp tỏi băm, hạt nêm, đường, tiêu 20 phút.",
       "Lăn ếch qua bột chiên giòn trộn chút bột bắp cho lớp vỏ xốp.",
       "Chiên ngập dầu lửa vừa đến khi vàng đều (6–8 phút), vớt ra giấy thấm dầu.",
       "Ăn nóng với tương ớt hoặc muối tiêu chanh, kèm rau sống."],
      44, CP + "875414",
      [("ech", "Ếch", 600, "g", "n", "chinh"),
       ("", "Bột chiên giòn", 150, "g", "n", "phu"),
       ("", "Bột bắp", 2, MC, "x", "gia_vi"),
       TOI(4), HAT_NEM(1), DUONG(1), TIEU,
       ("", "Dầu ăn (chiên ngập)", 500, "ml", "x", "gia_vi")]),

    R("chao_ech", "Cháo ếch", "mon_chinh", "nong", "nhe", "vua", "ech", "mua", 60, "vua",
      "Cháo trắng nấu nhừ ăn kèm ếch kho gừng hành sánh đậm – ấm bụng ngày mưa.",
      ["Gạo vo sạch, rang sơ, nấu với khoảng 1,8 lít nước và lá dứa đến khi hạt nở bung, cháo mịn (khoảng 40 phút).",
       "Ếch chặt miếng, ướp nước tương, dầu hào, nước mắm, đường, gừng, tỏi, hành băm 20 phút.",
       "Phi thơm gừng, tỏi, ớt; cho ếch vào xào săn, thêm ít nước, kho lửa nhỏ đến khi sốt sánh lại.",
       "Múc cháo ra bát, rắc hành lá, tiêu; ăn kèm ếch kho và quẩy."],
      None, CP + "23851069",
      [("ech", "Ếch", 600, "g", "n", "chinh"),
       ("", "Gạo tẻ", 200, "g", "n", "phu"),
       ("", "Lá dứa", 3, "lá", "x", "gia_vi"),
       ("sa_ot", "Gừng", 1, "củ", "x", "gia_vi"),
       ("", "Nước tương", 2, MC, "x", "gia_vi"),
       ("", "Dầu hào", 1, MC, "x", "gia_vi"),
       TOI(4), HANH(2), MAM(1), DUONG(1), DAU(2), HANH_LA, TIEU]),

    # ---------- Món Bắc khác ----------
    R("bun_cha_ha_noi", "Bún chả Hà Nội", "mon_chinh", "am", "nang", "vua", "thit_heo", "moi", 90, "vua",
      "Chả miếng ba chỉ và chả viên nướng than, ngâm nước chấm chua ngọt có đu đủ xanh, ăn với bún, rau sống.",
      ["Ba chỉ thái miếng mỏng; nạc vai xay. Ướp riêng mỗi loại với nước mắm, đường, dầu hào, hành tím, tỏi băm, tiêu và chút nước hàng (hoặc mật ong) trong 1 tiếng.",
       "Nặn thịt xay thành viên dẹt.",
       "Nướng than hoa (hoặc lò/nồi chiên không dầu 200°C) đến khi xém cạnh, thơm.",
       "Pha nước chấm: nước lọc, nước mắm, đường, giấm, chanh theo khẩu vị; đun ấm, để nguội, thả đu đủ xanh và cà rốt thái lát ngâm sẵn, tỏi ớt.",
       "Thả chả vào bát nước chấm, ăn cùng bún và rau sống."],
      None, CP + "12757369-bun-ch%E1%BA%A3-ha-n%E1%BB%99i",
      [("thit_heo", "Thịt ba rọi", 400, "g", "n", "chinh"),
       ("thit_heo", "Thịt nạc vai xay", 400, "g", "n", "chinh"),
       ("bun", "Bún tươi", 800, "g", "n", "phu"),
       ("rau_thom", "Xà lách, tía tô, kinh giới", 300, "g", "n", "phu"),
       ("", "Đu đủ xanh", 150, "g", "x", "phu"),
       ("ca_rot", "Cà rốt", 1, "củ", "x", "phu"),
       ("", "Dầu hào", 2, MC, "x", "gia_vi"),
       ("", "Mật ong hoặc nước hàng", 1, MC, "x", "gia_vi"),
       ("", "Giấm", 3, MC, "x", "gia_vi"),
       HANH(4), TOI(6), MAM(7), DUONG(6), TIEU]),

    R("dau_phu_sot_ca_chua", "Đậu phụ sốt cà chua", "mon_chinh", "am", "nhe", "vua", "dau_phu", "moi", 25, "de",
      "Đậu phụ rán vàng rim trong sốt cà chua hành lá – món rẻ, dễ, rất đưa cơm.",
      ["Đậu phụ cắt miếng vừa ăn, để ráo, rán vàng các mặt.",
       "Cà chua bỏ hạt, băm nhỏ.",
       "Phi hành tím, cho cà chua vào xào nát, thêm chút nước, nêm nước mắm, đường cho vừa chua ngọt.",
       "Cho đậu vào rim lửa nhỏ 5–7 phút cho thấm sốt.",
       "Rắc hành lá, tiêu, tắt bếp."],
      13, CP + "827516",
      [("dau_phu", "Đậu phụ", 4, "bìa", "n", "chinh"),
       ("ca_chua", "Cà chua", 4, "quả", "n", "phu"),
       HANH(2), MAM(2), DUONG(1), HANH_LA, TIEU,
       ("", "Dầu ăn (rán đậu)", 6, MC, "x", "gia_vi")]),

    R("canh_trung_ca_chua", "Canh trứng cà chua", "canh", "am", "nhe", "it", "trung|ca_chua", "moi", 15, "de",
      "Nhiều cà chua xào kỹ cho nước canh đỏ, chua ngọt; trứng đập vào để nguyên rồi mới khuấy nên thành từng mảng mềm.",
      ["Tỏi, hành tím băm nhỏ; hành lá thái nhỏ; ớt thái riêng cho người lớn.",
       "Cà chua rửa sạch, thái hạt lựu. Đập trứng ra tô, chỉ chọc vỡ lòng đỏ, không đánh tan.",
       "Phi tỏi, hành tím đến vàng thơm, cho cà chua vào xào đến khi mềm nhừ, ra màu đỏ.",
       "Đổ khoảng 1,2 lít nước, đun sôi rồi nêm nước mắm, hạt nêm, đường cho vừa.",
       "Đổ trứng vào nồi, để yên đến khi nước sôi lại thì mới khuấy nhẹ cho trứng thành mảng.",
       "Thả hành lá, rắc tiêu, tắt bếp."],
      None, CP + "13218421",
      [("trung", "Trứng gà hoặc trứng vịt", 4, "quả", "n", "chinh"),
       ("ca_chua", "Cà chua", 8, "quả", "n", "chinh"),
       TOI(3), HANH(1), MAM(1), HAT_NEM(2), DUONG(1), DAU(1), TIEU, HANH_LA,
       ("sa_ot", "Ớt (phần người lớn)", 1, "quả", "x", "gia_vi")]),

    R("trung_duc_thit", "Trứng đúc thịt", "mon_chinh", "am", "nhe", "vua", "trung", "moi", 25, "de",
      "Trứng đánh cùng thịt băm, mộc nhĩ, hành lá rồi rán thành bánh dày.",
      ["Mộc nhĩ ngâm nở, thái nhỏ; hành lá thái nhỏ.",
       "Đánh tan trứng, trộn thịt băm, mộc nhĩ, hành lá, nước mắm, tiêu.",
       "Đun chảo với dầu, đổ hỗn hợp vào dàn đều, để lửa vừa nhỏ.",
       "Khi mặt dưới vàng và mặt trên se lại thì lật (dùng đĩa úp lên cho dễ), rán tiếp đến khi thịt chín.",
       "Cắt miếng, chấm nước mắm ớt."],
      36, CP + "25062394",
      [("trung", "Trứng gà", 6, "quả", "n", "chinh"),
       ("thit_heo", "Thịt heo xay", 200, "g", "n", "phu"),
       ("nam", "Mộc nhĩ", 10, "g", "x", "phu"),
       HANH_LA, MAM(1), DAU(3), TIEU]),

    R("nem_ran_ha_noi", "Nem rán Hà Nội", "an_vat", "nong", "nang", "nhieu", "thit_heo", "mua", 90, "vua",
      "Nem cuốn bánh đa nem nhân thịt, miến, mộc nhĩ, trứng, rán giòn – món cỗ, ngày Tết của người Bắc.",
      ["Miến ngâm mềm cắt ngắn; mộc nhĩ, nấm hương ngâm nở thái nhỏ; cà rốt, su hào bào sợi, vắt bớt nước.",
       "Trộn thịt xay, tôm băm, rau củ, miến, mộc nhĩ, trứng, hành lá, nước mắm, tiêu cho thật đều.",
       "Làm ẩm bánh đa nem bằng nước pha chút giấm, đặt nhân, gấp hai mép, cuộn chặt vừa tay.",
       "Rán ngập dầu lửa nhỏ đến khi vàng giòn (khoảng 10 phút), vớt ra giấy thấm dầu.",
       "Chấm nước mắm chua ngọt có đu đủ, cà rốt; ăn với bún, rau sống."],
      478, CP + "24109052-nem-ran-ha-n%E1%BB%99i",
      [("thit_heo", "Thịt nạc vai xay", 400, "g", "n", "chinh"),
       ("tom_the", "Tôm", 150, "g", "n", "phu"),
       ("trung", "Trứng gà", 2, "quả", "n", "phu"),
       ("", "Miến dong", 50, "g", "n", "phu"),
       ("nam", "Mộc nhĩ, nấm hương", 20, "g", "x", "phu"),
       ("ca_rot", "Cà rốt", 1, "củ", "n", "phu"),
       ("su_hao", "Su hào", 1, "củ", "n", "phu"),
       ("", "Bánh đa nem", 30, "cái", "n", "phu"),
       MAM(5), DUONG(3), ("", "Giấm", 3, MC, "x", "gia_vi"), TIEU,
       ("", "Dầu ăn (rán ngập)", 700, "ml", "x", "gia_vi")]),

    R("ga_luoc_la_chanh", "Gà luộc lá chanh", "mon_chinh", "am", "nhe", "it", "ga_ta", "moi", 60, "de",
      "Gà ta luộc da vàng giòn, rắc lá chanh thái chỉ, chấm muối tiêu chanh – món mâm cơm Bắc.",
      ["Gà ta làm sạch, xát muối và gừng đập để khử mùi, rửa lại.",
       "Cho gà vào nồi nước lạnh ngập, thêm gừng, hành tím nướng; đun sôi rồi hạ lửa nhỏ, luộc 20–25 phút.",
       "Tắt bếp, đậy nắp ngâm thêm 10 phút; xiên vào đùi không ra nước hồng là chín.",
       "Vớt gà ngâm ngay vào nước đá 5 phút cho da giòn; quét chút nghệ hoặc mỡ gà nếu muốn da vàng đẹp.",
       "Chặt miếng, rắc lá chanh thái chỉ, chấm muối tiêu chanh. Nước luộc dùng nấu canh hoặc cháo."],
      30, CP + "251987-ga-lu%E1%BB%99c-la-chanh",
      [("ga_ta", "Gà ta", 1500, "g", "n", "chinh"),
       ("", "Lá chanh", 10, "lá", "x", "phu"),
       ("sa_ot", "Gừng", 1, "củ", "x", "gia_vi"),
       HANH(3),
       ("", "Muối tiêu chanh", None, "vừa đủ", "x", "gia_vi")]),

    R("canh_khoai_so_suon", "Canh khoai sọ nấu sườn", "canh", "nong", "nang", "vua", "khoai_mon", "mua", 60, "de",
      "Sườn non hầm ngọt nước, khoai sọ bở dẻo, thả rau mùi tàu – canh ấm ngày mưa (kiểu Bắc).",
      ["Sườn chặt miếng, chần sôi 3 phút, rửa sạch.",
       "Đun sôi khoảng 1,5 lít nước, cho sườn và hành tím đập vào, hầm lửa nhỏ 30 phút, hớt bọt.",
       "Khoai sọ đeo găng gọt vỏ (tránh ngứa), rửa với muối, cắt miếng vừa ăn.",
       "Cho khoai vào nấu 15–20 phút đến khi bở mềm; có thể dầm vài miếng cho nước canh sánh.",
       "Nêm nước mắm, hạt nêm, thả hành lá, rau mùi tàu thái nhỏ."],
      82, CP + "17126635-canh-khoai-s%E1%BB%8D-n%E1%BA%A5u-s%C6%B0%E1%BB%9Dn-heo",
      [("khoai_mon", "Khoai sọ", 500, "g", "n", "chinh"),
       ("thit_heo", "Sườn non", 400, "g", "n", "chinh"),
       ("rau_thom", "Hành lá, mùi tàu", 1, "bó", "x", "phu"),
       HANH(2), MAM(1), HAT_NEM(1)]),

    R("canh_cu_cai_xuong", "Canh củ cải nấu xương", "canh", "nong", "nhe", "it", "cu_cai", "mua", 75, "de",
      "Xương heo hầm với củ cải trắng và cà rốt – nước trong, ngọt thanh.",
      ["Xương heo chần sôi, rửa sạch.",
       "Hầm xương với khoảng 2 lít nước và hành tím đập trong 45 phút, hớt bọt.",
       "Củ cải gọt vỏ, cắt khúc; cà rốt cắt khoanh.",
       "Cho củ cải, cà rốt vào nấu 15 phút đến khi củ cải trong và mềm.",
       "Nêm muối, nước mắm, hạt nêm; rắc hành ngò, tiêu."],
      71, CP + "25251535",
      [("cu_cai", "Củ cải trắng", 600, "g", "n", "chinh"),
       ("thit_heo", "Xương heo", 500, "g", "n", "phu"),
       ("ca_rot", "Cà rốt", 1, "củ", "n", "phu"),
       ("rau_thom", "Hành ngò", 1, "bó", "x", "phu"),
       HANH(2), MAM(1), HAT_NEM(1), TIEU]),

    R("thit_kho_cu_cai", "Thịt kho củ cải", "mon_chinh", "am", "nang", "vua", "cu_cai", "mua", 50, "de",
      "Ba chỉ kho với củ cải trắng thấm nước kho ngọt mặn, ăn với cơm nóng.",
      ["Ba chỉ cắt miếng, chần sơ, ướp nước mắm, đường, hành tỏi băm, tiêu 20 phút.",
       "Thắng chút đường làm nước màu, cho thịt vào đảo săn.",
       "Đổ nước xâm xấp, kho lửa nhỏ 20 phút.",
       "Củ cải gọt vỏ, cắt miếng dày, cho vào kho thêm 15 phút đến khi trong và thấm.",
       "Nêm lại, rắc hành lá, tiêu."],
      None, CP + "16899696",
      [("thit_heo", "Thịt ba rọi", 400, "g", "n", "chinh"),
       ("cu_cai", "Củ cải trắng", 500, "g", "n", "chinh"),
       HANH(2), TOI(3), MAM(3), DUONG(2), HANH_LA, TIEU]),

    R("dua_gop_su_hao", "Dưa góp su hào cà rốt củ cải", "goi", "mat", "nhe", "it", "su_hao|cu_cai", "nang", 30, "de",
      "Su hào, cà rốt, củ cải thái lát bóp muối, ngâm giấm đường – ăn kèm thịt kho, món chiên cho đỡ ngán.",
      ["Su hào, củ cải, cà rốt gọt vỏ, thái lát mỏng hoặc thái sợi.",
       "Bóp rau củ với 1 thìa muối, để 20 phút cho ra nước, rửa lại, vắt thật khô.",
       "Đun giấm, đường, nước lọc đến khi đường tan, để nguội.",
       "Trộn rau củ với tỏi, ớt thái lát, đổ nước giấm đường, trộn đều.",
       "Để ngăn mát ít nhất 1 tiếng; ăn được trong 3–4 ngày."],
      None, CP + "16015119",
      [("su_hao", "Su hào", 1, "củ", "n", "chinh"),
       ("cu_cai", "Củ cải trắng", 300, "g", "n", "chinh"),
       ("ca_rot", "Cà rốt", 2, "củ", "n", "phu"),
       ("", "Giấm", 100, "ml", "x", "gia_vi"),
       DUONG(4), ("", "Muối", 1, MC, "x", "gia_vi"), TOI(3),
       ("sa_ot", "Ớt", 1, "quả", "x", "gia_vi")]),

    # ---------- Ngô, khoai ----------
    R("ngo_nuong_mo_hanh", "Ngô nướng mỡ hành", "an_vat", "am", "nhe", "vua", "ngo", "mua", 30, "de",
      "Bắp nếp nướng than, phết mỡ hành – món ăn vặt chiều mưa.",
      ["Bắp lột vỏ, chừa vài lớp vỏ non nếu muốn giữ ẩm, rửa sạch; có thể luộc sơ 10 phút cho nhanh chín.",
       "Làm mỡ hành: phi dầu nóng rồi rưới vào hành lá thái nhỏ, thêm chút muối, đường.",
       "Nướng bắp trên than hoặc trong lò 200°C, trở đều đến khi hạt vàng xém (15–20 phút).",
       "Phết mỡ hành lên bắp, nướng thêm 1–2 phút cho thơm. Ăn nóng."],
      45, CP + "6050015",
      [("ngo", "Bắp nếp", 4, "trái", "n", "chinh"),
       ("", "Hành lá", 1, "bó", "x", "phu"),
       DAU(4), ("", "Muối, đường", None, "vừa đủ", "x", "gia_vi")]),

    R("che_bap", "Chè bắp nước cốt dừa", "trang_mieng", "am", "nhe", "it", "ngo", "moi", 45, "de",
      "Chè bắp nếp dẻo, bột năng sánh, rưới nước cốt dừa – ăn nóng ngày mưa hoặc ăn lạnh ngày nắng.",
      ["Bắp nếp tách hạt (dùng dao lạng sát lõi), lõi bắp đem nấu với khoảng 1,2 lít nước 15 phút cho ngọt rồi vớt bỏ.",
       "Cho hạt bắp vào nồi nước lõi bắp, nấu 10 phút đến khi chín mềm.",
       "Thêm đường, lá dứa; hoà bột năng với ít nước, đổ từ từ vào, khuấy đến khi chè sánh trong.",
       "Nấu nước cốt dừa với chút muối, đường và ít bột năng cho sánh.",
       "Múc chè ra chén, rưới nước cốt dừa, rắc mè rang."],
      96, CP + "15125923",
      [("ngo", "Bắp nếp", 3, "trái", "n", "chinh"),
       ("", "Nước cốt dừa", 200, "ml", "n", "phu"),
       ("", "Bột năng", 3, MC, "x", "gia_vi"),
       ("", "Lá dứa", 3, "lá", "x", "gia_vi"),
       ("", "Đường", 120, "g", "x", "gia_vi"),
       ("", "Mè rang", 1, MC, "x", "gia_vi")]),

    R("khoai_lang_chien", "Khoai lang chiên giòn", "an_vat", "am", "nhe", "nhieu", "khoai_lang", "mua", 30, "de",
      "Khoai lang thái que tẩm bột chiên giòn – món ăn vặt chiều mưa.",
      ["Khoai lang gọt vỏ, thái que dài, ngâm nước muối loãng 15 phút rồi để thật ráo.",
       "Trộn bột chiên giòn, bột năng, chút đường, muối với nước lạnh thành bột hơi sệt.",
       "Nhúng khoai vào bột (hoặc lăn bột khô cho vỏ mỏng hơn).",
       "Chiên ngập dầu lửa vừa đến khi vàng giòn, vớt ra giấy thấm dầu. Ăn nóng."],
      155, CP + "563082",
      [("khoai_lang", "Khoai lang", 600, "g", "n", "chinh"),
       ("", "Bột chiên giòn", 100, "g", "n", "phu"),
       ("", "Bột năng", 2, MC, "x", "gia_vi"),
       DUONG(1), ("", "Dầu ăn (chiên ngập)", 500, "ml", "x", "gia_vi")]),

    # ---------- Trứng ----------
    R("trung_ran_hanh", "Trứng rán hành lá", "mon_chinh", "am", "nhe", "vua", "trung", "moi", 10, "de",
      "Trứng đánh với hành lá, nước mắm, rán mỏng vàng thơm – món cứu nguy 10 phút.",
      ["Đập trứng ra bát, thêm nước mắm, tiêu, đánh tan.",
       "Cho hành lá thái nhỏ vào trứng.",
       "Đun nóng chảo với dầu, phi sơ phần đầu hành cho thơm.",
       "Đổ trứng, lắc chảo cho dàn đều, rán lửa vừa đến khi mặt dưới vàng thì lật, rán thêm 1 phút.",
       "Cắt miếng, ăn với cơm nóng, dưa chuột."],
      1108, CP + "12483186",
      [("trung", "Trứng gà hoặc vịt", 6, "quả", "n", "chinh"),
       ("", "Hành lá", 1, "bó", "n", "phu"),
       MAM(1), DAU(3), TIEU]),

    R("thit_kho_trung", "Thịt kho trứng", "mon_chinh", "am", "nang", "vua", "trung|thit_heo", "mua", 90, "de",
      "Ba chỉ kho nước dừa với trứng luộc, nước kho màu cánh gián – nồi kho để được vài bữa.",
      ["Ba chỉ cắt miếng to, chần sơ, ướp nước mắm, đường, hành tỏi băm, tiêu 30 phút.",
       "Trứng luộc chín, bóc vỏ.",
       "Thắng đường làm nước màu, cho thịt vào đảo săn cho ngấm màu.",
       "Đổ nước dừa xâm xấp, kho lửa nhỏ 40 phút, hớt bọt.",
       "Cho trứng vào kho thêm 20 phút đến khi thịt mềm, trứng thấm màu; nêm lại vừa ăn."],
      301, CP + "1069610-th%E1%BB%8Bt-kho-tr%E1%BB%A9ng-th%E1%BB%8Bt-kho-tau",
      [("thit_heo", "Thịt ba rọi", 600, "g", "n", "chinh"),
       ("trung", "Trứng vịt hoặc gà", 6, "quả", "n", "chinh"),
       ("", "Nước dừa tươi", 500, "ml", "x", "phu"),
       HANH(3), TOI(4), MAM(4), DUONG(2), TIEU]),

    R("trung_hap_van", "Trứng hấp vân", "mon_chinh", "am", "nhe", "it", "trung", "mua", 40, "de",
      "Trứng đánh với thịt băm, mộc nhĩ, miến rồi hấp cách thuỷ; phết lòng đỏ tạo vân vàng.",
      ["Mộc nhĩ ngâm nở thái nhỏ; miến ngâm mềm cắt ngắn.",
       "Tách riêng 1 lòng đỏ để phết mặt; phần trứng còn lại đánh tan.",
       "Trộn trứng với thịt băm, mộc nhĩ, miến, hành lá, nước mắm, tiêu.",
       "Đổ vào bát hoặc khay có phết dầu, hấp cách thuỷ 25 phút.",
       "Phết lòng đỏ lên mặt, hấp thêm 5 phút cho lớp vân vàng chín. Cắt miếng, chấm nước mắm ớt."],
      5, TK + "tr%E1%BB%A9ng%20h%E1%BA%A5p%20v%C3%A2n",
      [("trung", "Trứng gà", 5, "quả", "n", "chinh"),
       ("thit_heo", "Thịt heo xay", 200, "g", "n", "phu"),
       ("nam", "Mộc nhĩ", 10, "g", "x", "phu"),
       ("", "Miến", 20, "g", "n", "phu"),
       HANH_LA, MAM(1), DAU(1), TIEU]),

    # ---------- Đậu bắp ----------
    R("dau_bap_luoc", "Đậu bắp luộc chấm kho quẹt", "mon_chinh", "mat", "nhe", "it", "dau_bap", "nang", 25, "de",
      "Đậu bắp luộc xanh giòn chấm kho quẹt tôm khô tóp mỡ.",
      ["Đậu bắp rửa sạch, giữ nguyên cuống để không bị nhớt.",
       "Luộc trong nước sôi có chút muối 3–4 phút, vớt ra ngâm nước lạnh rồi để ráo, cắt bỏ cuống.",
       "Kho quẹt: phi thơm hành tím, tóp mỡ và tôm khô; thêm nước mắm, đường, chút nước, tiêu, ớt, đun lửa nhỏ đến khi sệt lại.",
       "Bày đậu bắp ra đĩa, chấm với kho quẹt (hoặc chao, xì dầu)."],
      46, CP + "16496669",
      [("dau_bap", "Đậu bắp", 500, "g", "n", "chinh"),
       ("", "Tôm khô", 30, "g", "x", "phu"),
       ("thit_heo", "Mỡ heo (làm tóp)", 80, "g", "x", "phu"),
       HANH(2), MAM(3), DUONG(2), TIEU]),

    R("dau_bap_xao_toi", "Đậu bắp xào tỏi", "mon_chinh", "am", "nhe", "vua", "dau_bap", "moi", 15, "de",
      "Đậu bắp trụng sơ rồi xào nhanh với nhiều tỏi phi.",
      ["Đậu bắp rửa sạch, trụng nước sôi 1 phút rồi xả nước lạnh; cắt bỏ cuống, cắt đôi chéo.",
       "Phi tỏi đến vàng, vớt bớt một nửa để rắc sau.",
       "Cho đậu bắp vào xào lửa lớn 2–3 phút, nêm muối, hạt nêm, chút đường.",
       "Bày ra đĩa, rắc tỏi phi, ớt nếu thích."],
      40, CP + "24238935",
      [("dau_bap", "Đậu bắp", 500, "g", "n", "chinh"),
       TOI(8), HAT_NEM(1), DAU(3)]),

    # ---------- Bí, bầu ----------
    R("canh_bi_dao_tom", "Canh bí đao nấu tôm", "canh", "mat", "nhe", "it", "bi_dao", "nang", 25, "de",
      "Bí đao trong veo nấu tôm tươi – canh thanh nhiệt mùa nắng.",
      ["Tôm bóc vỏ, băm sơ, ướp chút hạt nêm, hành tím băm.",
       "Bí đao gọt vỏ, bỏ ruột, thái miếng mỏng.",
       "Phi hành, xào tôm cho đỏ, đổ khoảng 1,2 lít nước, đun sôi.",
       "Cho bí vào nấu 5–7 phút đến khi bí trong.",
       "Nêm nước mắm, hạt nêm, thả hành ngò, tiêu."],
      None, CP + "7310605",
      [("bi_dao", "Bí đao", 600, "g", "n", "chinh"),
       ("tom_the", "Tôm tươi", 150, "g", "n", "phu"),
       ("rau_thom", "Hành ngò", 1, "bó", "x", "phu"),
       HANH(2), MAM(1), HAT_NEM(1), DAU(1), TIEU]),

    R("nuoc_bi_dao", "Nước bí đao", "do_uong", "mat", "nhe", "it", "bi_dao", "nang", 60, "de",
      "Bí đao nấu với đường phèn và lá dứa, uống lạnh – giải nhiệt ngày nắng gắt.",
      ["Bí đao rửa sạch, để cả vỏ (cho nước có màu đẹp), bỏ ruột, cắt miếng.",
       "Nấu bí với khoảng 1 lít nước và lá dứa, lửa nhỏ 30–40 phút đến khi bí mềm nhừ.",
       "Cho đường phèn vào khuấy tan, nếm vừa ngọt.",
       "Lọc lấy nước (có thể xay bí rồi lọc cho đậm), để nguội, cho vào tủ lạnh. Uống với đá."],
      32, CP + "12194918-n%E1%BB%9Bc-sam-bi-dao",
      [("bi_dao", "Bí đao", 500, "g", "n", "chinh"),
       ("", "Đường phèn", 60, "g", "x", "gia_vi"),
       ("", "Lá dứa", 2, "lá", "x", "gia_vi")],
      khau_phan=2),

    R("canh_bi_do_thit_bam", "Canh bí đỏ thịt bằm", "canh", "am", "nhe", "it", "bi_do", "mua", 30, "de",
      "Bí đỏ bở ngọt nấu thịt bằm – canh dễ ăn cho cả nhà.",
      ["Bí đỏ gọt vỏ, bỏ ruột, cắt miếng vừa ăn.",
       "Thịt bằm ướp nước mắm, hành tím băm, tiêu.",
       "Phi hành, xào thịt săn lại, đổ khoảng 1,2 lít nước, đun sôi, hớt bọt.",
       "Cho bí đỏ vào nấu 15 phút đến khi mềm.",
       "Nêm nước mắm, hạt nêm, thả hành ngò."],
      51, CP + "6658364",
      [("bi_do", "Bí đỏ", 500, "g", "n", "chinh"),
       ("thit_heo", "Thịt heo xay", 150, "g", "n", "phu"),
       ("rau_thom", "Hành ngò", 1, "bó", "x", "phu"),
       HANH(2), MAM(1), HAT_NEM(1), DAU(1), TIEU]),

    R("bi_do_xao_toi", "Bí đỏ xào tỏi", "mon_chinh", "am", "nhe", "vua", "bi_do", "moi", 20, "de",
      "Bí đỏ cắt miếng xào tỏi, om nhẹ cho bở mà không nát.",
      ["Bí đỏ gọt vỏ, bỏ ruột, cắt miếng dày 1cm.",
       "Phi thơm tỏi.",
       "Cho bí vào đảo đều, nêm muối, hạt nêm, chút đường; thêm 3–4 thìa nước.",
       "Đậy nắp om lửa nhỏ 5–7 phút đến khi bí vừa chín, nước cạn.",
       "Rắc hành lá, tiêu."],
      54, CP + "295393",
      [("bi_do", "Bí đỏ", 600, "g", "n", "chinh"),
       TOI(5), HAT_NEM(1), DUONG(1), DAU(2), HANH_LA, TIEU]),

    R("canh_bau_tom", "Canh bầu nấu tôm", "canh", "mat", "nhe", "it", "bau", "nang", 20, "de",
      "Bầu non thái sợi nấu tôm – canh mát, ngọt, nấu rất nhanh.",
      ["Tôm bóc vỏ, giã hoặc băm sơ, ướp hạt nêm, hành tím.",
       "Bầu gọt vỏ, thái sợi hoặc thái miếng mỏng.",
       "Phi hành, xào tôm cho thơm, đổ khoảng 1,2 lít nước, đun sôi.",
       "Cho bầu vào nấu 2–3 phút (bầu chín rất nhanh, nấu lâu sẽ nhũn).",
       "Nêm nước mắm, hạt nêm, rắc rau mùi, tiêu."],
      69, CP + "3443935",
      [("bau", "Bầu", 1, "quả", "n", "chinh"),
       ("tom_the", "Tôm tươi", 150, "g", "n", "phu"),
       ("rau_thom", "Rau mùi", 1, "nhánh", "x", "phu"),
       HANH(2), MAM(1), HAT_NEM(1), DAU(1), TIEU]),

    # ---------- Rau củ khác ----------
    R("ca_bung", "Cà tím bung đậu phụ thịt ba chỉ", "mon_chinh", "nong", "nang", "vua", "ca_tim|dau_phu", "mua", 60, "vua",
      "Cà tím om với ba chỉ, đậu phụ rán, cà chua, mẻ, tía tô – món om dân dã ngày mưa (kiểu Bắc).",
      ["Cà tím cắt miếng, ngâm nước muối 15 phút cho đỡ thâm, vắt nhẹ.",
       "Ba chỉ thái miếng, xào cho ra mỡ, săn lại.",
       "Đậu phụ cắt miếng, rán vàng.",
       "Cho cà chua vào xào cùng thịt, thêm cà tím, mẻ, nước mắm, đổ ít nước, om lửa nhỏ 15–20 phút đến khi cà mềm nhừ.",
       "Cho đậu phụ vào om thêm 5 phút, nêm lại; tắt bếp thả tía tô, hành lá."],
      35, CP + "4052226",
      [("ca_tim", "Cà tím", 4, "quả", "n", "chinh"),
       ("dau_phu", "Đậu phụ", 3, "bìa", "n", "chinh"),
       ("thit_heo", "Thịt ba rọi", 250, "g", "n", "phu"),
       ("ca_chua", "Cà chua", 2, "quả", "n", "phu"),
       ("rau_thom", "Tía tô, hành lá", 1, "bó", "x", "phu"),
       ("", "Mẻ", 2, MC, "x", "gia_vi"),
       MAM(2), DAU(3)]),

    R("dau_co_ve_xao_thit", "Đậu cô ve xào thịt", "mon_chinh", "am", "nhe", "vua", "dau_co_ve", "moi", 25, "de",
      "Đậu cô ve Đà Lạt xào thịt nạc với tỏi và cà rốt – món xào thường ngày.",
      ["Đậu cô ve tước xơ, cắt xéo; cà rốt thái lát mỏng.",
       "Thịt nạc thái mỏng, ướp nước mắm, hành tím băm, tiêu.",
       "Phi tỏi, xào thịt đến chín, trút ra.",
       "Xào đậu và cà rốt với 3–4 thìa nước, đậy nắp 2 phút đến khi đậu xanh giòn.",
       "Cho thịt vào đảo đều, nêm nước mắm, hạt nêm."],
      117, CP + "17216547",
      [("dau_co_ve", "Đậu cô ve", 400, "g", "n", "chinh"),
       ("thit_heo", "Thịt nạc", 200, "g", "n", "phu"),
       ("ca_rot", "Cà rốt", 1, "củ", "n", "phu"),
       HANH(2), TOI(3), MAM(1), HAT_NEM(1), DAU(3), TIEU]),
]
