"""Lô 2 – món chủ dự án đề nghị thêm (lươn, chuối, lẩu Thái, lòng, nấm đùi gà...).

Cùng quy ước với lo1_bac.py: định lượng 4 người, cách làm viết lại bằng lời của Cá Chef,
link Cookpad (trang tìm kiếm) ở cột nguon chỉ để tham khảo. Tất cả "chua_nau_thu".
"""
from urllib.parse import quote

from lo1_bac import (DAU, DUONG, HANH, HANH_LA, HAT_NEM, MAM, MC, MCF, Q, R, TIEU, TOI)

TK = "https://cookpad.com/vn/tim-kiem/"
tk = lambda s: TK + quote(s)
SA = lambda n: ("sa_ot", "Sả", n, "cây", "x", "gia_vi")
OT = lambda n: ("sa_ot", "Ớt", n, "quả", "x", "gia_vi")
GUNG = lambda n: ("sa_ot", "Gừng", n, "nhánh", "x", "gia_vi")
RAU_THOM = lambda ten: ("rau_thom", ten, 1, "bó", "x", "phu")

# Nguyên liệu mới: (mã, tên, nhóm, vùng, lịch 12 tháng, nơi mua, tin cậy, ghi chú)
NGUYEN_LIEU = [
    ("luon", "Lươn", "thủy sản", "chung", Q, "chợ", "C", "Lươn nuôi có quanh năm; lươn đồng nhiều hơn mùa mưa – chưa có nguồn riêng"),
    ("oc_dong", "Ốc đồng / ốc nhồi", "thủy sản", "chung", Q, "chợ", "C", "Chưa có nguồn riêng cho Phan Rang"),
    ("hoa_chuoi", "Hoa chuối", "rau củ", "chung", Q, "chợ", "C", "Chuối trồng quanh năm – chưa có nguồn riêng"),
    ("thom", "Dứa (thơm)", "trái cây", "chung", Q, "chợ/GO!", "C", "Có quanh năm – chưa có nguồn riêng"),
]

RECIPES = [
    # ---------- Lươn ----------
    R("luon_xao_sa_ot", "Lươn xào sả ớt", "mon_chinh", "nong", "nhe", "vua", "luon", "mua", 35, "vua",
      "Lươn làm sạch nhớt, xào lửa lớn với sả ớt cho săn thơm – đưa cơm ngày mưa (bớt ớt phần trẻ con).",
      ["Lươn làm sạch: xát muối hoặc tro bếp cho hết nhớt, rửa lại nhiều lần, bỏ ruột, cắt khúc 4–5 cm.",
       "Ướp lươn với nước mắm, hạt nêm, chút nghệ, một nửa sả băm trong 15 phút.",
       "Phi thơm hành, tỏi, phần sả còn lại; cho lươn vào xào lửa lớn đến khi săn và vàng mặt.",
       "Thêm ớt (múc riêng phần cho trẻ trước), nêm lại, rắc rau răm hoặc lá lốt thái nhỏ rồi tắt bếp."],
      None, tk("lươn xào sả ớt"),
      [("luon", "Lươn", 600, "g", "n", "chinh"), SA(4), OT(2), ("", "Nghệ", 1, "nhánh", "x", "gia_vi"),
       TOI(4), HANH(2), MAM(1.5), HAT_NEM(1), DAU(2), RAU_THOM("Rau răm, lá lốt")]),
    R("mien_luon", "Miến lươn", "mon_chinh", "nong", "nhe", "it", "luon", "mua", 60, "vua",
      "Miến dong chan nước dùng xương, lươn chiên giòn rắc lên trên – món một tô kiểu Hà Nội.",
      ["Ninh xương heo khoảng 40 phút, hớt bọt, nêm nước mắm, hạt nêm cho thanh.",
       "Lươn làm sạch nhớt, luộc sơ, gỡ thịt thành sợi; xương lươn cho vào nồi nước dùng cho ngọt.",
       "Thịt lươn ướp chút nước mắm, tiêu, chiên giòn (hoặc xào săn với hành nếu muốn mềm cho trẻ).",
       "Trụng miến, xếp vào tô với giá, hành lá, rau răm; xếp lươn lên trên và chan nước dùng thật nóng."],
      None, tk("miến lươn"),
      [("luon", "Lươn", 500, "g", "n", "chinh"), ("bun", "Miến dong", 300, "g", "n", "phu"),
       ("thit_heo", "Xương heo", 500, "g", "x", "phu"), ("gia_do", "Giá đỗ", 200, "g", "n", "phu"),
       RAU_THOM("Rau răm"), HANH_LA, HANH(2), MAM(2), HAT_NEM(2), TIEU, DAU(4)]),
    R("luon_om_chuoi_dau", "Lươn om chuối đậu", "mon_chinh", "nong", "nang", "vua", "luon|chuoi_xanh", "mua", 75, "vua",
      "Lươn om với chuối xanh, đậu phụ rán, mẻ, nghệ, tía tô – món om dân dã miền Bắc.",
      ["Lươn làm sạch nhớt, cắt khúc; ướp với mẻ, nghệ, mắm tôm, chút nước mắm 20 phút.",
       "Chuối xanh gọt vỏ, cắt khúc, ngâm nước muối pha chút giấm cho khỏi thâm; đậu phụ cắt miếng rán vàng.",
       "Phi hành, cho lươn vào đảo săn, thêm chuối và nước xâm xấp, om lửa nhỏ đến khi chuối mềm (khoảng 25 phút).",
       "Cho đậu phụ vào om thêm 5 phút, nêm lại; tắt bếp thả tía tô, lá lốt, hành lá."],
      None, tk("lươn om chuối đậu"),
      [("luon", "Lươn", 600, "g", "n", "chinh"), ("chuoi_xanh", "Chuối xanh", 6, "quả", "n", "chinh"),
       ("dau_phu", "Đậu phụ", 3, "bìa", "n", "phu"), ("", "Mẻ", 2, MC, "x", "gia_vi"), ("", "Mắm tôm", 1, MCF, "x", "gia_vi"),
       ("", "Nghệ", 1, "nhánh", "x", "gia_vi"), RAU_THOM("Tía tô, lá lốt"), HANH(2), MAM(1), DAU(3)]),

    # ---------- Chuối ----------
    R("oc_nau_chuoi_dau", "Ốc nấu chuối đậu", "mon_chinh", "nong", "nang", "vua", "oc_dong|chuoi_xanh", "mua", 75, "vua",
      "Ốc nhồi, chuối xanh, đậu rán nấu với mẻ, nghệ, tía tô – vị chua bùi đặc trưng ngày se lạnh.",
      ["Ốc ngâm nước vo gạo có ớt 2–3 tiếng cho nhả nhớt, luộc sơ, khều lấy thịt, bóp muối và giấm rồi rửa lại.",
       "Chuối xanh gọt vỏ, cắt khúc, ngâm nước muối; đậu phụ rán vàng; ba chỉ thái miếng nhỏ.",
       "Xào ba chỉ cho ra mỡ, cho ốc vào đảo với mẻ, nghệ, mắm tôm; thêm chuối và nước xâm xấp, om nhỏ lửa 25 phút.",
       "Cho đậu phụ vào, nêm lại cho vừa chua mặn; tắt bếp rắc tía tô, lá lốt, hành lá."],
      None, tk("ốc nấu chuối đậu"),
      [("oc_dong", "Ốc nhồi / ốc đồng", 1000, "g", "n", "chinh"), ("chuoi_xanh", "Chuối xanh", 6, "quả", "n", "chinh"),
       ("dau_phu", "Đậu phụ", 3, "bìa", "n", "phu"), ("thit_heo", "Ba chỉ", 200, "g", "n", "phu"),
       ("", "Mẻ", 2, MC, "x", "gia_vi"), ("", "Mắm tôm", 1, MCF, "x", "gia_vi"), ("", "Nghệ", 1, "nhánh", "x", "gia_vi"),
       RAU_THOM("Tía tô, lá lốt"), MAM(1), DAU(2)]),
    R("nom_hoa_chuoi", "Nộm hoa chuối", "goi", "mat", "nhe", "it", "hoa_chuoi", "nang", 40, "vua",
      "Hoa chuối thái mỏng trộn thịt luộc, rau thơm, lạc rang, nước trộn chua ngọt – giòn mát ngày nắng.",
      ["Bóc bỏ lớp bẹ già, thái hoa chuối thật mỏng, thả ngay vào nước có chanh hoặc giấm cho khỏi thâm; ngâm 20 phút rồi vắt ráo.",
       "Luộc ba chỉ hoặc tai heo cho chín, thái mỏng; rang lạc giã dập.",
       "Pha nước trộn: nước mắm, đường, nước cốt chanh, tỏi ớt băm, khuấy tan.",
       "Trộn hoa chuối, thịt, rau răm, kinh giới với nước trộn; để 5 phút cho thấm rồi rắc lạc rang."],
      None, tk("nộm hoa chuối"),
      [("hoa_chuoi", "Hoa chuối", 2, "bắp", "n", "chinh"), ("thit_heo", "Ba chỉ hoặc tai heo", 250, "g", "n", "phu"),
       ("dau_phong", "Lạc rang", 50, "g", "x", "phu"), RAU_THOM("Rau răm, kinh giới"),
       ("khe_me", "Chanh", 2, "quả", "x", "gia_vi"), MAM(3), DUONG(2), TOI(3), OT(1)]),
    R("che_chuoi", "Chè chuối nước cốt dừa", "trang_mieng", "am", "nhe", "it", "chuoi_chin|dua", "moi", 35, "de",
      "Chuối chín nấu với bột báng, nước cốt dừa, rắc lạc rang – tráng miệng trẻ con rất thích.",
      ["Chuối chín bóc vỏ, cắt khúc, ướp chút đường 15 phút cho ngọt đều.",
       "Ngâm bột báng 10 phút; đun nước sôi, cho bột báng vào nấu đến khi trong.",
       "Thêm chuối và nước cốt dừa, nấu lửa nhỏ 5–7 phút, nêm đường và chút muối cho đậm.",
       "Múc ra chén, rắc lạc rang giã dập và mè rang; ăn nóng hoặc để nguội đều ngon."],
      None, tk("chè chuối"),
      [("chuoi_chin", "Chuối chín", 6, "quả", "n", "chinh"), ("dua", "Nước cốt dừa", 400, "ml", "n", "phu"),
       ("", "Bột báng", 50, "g", "n", "phu"), ("dau_phong", "Lạc rang", 30, "g", "x", "phu"), DUONG(4)]),

    # ---------- Lẩu ----------
    R("lau_thai", "Lẩu Thái chua cay", "lau", "nong", "nang", "vua", "tom_the|muc_tuoi", "mua", 60, "vua",
      "Nước lẩu chua cay thơm sả, riềng, lá chanh, nhúng tôm mực, nấm, rau – bữa tối cuối tuần (để riêng nồi ít cay cho trẻ).",
      ["Ninh xương heo hoặc xương gà 30 phút lấy nước dùng.",
       "Đập dập sả, riềng thái lát, lá chanh vò; phi thơm cùng tỏi, cho cà chua và gói gia vị lẩu Thái (hoặc sa tế) vào xào.",
       "Đổ nước dùng vào, nêm nước cốt chanh hoặc me, nước mắm, đường cho vị chua cay mặn ngọt hài hoà.",
       "Tôm bóc chỉ lưng, mực cắt khoanh, nấm rửa sạch; bày cùng rau muống, cải thảo, bún. Nhúng chín tới khi ăn."],
      None, tk("lẩu thái"),
      [("tom_the", "Tôm", 400, "g", "n", "chinh"), ("muc_tuoi", "Mực", 400, "g", "n", "chinh"),
       ("nam", "Nấm các loại", 300, "g", "n", "phu"), ("ca_chua", "Cà chua", 3, "quả", "n", "phu"),
       ("rau_muong", "Rau muống", 300, "g", "n", "phu"), ("cai_thao", "Cải thảo", 300, "g", "n", "phu"),
       ("bun", "Bún", 600, "g", "n", "phu"), ("thit_heo", "Xương heo", 500, "g", "x", "phu"),
       SA(4), ("sa_ot", "Riềng", 1, "nhánh", "x", "gia_vi"), ("", "Lá chanh", 10, "lá", "x", "gia_vi"),
       ("", "Gia vị lẩu Thái", 1, "gói", "x", "gia_vi"), ("khe_me", "Chanh", 3, "quả", "x", "gia_vi"), MAM(2), DUONG(1), TOI(4)]),

    # ---------- Tôm, cá ----------
    R("tom_rang_chay_canh", "Tôm rang cháy cạnh", "mon_chinh", "nong", "nhe", "vua", "tom_the", "moi", 25, "de",
      "Tôm rang với hành, nước mắm đường đến khi vỏ đỏ au, xém cạnh – ăn cả vỏ giòn.",
      ["Tôm cắt râu, bỏ chỉ lưng, rửa sạch, để thật ráo.",
       "Phi thơm hành tím, cho tôm vào rang lửa lớn đến khi đỏ đều và vỏ hơi xém.",
       "Thêm nước mắm, đường, đảo đến khi nước sánh lại bám vào vỏ tôm.",
       "Rắc tiêu, hành lá cắt khúc, đảo đều rồi tắt bếp."],
      None, tk("tôm rang"),
      [("tom_the", "Tôm", 500, "g", "n", "chinh"), HANH(3), MAM(1.5), DUONG(1), TIEU, HANH_LA, DAU(2)]),
    R("ca_ro_phi_ran", "Cá rô phi rán chấm nước mắm gừng", "mon_chinh", "nong", "nhe", "nhieu", "", "moi", 30, "de",
      "Cá rán vàng giòn hai mặt, chấm nước mắm gừng – món mặn quen thuộc của mâm cơm Bắc.",
      ["Cá làm sạch, khứa vài đường hai bên thân, xát chút muối, để thật ráo (thấm khăn giấy).",
       "Đun dầu thật nóng, thả cá vào rán lửa vừa, không lật sớm; mặt dưới vàng giòn mới lật mặt kia.",
       "Pha nước chấm: nước mắm, đường, nước cốt chanh, gừng và tỏi băm, ớt (để riêng chén không ớt cho bé).",
       "Vớt cá ra giấy thấm dầu, bày đĩa, ăn nóng với nước chấm."],
      None, tk("cá rán"),
      [("", "Cá rô phi (hoặc cá diêu hồng)", 2, "con", "n", "chinh"), GUNG(1), TOI(3), MAM(3), DUONG(2),
       ("khe_me", "Chanh", 1, "quả", "x", "gia_vi"), OT(1), DAU(8)]),
    R("ca_bac_ma_kho_tieu", "Cá bạc má kho tiêu", "mon_chinh", "nong", "nang", "vua", "ca_bac_ma", "mua", 50, "de",
      "Cá bạc má kho với nước màu, tiêu xanh và tiêu xay – mặn ngọt, cay nhẹ, rất đưa cơm.",
      ["Cá làm sạch, cắt khúc hoặc để nguyên con nhỏ; ướp nước mắm, đường, hành tỏi băm, tiêu 20 phút.",
       "Xếp cá vào nồi, thêm 1 thìa nước màu và nước xâm xấp mặt cá.",
       "Kho lửa vừa 10 phút rồi hạ nhỏ lửa, kho tiếp 25–30 phút đến khi nước sánh lại; không đảo để cá khỏi nát.",
       "Rắc thêm tiêu xanh đập dập, hành lá; tắt bếp."],
      None, tk("cá bạc má kho tiêu"),
      [("ca_bac_ma", "Cá bạc má", 600, "g", "n", "chinh"), ("", "Tiêu xanh", 1, "nhánh", "x", "gia_vi"), TIEU,
       ("", "Nước màu", 1, MC, "x", "gia_vi"), MAM(3), DUONG(1.5), HANH(2), TOI(3), HANH_LA]),

    # ---------- Lòng, lưỡi heo ----------
    R("long_heo_luoc", "Lòng heo luộc chấm mắm tôm", "mon_chinh", "am", "nhe", "vua", "long_heo", "moi", 60, "vua",
      "Lòng non, dạ dày, tim gan luộc chín tới, chấm mắm tôm chanh – món nhậu thành món cơm nhà (không hợp trẻ nhỏ).",
      ["Lòng non lộn mặt, bỏ mỡ thừa, bóp kỹ với muối, chanh hoặc giấm rồi rửa nhiều nước; dạ dày chà muối, bóp bột mì cho sạch nhớt.",
       "Chần sơ tất cả qua nước sôi 2 phút, đổ bỏ nước đầu.",
       "Luộc với nước mới có gừng đập, hành, chút muối; tim gan 15 phút, lòng 15–20 phút, dạ dày 30 phút. Vớt ra ngâm nước đá cho giòn.",
       "Thái miếng vừa ăn; pha mắm tôm với đường, chanh, ớt, đánh bông. Ăn kèm rau thơm, dưa leo."],
      None, tk("lòng heo luộc"),
      [("long_heo", "Lòng non, dạ dày, tim gan heo", 800, "g", "n", "chinh"), GUNG(1), HANH(2),
       ("", "Mắm tôm", 2, MC, "x", "gia_vi"), ("khe_me", "Chanh", 2, "quả", "x", "gia_vi"), DUONG(1),
       ("dua_leo", "Dưa leo", 2, "quả", "n", "phu"), RAU_THOM("Rau thơm, kinh giới")]),
    R("long_heo_xao_dua_cai", "Lòng heo xào dưa cải", "mon_chinh", "nong", "nhe", "vua", "long_heo", "mua", 40, "vua",
      "Lòng heo luộc sơ xào với dưa cải chua, cà chua, hành – vị chua giòn, đậm đà.",
      ["Làm sạch lòng như món lòng luộc, luộc sơ 10 phút rồi thái miếng.",
       "Dưa cải chua vắt bớt nước, cắt khúc; cà chua bổ múi.",
       "Phi tỏi, xào lòng lửa lớn với chút nước mắm cho săn, múc ra.",
       "Xào cà chua cho mềm, cho dưa vào đảo 3 phút, trút lòng vào, nêm đường, nước mắm; thêm hành lá, tiêu rồi tắt bếp."],
      None, tk("lòng xào dưa"),
      [("long_heo", "Lòng heo", 600, "g", "n", "chinh"), ("cai_xanh", "Dưa cải chua", 400, "g", "n", "phu"),
       ("ca_chua", "Cà chua", 2, "quả", "n", "phu"), TOI(4), MAM(1.5), DUONG(1), HANH_LA, TIEU, DAU(2)]),
    R("luoi_heo_luoc", "Lưỡi heo luộc", "mon_chinh", "am", "nhe", "it", "thit_heo", "moi", 50, "de",
      "Lưỡi heo luộc giòn sần sật, thái mỏng chấm nước mắm gừng hoặc muối tiêu chanh.",
      ["Chần lưỡi qua nước sôi 1–2 phút, vớt ra dùng dao cạo sạch lớp màng trắng, xát muối rửa lại.",
       "Luộc lưỡi với gừng đập, hành, chút muối khoảng 30–35 phút; xiên đũa không ra nước hồng là chín.",
       "Vớt ra ngâm ngay vào nước đá 5 phút cho giòn và trắng.",
       "Thái lát mỏng, chấm nước mắm gừng hoặc muối tiêu chanh; ăn kèm dưa leo, rau thơm."],
      None, tk("lưỡi heo luộc"),
      [("thit_heo", "Lưỡi heo", 2, "cái", "n", "chinh"), GUNG(1), HANH(2), MAM(2), DUONG(1),
       ("khe_me", "Chanh", 1, "quả", "x", "gia_vi"), ("dua_leo", "Dưa leo", 2, "quả", "n", "phu")]),

    # ---------- Gà, bò, ếch ----------
    R("long_ga_xao_gia_dua", "Lòng gà xào giá đỗ dứa", "mon_chinh", "nong", "nhe", "vua", "ga_ta|gia_do|thom", "moi", 30, "de",
      "Mề, tim, gan gà xào nhanh với dứa và giá đỗ – chua ngọt, giòn, nhanh gọn.",
      ["Mề gà bóc màng vàng, khứa hoa; tim gan cắt đôi; bóp với muối và rượu trắng rồi rửa sạch, ướp nước mắm, tiêu, tỏi 10 phút.",
       "Dứa thái miếng mỏng; giá nhặt rễ, rửa ráo; hành lá cắt khúc.",
       "Phi tỏi, xào lòng gà lửa lớn 3–4 phút cho chín tới, múc ra.",
       "Xào dứa 1 phút, cho giá và lòng gà vào đảo nhanh tay 1 phút, nêm lại, thêm hành lá; tắt bếp khi giá còn giòn."],
      None, tk("lòng gà xào giá dứa"),
      [("ga_ta", "Lòng gà (mề, tim, gan)", 500, "g", "n", "chinh"), ("gia_do", "Giá đỗ", 300, "g", "n", "chinh"),
       ("thom", "Dứa", 0.5, "quả", "n", "chinh"), TOI(4), MAM(1.5), DUONG(0.5), TIEU, HANH_LA, DAU(2)]),
    R("com_ga_hoi_an", "Cơm gà Hội An", "mon_chinh", "am", "nang", "vua", "ga_ta", "moi", 90, "vua",
      "Cơm nấu nước luộc gà với nghệ cho vàng tơi, gà xé trộn rau răm hành tây, kèm đu đủ bóp.",
      ["Luộc gà với gừng, hành, chút muối khoảng 25–30 phút; ngâm gà vào nước đá cho da giòn, giữ nước luộc.",
       "Vo gạo, để ráo; xào gạo với mỡ gà, tỏi phi và chút nghệ cho vàng đều, rồi nấu bằng nước luộc gà.",
       "Gà xé sợi, trộn với hành tây thái mỏng (ngâm nước đá), rau răm, chút nước mắm, chanh, tiêu.",
       "Bày cơm ra đĩa, gà xé lên trên; ăn kèm đu đủ bóp, chén nước luộc gà nóng và tương ớt (để riêng)."],
      None, tk("cơm gà hội an"),
      [("ga_ta", "Gà ta", 1.2, "kg", "n", "chinh"), ("", "Gạo", 500, "g", "n", "phu"), ("", "Hành tây", 1, "củ", "n", "phu"),
       ("du_du", "Đu đủ xanh", 300, "g", "n", "phu"), RAU_THOM("Rau răm"), ("", "Nghệ", 1, "nhánh", "x", "gia_vi"),
       GUNG(1), TOI(4), MAM(2), ("khe_me", "Chanh", 1, "quả", "x", "gia_vi"), TIEU]),
    R("su_su_xao_thit_bo", "Su su xào thịt bò", "mon_chinh", "am", "nhe", "vua", "su_su|thit_bo", "moi", 20, "de",
      "Su su thái lát giòn ngọt xào nhanh với thịt bò mềm – vừa rau vừa đạm.",
      ["Thịt bò thái mỏng ngang thớ, ướp dầu hào, chút nước mắm, tiêu, tỏi và 1 thìa dầu ăn 10 phút.",
       "Su su gọt vỏ, bỏ lõi, thái lát mỏng.",
       "Xào bò lửa thật lớn 1 phút cho tái, múc ra.",
       "Xào su su với tỏi cho chín tới (thêm chút nước nếu khô), nêm vừa, trút bò vào đảo đều 30 giây, thêm hành lá rồi tắt bếp."],
      None, tk("su su xào thịt bò"),
      [("su_su", "Su su", 3, "quả", "n", "chinh"), ("thit_bo", "Thịt bò", 250, "g", "n", "chinh"),
       ("", "Dầu hào", 1, MC, "x", "gia_vi"), TOI(4), MAM(1), TIEU, HANH_LA, DAU(2)]),
    R("ech_xao_mang_cay", "Ếch xào măng cay", "mon_chinh", "nong", "nhe", "vua", "ech", "mua", 40, "vua",
      "Ếch chặt miếng xào với măng chua, sả, ớt – cay thơm, đậm vị (múc riêng phần ít cay cho bé).",
      ["Ếch làm sạch, chặt miếng vừa ăn; ướp nước mắm, hạt nêm, sả băm, chút nghệ 15 phút.",
       "Măng chua rửa sạch, luộc sơ 5 phút cho bớt mùi, vắt ráo.",
       "Phi thơm tỏi, sả; cho ếch vào xào lửa lớn đến khi săn và hơi vàng.",
       "Thêm măng, ớt, đảo 3–4 phút cho thấm; nêm lại, rắc lá lốt hoặc rau răm thái nhỏ."],
      None, tk("ếch xào măng"),
      [("ech", "Ếch", 600, "g", "n", "chinh"), ("", "Măng chua", 300, "g", "n", "phu"), SA(3), OT(3),
       ("", "Nghệ", 1, "nhánh", "x", "gia_vi"), TOI(4), MAM(1.5), HAT_NEM(1), DAU(2), RAU_THOM("Lá lốt, rau răm")]),
    R("canh_bo_kim_chi", "Canh bò Mỹ kim chi nấm kim châm", "canh", "nong", "nhe", "it", "thit_bo|nam", "mua", 25, "de",
      "Canh kiểu Hàn: ba chỉ bò Mỹ, kim chi, nấm kim châm, đậu phụ non – chua cay nhẹ, ấm bụng.",
      ["Xào kim chi với chút dầu 2 phút cho dậy mùi.",
       "Thêm nước (khoảng 1,2 lít) và chút nước kim chi, đun sôi; nêm nước mắm, hạt nêm, chút đường cho dịu vị chua.",
       "Cho đậu phụ non cắt miếng và nấm kim châm (đã cắt gốc) vào nấu 3 phút.",
       "Thả ba chỉ bò vào, sôi lại là tắt bếp để thịt mềm; rắc hành lá. Phần của bé múc trước khi cho nhiều kim chi."],
      None, tk("canh kim chi bò"),
      [("thit_bo", "Ba chỉ bò Mỹ", 300, "g", "n", "chinh"), ("nam", "Nấm kim châm", 200, "g", "n", "chinh"),
       ("", "Kim chi cải thảo", 250, "g", "n", "phu"), ("dau_phu", "Đậu phụ non", 1, "hộp", "n", "phu"),
       MAM(1), HAT_NEM(1), DUONG(0.5), HANH_LA, DAU(1)]),

    # ---------- Nấm ----------
    R("nem_nam_dui_ga", "Nem nấm đùi gà", "mon_chinh", "am", "nhe", "nhieu", "nam", "moi", 60, "vua",
      "Nấm đùi gà xé sợi trộn miến, cà rốt, mộc nhĩ, cuộn bánh đa nem rán giòn – nem kiểu chay, giòn thơm.",
      ["Nấm đùi gà xé sợi, xào khô với chút muối cho ra hết nước; mộc nhĩ ngâm nở thái sợi; cà rốt bào sợi; miến ngâm mềm cắt ngắn.",
       "Trộn nhân với trứng, hành lá, tiêu, hạt nêm cho kết dính.",
       "Cuộn nhân vào bánh đa nem, cuộn chặt tay, gấp hai đầu.",
       "Rán lửa vừa đến khi vàng giòn (hoặc nồi chiên không dầu 180°C khoảng 15 phút, lật giữa chừng). Chấm nước mắm chua ngọt."],
      None, tk("nem nấm đùi gà"),
      [("nam", "Nấm đùi gà", 400, "g", "n", "chinh"), ("ca_rot", "Cà rốt", 1, "củ", "n", "phu"),
       ("", "Mộc nhĩ", 20, "g", "n", "phu"), ("bun", "Miến", 50, "g", "n", "phu"), ("trung", "Trứng gà", 1, "quả", "n", "phu"),
       ("banh_trang", "Bánh đa nem", 20, "lá", "n", "phu"), HAT_NEM(1), TIEU, DAU(10)]),
    R("nam_dui_ga_xao_toi", "Nấm đùi gà xào tỏi", "mon_chinh", "am", "nhe", "vua", "nam", "moi", 15, "de",
      "Nấm đùi gà thái lát xào lửa lớn với tỏi, chút dầu hào – dai giòn như thịt, xong trong 15 phút.",
      ["Nấm đùi gà rửa nhanh, thấm khô, thái lát dày khoảng 0,5 cm (hoặc xé sợi).",
       "Phi thơm tỏi băm với dầu ăn (hoặc chút bơ).",
       "Cho nấm vào xào lửa lớn đến khi hơi vàng mép, không đảo quá nhiều để nấm khỏi ra nước.",
       "Nêm dầu hào, chút nước tương, tiêu; thêm hành lá hoặc rau mùi rồi tắt bếp."],
      None, tk("nấm đùi gà xào tỏi"),
      [("nam", "Nấm đùi gà", 400, "g", "n", "chinh"), TOI(5), ("", "Dầu hào", 1, MC, "x", "gia_vi"),
       ("", "Nước tương", 1, MCF, "x", "gia_vi"), TIEU, HANH_LA, DAU(2)]),
    R("bi_ngo_non_xao_toi", "Bí ngô non xào tỏi", "mon_chinh", "am", "nhe", "it", "bi_do", "moi", 15, "de",
      "Quả bí ngô non thái lát xào tỏi – ngọt mát, mềm, trẻ con dễ ăn.",
      ["Bí ngô non rửa sạch, để nguyên vỏ (vỏ non mềm), bỏ ruột nếu có, thái lát mỏng.",
       "Phi thơm tỏi đập dập.",
       "Cho bí vào xào lửa lớn 2–3 phút, thêm vài thìa nước nếu khô, nêm muối hoặc hạt nêm.",
       "Bí vừa chín tới, còn xanh là tắt bếp để giữ độ giòn ngọt."],
      None, tk("bí ngô non xào tỏi"),
      [("bi_do", "Bí ngô non", 2, "quả", "n", "chinh"), TOI(4), HAT_NEM(1), DAU(2)]),
]
