"""Lô 3 – món đạm cho đa dạng (gà, vịt, ngan, bò, lợn, cá biển địa phương, hải sản, trứng),
món nấu với dưa cải chua và kim chi, và 3 bữa nướng (bữa chính một món như lẩu).

Cùng quy ước với lo1_bac.py: định lượng 4 người, cách làm viết lại bằng lời của Cá Chef,
link Cookpad (trang tìm kiếm) ở cột nguon chỉ để tham khảo. Tất cả "chua_nau_thu".
KHUNG: (mã món, vai mâm, nhóm đạm) – xuat_csv.py ghi vào khung_mon.csv với nguon_loai "lo3".
"""
from urllib.parse import quote

from lo1_bac import (DAU, DUONG, HANH, HANH_LA, HAT_NEM, MAM, MC, MCF, Q, R, TIEU, TOI, ro)

TK = "https://cookpad.com/vn/tim-kiem/"
tk = lambda s: TK + quote(s)
SA = lambda n: ("sa_ot", "Sả", n, "cây", "x", "gia_vi")
OT = lambda n: ("sa_ot", "Ớt", n, "quả", "x", "gia_vi")
GUNG = lambda n: ("sa_ot", "Gừng", n, "nhánh", "x", "gia_vi")
RAU_THOM = lambda ten: ("rau_thom", ten, 1, "bó", "x", "phu")
DAU_HAO = lambda n: ("", "Dầu hào", n, MC, "x", "gia_vi")
MUOI = ("muoi_ca_na", "Muối", None, "vừa đủ", "x", "gia_vi")

# Nguyên liệu mới: (mã, tên, nhóm, vùng, lịch 12 tháng, nơi mua, tin cậy, ghi chú)
NGUYEN_LIEU = [
    ("vit", "Vịt", "thịt", "chung", Q, "chợ", "C", "Vịt nuôi có quanh năm – chưa có nguồn riêng"),
    ("ngan", "Ngan", "thịt", "chung", Q, "chợ", "C", "Ngan nuôi có quanh năm, ở Phan Rang ít hơn vịt – chưa có nguồn riêng"),
    ("chim_cut", "Chim cút", "thịt", "chung", Q, "chợ", "C", "Chim cút nuôi có quanh năm – chưa có nguồn riêng"),
    ("ca_chep", "Cá chép", "thủy sản", "chung", Q, "chợ/GO!", "C", "Cá nuôi nước ngọt; chợ Phan Rang ít gặp, siêu thị có cá làm sẵn"),
    ("ca_tram", "Cá trắm", "thủy sản", "chung", Q, "chợ/GO!", "C", "Cá nuôi nước ngọt; chợ Phan Rang ít gặp, siêu thị có cá cắt khúc"),
    ("sau", "Sấu", "trái cây", "Miền Bắc", ro(5, 6, 7, 8), "chợ/online", "C",
     "Sấu tươi chỉ có ở miền Bắc mùa hè; ở Phan Rang mua sấu đông lạnh hoặc sấu ngâm"),
    ("thien_ly", "Hoa thiên lý", "rau củ", "chung", ro(5, 6, 7, 8), "chợ", "C", "Hoa nở rộ mùa hè – chưa có nguồn riêng"),
    ("dua_cai_chua", "Dưa cải muối chua", "khác", "chung", Q, "chợ/GO!", "A", "Dưa muối sẵn hoặc tự muối, có quanh năm"),
    ("kim_chi", "Kim chi cải thảo", "khác", "chung", Q, "GO!/siêu thị", "A", "Kim chi đóng hộp bán quanh năm ở siêu thị"),
    ("tao_do", "Táo đỏ (táo tàu)", "hàng khô", "chung", Q, "chợ/GO!/tiệm thuốc bắc", "A", "Hàng khô, có quanh năm"),
]

KHUNG = []


def M(vai, dam, *a, **kw):
    """Một món: vai mâm, nhóm đạm, rồi các tham số của R()."""
    r = R(*a, **kw)
    KHUNG.append((r["ma"], vai, dam))
    return r


RECIPES = [
    # ---------- Gà, vịt, ngan ----------
    M("man", "ga", "ga_rang_gung", "Gà rang gừng", "mon_chinh", "nong", "nhe", "vua", "ga_ta", "mua", 40, "de",
      "Gà chặt miếng rang với thật nhiều gừng, nước mắm, đường đến khi sém cạnh, thơm cay ấm bụng (kiểu Bắc).",
      ["Gà chặt miếng vừa ăn, rửa với nước muối pha gừng đập dập, để ráo.",
       "Ướp gà với nước mắm, chút đường, hạt nêm, một nửa gừng thái sợi trong 20 phút.",
       "Phi thơm hành tím, cho gà vào đảo lửa lớn đến khi săn và ra mỡ.",
       "Thêm phần gừng còn lại, rưới chút nước màu hoặc đường thắng, rang lửa vừa đến khi gà khô, sém cạnh, bóng đều.",
       "Nêm lại, rắc tiêu và hành lá rồi tắt bếp."],
      None, tk("gà rang gừng"),
      [("ga_ta", "Gà ta", 1000, "g", "n", "chinh"), GUNG(2), HANH(3), MAM(2), DUONG(1.5), HAT_NEM(1), DAU(2), TIEU, HANH_LA]),
    M("man", "ga", "ga_rang_muoi", "Gà rang muối", "mon_chinh", "nong", "nhe", "nhieu", "ga_ta", "moi", 45, "vua",
      "Gà chiên vàng rồi đảo với muối rang, lá chanh, sả, tỏi phi – giòn mặn thơm, trẻ con thích.",
      ["Gà chặt miếng, ướp chút muối, hạt nêm, tiêu 15 phút; lăn qua lớp bột năng mỏng.",
       "Chiên gà ngập dầu lửa vừa đến chín, vớt ra rồi chiên lại lửa lớn 1 phút cho giòn.",
       "Rang muối với hạt nêm, chút đường đến khô thơm; phi tỏi, sả băm, lá chanh thái chỉ cho vàng giòn.",
       "Cho gà vào chảo muối, đảo nhanh tay với tỏi, sả, lá chanh cho áo đều rồi bày ra đĩa."],
      None, tk("gà rang muối"),
      [("ga_ta", "Gà ta", 1000, "g", "n", "chinh"), ("", "Bột năng", 3, MC, "x", "phu"), ("", "Lá chanh", 10, "lá", "x", "phu"),
       SA(2), TOI(6), MUOI, HAT_NEM(1), DUONG(0.5), ("", "Dầu ăn để chiên", 500, "ml", "x", "gia_vi")]),
    M("man", "ga", "ga_xao_sa_ot", "Gà xào sả ớt", "mon_chinh", "nong", "nhe", "vua", "ga_ta", "mua", 35, "de",
      "Gà xào săn với sả, ớt, nghệ – thơm nồng đưa cơm ngày mưa (múc riêng phần bé trước khi cho ớt).",
      ["Gà chặt miếng nhỏ, ướp nước mắm, hạt nêm, chút nghệ, một nửa sả băm trong 15 phút.",
       "Phi thơm hành, tỏi, phần sả còn lại; cho gà vào đảo lửa lớn đến khi săn.",
       "Thêm chút nước, đậy nắp om nhỏ lửa 10 phút cho gà mềm và thấm.",
       "Múc riêng phần cho bé, cho ớt vào phần còn lại, đảo khô nước, rắc tiêu và lá chanh."],
      None, tk("gà xào sả ớt"),
      [("ga_ta", "Gà ta", 800, "g", "n", "chinh"), SA(4), OT(2), ("", "Nghệ", 1, "nhánh", "x", "gia_vi"),
       TOI(4), HANH(2), MAM(2), HAT_NEM(1), DUONG(1), DAU(2), ("", "Lá chanh", 5, "lá", "x", "phu")]),
    M("man", "ga", "ga_kho_sa", "Gà kho sả", "mon_chinh", "nong", "nhe", "vua", "ga_ta", "mua", 45, "de",
      "Gà kho với sả cây đập dập, nước mắm và nước màu – nước kho sệt, đậm vị, chan cơm ngon.",
      ["Gà chặt miếng, ướp nước mắm, đường, hạt nêm, tiêu, sả băm 20 phút.",
       "Phi thơm hành, sả cây đập dập; cho gà vào đảo đến săn.",
       "Thêm nước màu và nước xâm xấp, kho lửa nhỏ 20–25 phút đến khi nước sệt lại.",
       "Nêm lại vừa ăn, rắc tiêu và hành lá."],
      None, tk("gà kho sả"),
      [("ga_ta", "Gà ta", 800, "g", "n", "chinh"), SA(5), HANH(2), MAM(2), DUONG(1.5), HAT_NEM(1),
       ("", "Nước màu", 1, MC, "x", "gia_vi"), DAU(1), TIEU, HANH_LA]),
    M("man", "ga", "ngan_xao_sa_ot", "Ngan xào sả ớt", "mon_chinh", "nong", "nhe", "vua", "ngan", "mua", 45, "vua",
      "Ngan chặt miếng xào sả ớt, chút mẻ cho thơm – thịt ngan dai ngọt, chấm thêm mắm gừng (kiểu Bắc).",
      ["Ngan làm sạch, xát gừng và rượu cho bớt mùi, chặt miếng nhỏ.",
       "Ướp ngan với nước mắm, hạt nêm, sả băm, chút mẻ trong 20 phút.",
       "Phi thơm hành tỏi, cho ngan vào xào lửa lớn đến săn, thêm ít nước, đậy nắp om 15 phút cho mềm.",
       "Múc phần cho bé, thêm ớt vào phần còn lại, đảo khô, rắc lá chanh thái chỉ."],
      None, tk("ngan xào sả ớt"),
      [("ngan", "Ngan", 1000, "g", "n", "chinh"), SA(4), OT(2), GUNG(1), ("", "Mẻ", 1, MC, "x", "gia_vi"),
       TOI(4), HANH(2), MAM(2), HAT_NEM(1), DAU(2), ("", "Lá chanh", 5, "lá", "x", "phu")]),
    M("man", "ga", "vit_om_sau", "Vịt om sấu", "mon_chinh", "nong", "nang", "vua", "vit|sau", "moi", 75, "vua",
      "Vịt om với sấu chua thanh, khoai sọ bùi, chan bún hay cơm đều hợp – món Hà Nội ngày giao mùa.",
      ["Vịt làm sạch, xát gừng, chặt miếng; ướp với nước mắm, hạt nêm, hành tím băm 20 phút.",
       "Sấu (sấu đông lạnh rã đông) gọt vỏ, khía cạnh; khoai sọ gọt, cắt đôi, ngâm nước muối.",
       "Phi hành, cho vịt vào đảo săn, đổ nước ngập, thả sấu, om lửa nhỏ 30 phút.",
       "Cho khoai sọ vào om thêm 15 phút đến khi khoai mềm; dầm vài quả sấu cho nước chua dịu, nêm lại.",
       "Tắt bếp thả hành lá, rau mùi; ăn với bún hoặc cơm, chấm mắm gừng."],
      None, tk("vịt om sấu"),
      [("vit", "Vịt", 1200, "g", "n", "chinh"), ("sau", "Sấu", 10, "quả", "n", "chinh"),
       ("khoai_mon", "Khoai sọ", 500, "g", "n", "phu"), GUNG(1), HANH(3), MAM(2), HAT_NEM(1), DAU(2), HANH_LA,
       RAU_THOM("Rau mùi")]),
    M("man", "ga", "vit_kho_gung", "Vịt kho gừng", "mon_chinh", "nong", "nang", "vua", "vit", "mua", 60, "de",
      "Vịt kho gừng, nước mắm, nước màu đến khi thịt săn, nước sánh – ấm bụng, ít mùi.",
      ["Vịt chặt miếng, rửa với nước muối gừng, chần qua nước sôi cho sạch.",
       "Ướp vịt với nước mắm, đường, hạt nêm, nửa phần gừng thái sợi 20 phút.",
       "Phi hành, cho vịt vào đảo cho ra bớt mỡ, chắt bớt mỡ thừa.",
       "Thêm nước màu, phần gừng còn lại và nước xâm xấp, kho lửa nhỏ 35–40 phút đến khi sánh, rắc tiêu."],
      None, tk("vịt kho gừng"),
      [("vit", "Vịt", 1000, "g", "n", "chinh"), GUNG(2), HANH(2), MAM(2.5), DUONG(1.5), HAT_NEM(1),
       ("", "Nước màu", 1, MC, "x", "gia_vi"), TIEU]),
    M("canh", "ga", "canh_ga_tan_hat_sen", "Canh gà tần hạt sen", "canh", "am", "nhe", "it", "ga_ta|hat_sen", "moi", 90, "de",
      "Gà tần với hạt sen, táo đỏ, nấm hương – canh ngọt thanh, bổ, bé dễ ăn.",
      ["Gà chặt miếng to, chần nước sôi 2 phút, rửa sạch.",
       "Hạt sen bỏ tim, ngâm mềm; nấm hương ngâm, cắt chân; táo đỏ rửa sạch.",
       "Cho gà, hạt sen, nấm, táo đỏ, gừng vào nồi, đổ khoảng 1,5 lít nước, tần hoặc hầm lửa nhỏ 60 phút.",
       "Nêm muối, hạt nêm vừa ăn; hớt bọt, rắc hành lá."],
      None, tk("gà tần hạt sen"),
      [("ga_ta", "Gà ta", 600, "g", "n", "chinh"), ("hat_sen", "Hạt sen", 150, "g", "n", "chinh"),
       ("nam", "Nấm hương", 8, "tai", "n", "phu"), ("tao_do", "Táo đỏ", 8, "quả", "n", "phu"), GUNG(1), MUOI, HAT_NEM(1), HANH_LA]),
    M("canh", "ga", "ga_tiem_thuoc_bac", "Gà tiềm thuốc bắc", "canh", "nong", "nhe", "it", "ga_ta|tao_do", "mua", 120, "de",
      "Gà ác (hoặc gà ta) tiềm cách thủy với gói thuốc bắc, táo đỏ, kỷ tử – nước trong, ngọt thơm, bồi bổ ngày mưa.",
      ["Gà làm sạch, xát muối và gừng cho bớt mùi, chần qua nước sôi; để nguyên con hoặc chặt đôi.",
       "Gói thuốc bắc tiềm gà (đương quy, hoài sơn, kỷ tử, táo đỏ...) rửa nhanh qua nước; táo đỏ khứa nhẹ.",
       "Cho gà vào thố hoặc nồi nhỏ cùng thuốc bắc, táo đỏ, vài lát gừng, đổ nước vừa ngập.",
       "Chưng cách thủy hoặc hầm lửa thật nhỏ 90 phút đến khi gà mềm; cuối cùng nêm muối, chút hạt nêm (vị thanh, không nêm đậm).",
       "Bé ăn thịt gà và nước dùng lượng vừa phải; múc ra thố ăn nóng."],
      None, tk("gà tiềm thuốc bắc"),
      [("ga_ta", "Gà ác hoặc gà ta", 1, "con", "n", "chinh"), ("tao_do", "Táo đỏ", 10, "quả", "x", "chinh"),
       ("", "Gói thuốc bắc tiềm gà", 1, "gói", "x", "phu"), ("", "Kỷ tử", 1, MC, "x", "phu"), GUNG(1), MUOI, HAT_NEM(0.5)]),
    M("man", "ga", "me_ga_xao_dua_chua", "Mề gà xào dưa chua", "mon_chinh", "nong", "nhe", "vua", "ga_ta|dua_cai_chua", "moi", 30, "de",
      "Mề gà giòn sần sật xào với dưa cải chua, cà chua – chua nhẹ, đưa cơm (kiểu Bắc).",
      ["Mề gà bóc màng vàng, rửa muối và giấm, thái lát mỏng; ướp nước mắm, tiêu, hành băm 10 phút.",
       "Dưa cải chua vắt bớt nước, cắt khúc; cà chua bổ múi.",
       "Phi hành tỏi, xào mề lửa lớn đến săn thì múc ra.",
       "Xào cà chua cho mềm, cho dưa vào đảo 3 phút, cho mề vào đảo đều, nêm đường, nước mắm, rắc hành lá."],
      None, tk("mề gà xào dưa chua"),
      [("ga_ta", "Mề gà", 400, "g", "n", "chinh"), ("dua_cai_chua", "Dưa cải chua", 300, "g", "n", "chinh"),
       ("ca_chua", "Cà chua", 2, "quả", "n", "phu"), TOI(3), HANH(2), MAM(1.5), DUONG(1), DAU(2), TIEU, HANH_LA]),
    M("man", "ga", "chim_cut_ro_ti", "Chim cút rô ti", "mon_chinh", "nong", "nhe", "vua", "chim_cut", "moi", 50, "vua",
      "Chim cút ướp nước dừa, chiên vàng rồi rim sệt – da bóng, thịt mềm, bé cầm tay ăn được.",
      ["Chim cút làm sạch, để nguyên con hoặc chặt đôi; ướp nước mắm, đường, tỏi băm, tiêu, chút ngũ vị 30 phút.",
       "Chiên chim cút lửa vừa đến vàng đều các mặt.",
       "Phi tỏi, cho chim vào cùng nước dừa và phần nước ướp, rim lửa nhỏ 15–20 phút đến khi nước sệt, bám bóng.",
       "Bày ra đĩa, ăn kèm dưa leo, cà chua."],
      None, tk("chim cút rô ti"),
      [("chim_cut", "Chim cút", 8, "con", "n", "chinh"), ("dua", "Nước dừa", 300, "ml", "x", "phu"), TOI(5),
       MAM(2), DUONG(1.5), ("", "Ngũ vị hương", 0.5, MCF, "x", "gia_vi"), DAU(4), TIEU]),

    # ---------- Bò ----------
    M("man", "bo", "bo_xao_kho_qua", "Bò xào khổ qua", "mon_chinh", "mat", "nhe", "vua", "thit_bo|kho_qua", "nang", 25, "de",
      "Thịt bò mềm xào nhanh với khổ qua giòn – đắng nhẹ, mát người ngày nắng.",
      ["Bò thái mỏng ngang thớ, ướp dầu hào, tiêu, tỏi băm, chút dầu ăn 15 phút.",
       "Khổ qua bổ đôi, bỏ ruột, thái lát xiên; chần qua nước sôi có muối cho bớt đắng.",
       "Xào bò lửa thật lớn vừa tái thì múc ra.",
       "Phi tỏi, xào khổ qua 2 phút, cho bò vào đảo nhanh, nêm nước mắm, hạt nêm, rắc tiêu."],
      None, tk("bò xào khổ qua"),
      [("thit_bo", "Thịt bò thăn", 350, "g", "n", "chinh"), ("kho_qua", "Khổ qua", 2, "quả", "n", "chinh"),
       TOI(4), DAU_HAO(1), MAM(1), HAT_NEM(0.5), DAU(2), TIEU]),
    M("man", "bo", "bo_xao_thien_ly", "Bò xào hoa thiên lý", "mon_chinh", "mat", "nhe", "vua", "thit_bo|thien_ly", "nang", 20, "de",
      "Hoa thiên lý xanh giòn xào với thịt bò – món mùa hè thanh mát của người Hà Nội.",
      ["Bò thái mỏng, ướp tỏi băm, dầu hào, tiêu, chút dầu ăn 15 phút.",
       "Hoa thiên lý nhặt bỏ cuống già, rửa nhẹ tay, để ráo.",
       "Xào bò lửa lớn vừa tái thì múc ra.",
       "Phi tỏi, xào hoa thiên lý 1 phút, cho bò vào đảo đều, nêm hạt nêm, nước mắm rồi tắt bếp ngay cho hoa khỏi nhũn."],
      None, tk("bò xào hoa thiên lý"),
      [("thit_bo", "Thịt bò thăn", 300, "g", "n", "chinh"), ("thien_ly", "Hoa thiên lý", 300, "g", "n", "chinh"),
       TOI(4), DAU_HAO(1), MAM(1), HAT_NEM(0.5), DAU(2), TIEU]),
    M("man", "bo", "bo_bit_tet", "Bò bít tết kiểu Việt", "mon_chinh", "nong", "nang", "vua", "thit_bo", "moi", 30, "de",
      "Bò áp chảo gang với bơ tỏi, ốp la trứng, khoai tây chiên, chấm sốt tiêu – bé rất thích.",
      ["Bò cắt miếng dày 1,5 cm, đập nhẹ cho mềm, ướp tỏi băm, dầu hào, tiêu, chút dầu 20 phút.",
       "Khoai tây cắt thanh, chiên vàng; trứng ốp la để riêng.",
       "Đun nóng chảo gang, áp bò mỗi mặt 1,5–2 phút (phần bé để chín kỹ hơn), thêm bơ và tỏi đập rưới lên mặt thịt.",
       "Dùng chảo áp thịt nấu sốt: nước, chút dầu hào, tiêu đen, hành tây; rưới lên thịt, ăn kèm khoai, trứng, bánh mì."],
      None, tk("bò bít tết"),
      [("thit_bo", "Thịt bò thăn", 600, "g", "n", "chinh"), ("trung", "Trứng gà", 4, "quả", "n", "phu"),
       ("khoai_tay", "Khoai tây", 3, "củ", "n", "phu"), ("", "Hành tây", 1, "củ", "n", "phu"), ("", "Bơ", 30, "g", "x", "gia_vi"),
       TOI(5), DAU_HAO(1), ("", "Tiêu đen xay", 1, MCF, "x", "gia_vi"), DAU(3)]),
    M("man", "bo", "bo_xao_ot_chuong", "Bò xào ớt chuông", "mon_chinh", "am", "nhe", "vua", "thit_bo", "moi", 25, "de",
      "Bò mềm xào ớt chuông ba màu, hành tây – ngọt giòn, nhiều màu cho bé.",
      ["Bò thái mỏng, ướp dầu hào, tỏi, tiêu, chút bột năng và dầu ăn 15 phút.",
       "Ớt chuông bỏ hạt, cắt miếng vuông; hành tây bổ múi cau.",
       "Xào bò lửa lớn vừa tái, múc ra.",
       "Xào ớt chuông, hành tây 2 phút, cho bò vào, nêm nước tương, hạt nêm, đảo đều rồi tắt bếp."],
      None, tk("bò xào ớt chuông"),
      [("thit_bo", "Thịt bò thăn", 350, "g", "n", "chinh"), ("", "Ớt chuông", 2, "quả", "n", "phu"),
       ("", "Hành tây", 1, "củ", "n", "phu"), TOI(3), DAU_HAO(1), ("", "Nước tương", 1, MC, "x", "gia_vi"),
       HAT_NEM(0.5), DAU(2), TIEU]),
    M("man", "bo", "bo_ham_tieu_xanh", "Bò hầm tiêu xanh", "mon_chinh", "nong", "nang", "vua", "thit_bo|tieu_moi", "mua", 120, "de",
      "Bắp bò hầm mềm với tiêu xanh, sả, gừng – nước hầm cay thơm, ấm bụng ngày mưa.",
      ["Bắp bò cắt miếng vuông, chần nước sôi, rửa sạch.",
       "Ướp bò với nước mắm, hạt nêm, hành tỏi băm, sả băm 30 phút.",
       "Xào bò cho săn, đổ nước ngập, thêm gừng, sả cây đập dập, hầm lửa nhỏ 90 phút đến khi bò mềm.",
       "Thả tiêu xanh nguyên chùm, hầm thêm 10 phút, nêm lại; ăn với bánh mì hoặc cơm."],
      None, tk("bò hầm tiêu xanh"),
      [("thit_bo", "Bắp bò", 800, "g", "n", "chinh"), ("tieu_moi", "Tiêu xanh", 30, "g", "x", "chinh"), SA(3), GUNG(1),
       TOI(4), HANH(2), MAM(2), HAT_NEM(1), DAU(2)]),
    M("man", "bo", "bo_tai_chanh", "Bò tái chanh", "goi", "mat", "nhe", "it", "thit_bo", "nang", 30, "vua",
      "Thăn bò thái mỏng trần tái, trộn chanh, hành tây, rau thơm, vừng rang – món nhậu mát ngày nắng (không hợp bé).",
      ["Thăn bò thái thật mỏng; trần nhanh qua nước sôi có gừng 10 giây, vớt ra vắt ráo.",
       "Trộn bò với nước cốt chanh 5 phút cho tái, vắt bớt nước chanh.",
       "Pha nước trộn: nước mắm, đường, tỏi ớt băm, chút nước cốt chanh.",
       "Trộn bò với hành tây thái mỏng, rau răm, kinh giới, nước trộn; rắc vừng và lạc rang khi ăn."],
      None, tk("bò tái chanh"),
      [("thit_bo", "Thăn bò", 400, "g", "n", "chinh"), ("", "Chanh", 5, "quả", "x", "gia_vi"), ("", "Hành tây", 1, "củ", "n", "phu"),
       RAU_THOM("Rau răm, kinh giới"), ("dau_phong", "Lạc rang", 2, MC, "x", "phu"), ("", "Vừng rang", 1, MC, "x", "phu"),
       GUNG(1), TOI(3), OT(1), MAM(2), DUONG(1.5)]),
    M("canh", "bo", "canh_bo_nau_chua", "Canh bò nấu chua", "canh", "mat", "nhe", "it", "thit_bo|ca_chua", "nang", 30, "de",
      "Thịt bò thái mỏng nấu với cà chua, dứa, dọc mùng – chua thanh kiểu Bắc, ăn ngày nắng rất đưa cơm.",
      ["Bò thái mỏng, ướp chút nước mắm, tiêu, hành băm.",
       "Dọc mùng tước vỏ, thái vát, bóp muối rồi rửa; cà chua bổ múi; dứa thái miếng.",
       "Phi hành, xào cà chua và dứa cho mềm, đổ khoảng 1,2 lít nước đun sôi.",
       "Cho dọc mùng vào, nêm nước mắm, chút đường cho chua dịu; thả bò vào, sôi lại là tắt bếp, rắc hành, rau thơm."],
      None, tk("canh bò nấu chua"),
      [("thit_bo", "Thịt bò", 250, "g", "n", "chinh"), ("ca_chua", "Cà chua", 3, "quả", "n", "chinh"),
       ("thom", "Dứa", 0.25, "quả", "n", "phu"), ("", "Dọc mùng", 2, "cây", "n", "phu"), HANH(2), MAM(1.5),
       DUONG(0.5), HANH_LA, RAU_THOM("Rau thơm, ngò gai")]),
    M("man", "bo", "bo_xao_dua_chua", "Bò xào dưa chua", "mon_chinh", "nong", "nhe", "vua", "thit_bo|dua_cai_chua", "moi", 25, "de",
      "Bò mềm xào dưa cải chua, cà chua – chua dịu, thơm, món cơm nhà quen thuộc của người Bắc.",
      ["Bò thái mỏng, ướp tỏi, dầu hào, tiêu 15 phút.",
       "Dưa cải chua vắt bớt nước, cắt khúc; cà chua bổ múi.",
       "Xào bò lửa lớn vừa tái, múc ra.",
       "Xào cà chua cho mềm, cho dưa vào đảo 3–4 phút, nêm đường cho dịu chua; cho bò vào đảo đều, rắc hành lá."],
      None, tk("bò xào dưa chua"),
      [("thit_bo", "Thịt bò", 300, "g", "n", "chinh"), ("dua_cai_chua", "Dưa cải chua", 400, "g", "n", "chinh"),
       ("ca_chua", "Cà chua", 2, "quả", "n", "phu"), TOI(4), DAU_HAO(1), DUONG(1), MAM(0.5), DAU(2), TIEU, HANH_LA]),
    M("man", "bo", "bo_ham_dua_chua", "Bò hầm dưa chua", "mon_chinh", "nong", "nang", "vua", "thit_bo|dua_cai_chua", "mua", 120, "de",
      "Bắp bò hầm mềm với dưa cải chua, cà chua – nước hầm chua ngọt, ăn với cơm hay bún đều ngon.",
      ["Bắp bò cắt miếng vừa ăn, chần nước sôi, rửa sạch; ướp nước mắm, hạt nêm, hành băm 20 phút.",
       "Dưa cải chua vắt bớt nước, cắt khúc; cà chua bổ múi.",
       "Phi hành, xào bò cho săn, đổ nước ngập, hầm lửa nhỏ 70–80 phút đến khi bò gần mềm.",
       "Xào cà chua với dưa 3 phút rồi cho vào nồi bò, hầm thêm 20 phút; nêm đường, nước mắm cho chua dịu, rắc hành lá."],
      None, tk("bò hầm dưa chua"),
      [("thit_bo", "Bắp bò", 700, "g", "n", "chinh"), ("dua_cai_chua", "Dưa cải chua", 400, "g", "n", "chinh"),
       ("ca_chua", "Cà chua", 3, "quả", "n", "phu"), HANH(3), MAM(2), HAT_NEM(1), DUONG(1), DAU(2), HANH_LA]),

    # ---------- Lợn ----------
    M("man", "heo", "thit_chung_mam_tep", "Thịt chưng mắm tép", "mon_chinh", "nong", "nhe", "vua", "thit_heo", "moi", 40, "de",
      "Thịt ba chỉ băm chưng với mắm tép, đường, ớt – mặn ngọt đậm đà, ăn với cơm trắng, dưa cà (kiểu Bắc).",
      ["Thịt ba chỉ thái hạt lựu nhỏ hoặc băm thô.",
       "Phi thơm hành tím, cho thịt vào đảo đến khi ra mỡ, hơi xém.",
       "Thêm mắm tép, đường, chút nước, đun lửa nhỏ 15–20 phút, đảo đều đến khi sệt lại.",
       "Múc phần cho bé trước, thêm ớt vào phần còn lại; rắc tiêu, hành lá."],
      None, tk("thịt chưng mắm tép"),
      [("thit_heo", "Thịt ba chỉ", 400, "g", "n", "chinh"), ("", "Mắm tép", 3, MC, "x", "gia_vi"), DUONG(2),
       HANH(3), OT(1), DAU(1), TIEU, HANH_LA]),
    M("man", "heo", "ruoc_thit_heo", "Ruốc thịt heo", "mon_chinh", "am", "nhe", "it", "thit_heo", "moi", 90, "vua",
      "Thịt nạc rim rồi xé tơi, sao khô thành ruốc bông – làm một lần ăn nhiều bữa, bé ăn cơm, cháo đều hợp.",
      ["Thịt nạc thăn cắt miếng to theo thớ, luộc với chút muối, hành 30 phút đến chín mềm.",
       "Vớt thịt, để nguội, xé nhỏ theo thớ hoặc giã nhẹ cho tơi.",
       "Cho thịt vào chảo cùng nước mắm, đường, chút nước luộc, rim lửa nhỏ đến khi thấm khô.",
       "Sao lửa thật nhỏ, đảo liên tục 30–40 phút đến khi ruốc tơi bông, vàng nhẹ; để nguội cho vào hũ kín, ngăn mát dùng 2 tuần."],
      None, tk("ruốc thịt heo"),
      [("thit_heo", "Thịt nạc thăn", 800, "g", "x", "chinh"), MAM(3), DUONG(2), HANH(2), MUOI]),
    M("man", "heo", "gan_heo_xao_hanh", "Gan heo xào hành", "mon_chinh", "nong", "nhe", "vua", "long_heo", "moi", 20, "de",
      "Gan heo thái mỏng xào lửa lớn với hành tây, hành lá – mềm, không tanh, bổ sung sắt cho bé.",
      ["Gan ngâm sữa tươi hoặc nước muối loãng 20 phút cho sạch máu, thái lát mỏng.",
       "Ướp gan với nước mắm, tiêu, tỏi băm, chút bột năng 10 phút.",
       "Phi tỏi, xào gan lửa thật lớn 2–3 phút đến vừa chín (xào lâu gan sẽ bở, khô).",
       "Cho hành tây, hành lá vào đảo nhanh, nêm hạt nêm, tắt bếp."],
      None, tk("gan heo xào hành"),
      [("long_heo", "Gan heo", 400, "g", "n", "chinh"), ("", "Hành tây", 1, "củ", "n", "phu"), HANH_LA,
       TOI(4), MAM(1), HAT_NEM(0.5), ("", "Bột năng", 1, MCF, "x", "gia_vi"), DAU(2), TIEU]),
    M("man", "heo", "tim_cat_xao_can_toi", "Tim cật heo xào cần tỏi", "mon_chinh", "nong", "nhe", "vua", "long_heo", "moi", 30, "vua",
      "Tim, cật heo làm sạch kỹ, xào giòn với cần tây, tỏi – món xào nhanh quen thuộc mâm cơm Bắc.",
      ["Cật bổ đôi, lạng bỏ phần trắng, khía vảy rồng, ngâm nước muối gừng 15 phút; tim bổ đôi, rửa sạch máu, thái lát.",
       "Chần tim cật qua nước sôi 30 giây, vớt ra để ráo; ướp nước mắm, tiêu, tỏi.",
       "Cần tây cắt khúc, cà rốt thái lát mỏng.",
       "Phi tỏi, xào tim cật lửa lớn 2 phút, cho cần, cà rốt vào đảo, nêm dầu hào, hạt nêm."],
      None, tk("tim cật xào cần tỏi"),
      [("long_heo", "Tim, cật heo", 500, "g", "n", "chinh"), ("can_tay", "Cần tây", 200, "g", "n", "phu"),
       ("ca_rot", "Cà rốt", 1, "củ", "n", "phu"), GUNG(1), TOI(5), DAU_HAO(1), MAM(1), HAT_NEM(0.5), DAU(2), TIEU]),
    M("man", "heo", "suon_nuong_mat_ong", "Sườn nướng mật ong", "mon_chinh", "nong", "nhe", "vua", "thit_heo", "moi", 70, "vua",
      "Sườn non ướp mật ong, tỏi, nước tương rồi nướng lò hoặc nồi chiên không dầu – bóng, thơm, bé thích.",
      ["Sườn non chặt miếng dài, chần nước sôi, để ráo.",
       "Ướp sườn với mật ong, nước tương, dầu hào, tỏi băm, tiêu, chút ngũ vị ít nhất 2 tiếng (để qua đêm càng ngấm).",
       "Nướng 200°C khoảng 25 phút, lật mặt, quét lại nước ướp, nướng thêm 10–15 phút đến khi xém cạnh.",
       "Ăn với cơm, dưa leo, cà chua."],
      None, tk("sườn nướng mật ong"),
      [("thit_heo", "Sườn non", 800, "g", "n", "chinh"), ("mat_ong", "Mật ong", 3, MC, "x", "gia_vi"),
       ("", "Nước tương", 2, MC, "x", "gia_vi"), DAU_HAO(1), TOI(6), ("", "Ngũ vị hương", 0.5, MCF, "x", "gia_vi"), TIEU]),
    M("man", "heo", "thit_quay_gion_bi", "Thịt ba chỉ quay giòn bì", "mon_chinh", "nong", "nang", "nhieu", "thit_heo", "moi", 150, "kho",
      "Ba chỉ ướp ngũ vị, phơi khô bì rồi quay đến khi da nổ giòn – chấm mắm, ăn với dưa chua.",
      ["Ba chỉ miếng to luộc 10 phút, vớt ra, dùng xiên châm thật nhiều lỗ trên bì.",
       "Ướp mặt thịt (không ướp bì) với muối, đường, ngũ vị, tỏi băm; xát muối và giấm lên bì.",
       "Để mặt bì lên trên, cho vào ngăn mát không đậy khoảng 4 tiếng (hoặc qua đêm) cho bì thật khô.",
       "Nướng 180°C 40 phút, tăng 220°C thêm 20–30 phút đến khi bì phồng nổ giòn; để nguội 10 phút rồi thái miếng."],
      None, tk("thịt ba chỉ quay giòn bì"),
      [("thit_heo", "Thịt ba chỉ", 800, "g", "n", "chinh"), MUOI, DUONG(1), ("", "Ngũ vị hương", 1, MCF, "x", "gia_vi"),
       TOI(4), ("", "Giấm", 1, MC, "x", "gia_vi")]),
    M("man", "heo", "gia_cay_chan_gio", "Giả cầy (chân giò om mẻ riềng)", "mon_chinh", "nong", "nang", "vua", "thit_heo", "mua", 120, "kho",
      "Chân giò thui vàng om với riềng, mẻ, mắm tôm, nghệ – món ngày lạnh đậm vị của người Bắc.",
      ["Chân giò thui vàng bì (hoặc khò), cạo sạch, chặt miếng vừa ăn.",
       "Ướp với riềng giã, nghệ, mẻ, mắm tôm, nước mắm, chút đường ít nhất 2 tiếng.",
       "Phi hành, đảo chân giò cho săn, đổ nước xâm xấp, om lửa nhỏ 60–70 phút đến khi mềm, nước sánh.",
       "Nêm lại, thả lá lốt, hành lá thái nhỏ rồi tắt bếp; ăn với bún hoặc cơm nóng."],
      None, tk("giả cầy chân giò"),
      [("thit_heo", "Chân giò", 1200, "g", "n", "chinh"), ("", "Riềng", 1, "củ", "x", "gia_vi"), ("", "Nghệ", 1, "nhánh", "x", "gia_vi"),
       ("", "Mẻ", 3, MC, "x", "gia_vi"), ("", "Mắm tôm", 1, MC, "x", "gia_vi"), MAM(1), DUONG(1), HANH(3), DAU(2),
       RAU_THOM("Lá lốt, hành lá")]),
    M("man", "heo", "mong_gio_ham_mang", "Móng giò hầm măng", "mon_chinh", "nong", "nang", "vua", "thit_heo|mang_rung", "mua", 120, "vua",
      "Móng giò hầm mềm với măng khô hoặc măng tươi – nước ngọt béo, món quen ngày lạnh.",
      ["Măng khô ngâm qua đêm, luộc kỹ vài lần thay nước, xé sợi (măng tươi luộc kỹ bỏ nước đắng).",
       "Móng giò chặt miếng, chần nước sôi, rửa sạch.",
       "Xào măng với hành, nước mắm cho thấm; cho móng giò vào, đổ nước ngập, hầm lửa nhỏ 80–90 phút.",
       "Nêm lại vừa ăn, rắc hành lá, tiêu."],
      None, tk("móng giò hầm măng"),
      [("thit_heo", "Móng giò", 1000, "g", "n", "chinh"), ("mang_rung", "Măng", 300, "g", "n", "chinh"),
       HANH(3), MAM(2), HAT_NEM(1), DAU(1), HANH_LA, TIEU]),
    M("man", "heo", "xiu_mai_sot_ca", "Xíu mại sốt cà", "mon_chinh", "am", "nhe", "vua", "thit_heo|ca_chua", "moi", 50, "vua",
      "Viên thịt mềm trộn củ sắn, mộc nhĩ hấp chín rồi rim sốt cà chua – bé ăn với bánh mì hoặc cơm.",
      ["Thịt băm trộn củ sắn (củ đậu) băm, mộc nhĩ băm, hành tím, nước mắm, tiêu, chút bột năng; nhồi đều, vo viên.",
       "Hấp viên thịt 15 phút cho chín và giữ dáng; giữ lại nước hấp.",
       "Phi hành, xào cà chua băm cho nhừ, thêm chút tương cà, nước hấp viên, nêm đường, nước mắm.",
       "Cho viên vào rim lửa nhỏ 10 phút cho thấm sốt, rắc hành lá."],
      None, tk("xíu mại sốt cà"),
      [("thit_heo", "Thịt heo băm", 500, "g", "n", "chinh"), ("ca_chua", "Cà chua", 4, "quả", "n", "chinh"),
       ("", "Củ sắn (củ đậu)", 150, "g", "n", "phu"), ("", "Mộc nhĩ", 5, "tai", "n", "phu"), HANH(3),
       ("", "Tương cà", 2, MC, "x", "gia_vi"), MAM(1.5), DUONG(1), ("", "Bột năng", 1, MC, "x", "gia_vi"), DAU(2), TIEU, HANH_LA]),
    M("man", "heo", "thit_kho_dua_cai", "Thịt ba chỉ kho dưa cải", "mon_chinh", "nong", "nang", "vua", "thit_heo|dua_cai_chua", "mua", 60, "de",
      "Ba chỉ kho với dưa cải chua đến khi dưa ngấm mỡ, thịt mềm – chua mặn ngọt, để được vài bữa.",
      ["Ba chỉ cắt miếng vừa ăn, ướp nước mắm, đường, hành băm 20 phút.",
       "Dưa cải chua vắt bớt nước, cắt khúc (dưa chua quá thì rửa qua).",
       "Thắng chút đường làm nước màu, cho thịt vào đảo săn, thêm nước xâm xấp, kho 20 phút.",
       "Cho dưa vào kho thêm 20–25 phút đến khi dưa mềm, ngấm, nước sệt; nêm lại, rắc tiêu."],
      None, tk("thịt kho dưa cải"),
      [("thit_heo", "Thịt ba chỉ", 500, "g", "n", "chinh"), ("dua_cai_chua", "Dưa cải chua", 500, "g", "n", "chinh"),
       HANH(3), MAM(2.5), DUONG(2), DAU(1), TIEU]),
    M("man", "heo", "tau_hu_ky_cuon_thit", "Tàu hũ ky cuộn thịt", "mon_chinh", "nong", "nhe", "nhieu", "thit_heo", "moi", 50, "vua",
      "Tàu hũ ky cuộn nhân thịt tôm, chiên vàng giòn, chấm tương ớt – món nhà làm bé thích.",
      ["Thịt băm trộn tôm băm, mộc nhĩ, hành tím, nước mắm, tiêu, chút bột năng.",
       "Tàu hũ ky lau ẩm cho mềm, cắt miếng vuông, đặt nhân, cuộn chặt, dán mép bằng chút bột năng pha nước.",
       "Hấp cuộn 10 phút cho nhân chín, để nguội.",
       "Chiên ngập dầu lửa vừa đến khi vàng giòn; cắt khúc, chấm tương ớt hoặc nước mắm chua ngọt."],
      None, tk("tàu hũ ky cuộn thịt"),
      [("thit_heo", "Thịt heo băm", 300, "g", "n", "chinh"), ("tom_the", "Tôm", 150, "g", "n", "phu"),
       ("", "Tàu hũ ky", 3, "lá", "n", "phu"), ("", "Mộc nhĩ", 4, "tai", "n", "phu"), HANH(2), MAM(1),
       ("", "Bột năng", 1, MC, "x", "gia_vi"), ("", "Dầu ăn để chiên", 400, "ml", "x", "gia_vi"), TIEU]),
    M("man", "heo", "ba_chi_xao_kim_chi", "Ba chỉ xào kim chi", "mon_chinh", "nong", "nhe", "vua", "thit_heo|kim_chi", "mua", 20, "de",
      "Ba chỉ thái mỏng xào với kim chi, hành tây – cay chua đậm đà, ăn với cơm trắng (phần bé ít kim chi).",
      ["Ba chỉ thái lát mỏng; kim chi cắt miếng vừa, giữ lại nước kim chi.",
       "Áp chảo ba chỉ cho ra mỡ, hơi xém.",
       "Cho kim chi, hành tây vào xào 3–4 phút, thêm 2 muỗng nước kim chi, chút đường, nước tương.",
       "Đảo đều, rắc hành lá và vừng rang."],
      None, tk("ba chỉ xào kim chi"),
      [("thit_heo", "Thịt ba chỉ", 400, "g", "n", "chinh"), ("kim_chi", "Kim chi cải thảo", 300, "g", "n", "chinh"),
       ("", "Hành tây", 1, "củ", "n", "phu"), ("", "Nước tương", 1, MC, "x", "gia_vi"), DUONG(1), HANH_LA,
       ("", "Vừng rang", 1, MCF, "x", "phu")]),
    M("canh", "heo", "canh_kim_chi_thit_dau_phu", "Canh kim chi thịt ba chỉ đậu phụ", "canh", "nong", "nhe", "vua", "kim_chi|thit_heo|dau_phu", "mua", 35, "de",
      "Kim chi xào với ba chỉ rồi nấu cùng đậu phụ non – canh chua cay ấm bụng kiểu Hàn.",
      ["Ba chỉ thái mỏng; kim chi cắt nhỏ; đậu phụ non cắt miếng; hành tây thái múi.",
       "Áp chảo ba chỉ cho ra mỡ, cho kim chi vào xào 3 phút cho thơm.",
       "Đổ khoảng 1 lít nước cùng nước kim chi, đun sôi 10 phút; thêm hành tây, nấm.",
       "Thả đậu phụ, nêm nước tương, chút đường; sôi lại thì rắc hành lá."],
      None, tk("canh kim chi"),
      [("kim_chi", "Kim chi cải thảo", 300, "g", "n", "chinh"), ("thit_heo", "Thịt ba chỉ", 200, "g", "n", "chinh"),
       ("dau_phu", "Đậu phụ non", 1, "hộp", "n", "chinh"), ("nam", "Nấm kim châm", 150, "g", "n", "phu"),
       ("", "Hành tây", 0.5, "củ", "n", "phu"), ("", "Nước tương", 1, MC, "x", "gia_vi"), DUONG(0.5), HANH_LA]),

    # ---------- Cá biển địa phương, cá nước ngọt ----------
    M("man", "ca", "ca_liet_chien_gion", "Cá liệt chiên giòn", "mon_chinh", "nong", "nhe", "nhieu", "ca_liet", "moi", 30, "de",
      "Cá liệt nhỏ lăn bột chiên giòn rụm, ăn được cả xương – chấm nước mắm tỏi ớt.",
      ["Cá liệt làm sạch, bỏ ruột, rửa nước muối, để thật ráo.",
       "Ướp cá với chút muối, tiêu 10 phút; lăn qua bột chiên giòn.",
       "Chiên ngập dầu lửa vừa đến khi vàng giòn, vớt ra để ráo dầu.",
       "Pha nước mắm tỏi ớt chua ngọt để chấm (phần bé không ớt)."],
      None, tk("cá liệt chiên giòn"),
      [("ca_liet", "Cá liệt", 600, "g", "n", "chinh"), ("", "Bột chiên giòn", 100, "g", "x", "phu"), MUOI, TIEU,
       ("", "Dầu ăn để chiên", 500, "ml", "x", "gia_vi"), TOI(3), OT(1), MAM(2), DUONG(1)]),
    M("man", "ca", "ca_ho_chien_sa", "Cá hố chiên sả", "mon_chinh", "nong", "nhe", "nhieu", "ca_ho", "moi", 35, "de",
      "Cá hố cắt khúc ướp sả nghệ, chiên vàng thơm – thịt trắng ngọt, ít xương dăm.",
      ["Cá hố cạo nhẹ lớp bạc, cắt khúc 6–7 cm, rửa nước muối, để ráo.",
       "Ướp cá với sả băm, chút nghệ, muối, hạt nêm 15 phút.",
       "Chiên cá lửa vừa đến vàng hai mặt, vớt ra.",
       "Phi phần sả còn lại cho vàng giòn, rắc lên cá; chấm nước mắm chanh."],
      None, tk("cá hố chiên sả"),
      [("ca_ho", "Cá hố", 700, "g", "n", "chinh"), SA(4), ("", "Nghệ", 1, "nhánh", "x", "gia_vi"), MUOI, HAT_NEM(1),
       ("", "Dầu ăn để chiên", 300, "ml", "x", "gia_vi")]),
    M("man", "ca", "ca_chuon_kho_man", "Cá chuồn kho mặn", "mon_chinh", "nong", "nhe", "it", "ca_chuon", "moi", 50, "de",
      "Cá chuồn kho nước mắm, tiêu, ớt đến khi thịt săn, nước keo lại – món quen miền biển Ninh Thuận.",
      ["Cá chuồn làm sạch, cắt đôi, rửa nước muối, để ráo.",
       "Ướp cá với nước mắm, đường, tiêu, hành tỏi băm 20 phút.",
       "Xếp cá vào nồi, thêm nước màu và nước xâm xấp, kho lửa nhỏ 30 phút đến khi nước keo lại.",
       "Thêm ớt (phần bé để riêng), rắc tiêu, hành lá."],
      None, tk("cá chuồn kho"),
      [("ca_chuon", "Cá chuồn", 800, "g", "n", "chinh"), MAM(3), DUONG(1.5), HANH(2), TOI(3),
       ("", "Nước màu", 1, MC, "x", "gia_vi"), OT(1), TIEU, HANH_LA]),
    M("man", "ca", "ca_trich_chien_gion", "Cá trích chiên giòn", "mon_chinh", "nong", "nhe", "nhieu", "ca_trich", "moi", 30, "de",
      "Cá trích tươi chiên giòn đến mềm xương, chấm nước mắm me hoặc mắm gừng.",
      ["Cá trích đánh vảy, bỏ ruột, rửa nước muối, để ráo; khứa nhẹ thân.",
       "Ướp chút muối, tiêu, lăn qua bột chiên giòn mỏng.",
       "Chiên ngập dầu lửa vừa 8–10 phút đến khi vàng giòn, xương mềm.",
       "Ăn kèm rau sống, chấm nước mắm me hoặc mắm gừng."],
      None, tk("cá trích chiên giòn"),
      [("ca_trich", "Cá trích", 600, "g", "n", "chinh"), ("", "Bột chiên giòn", 80, "g", "x", "phu"), MUOI, TIEU,
       ("", "Dầu ăn để chiên", 500, "ml", "x", "gia_vi"), MAM(2), DUONG(1), GUNG(1)]),
    M("man", "ca", "ca_duc_chien_gion", "Cá đục chiên giòn", "mon_chinh", "nong", "nhe", "nhieu", "ca_duc", "moi", 30, "de",
      "Cá đục thịt trắng ngọt, chiên giòn chấm mắm tỏi ớt – cá nhỏ dễ ăn, ít xương to.",
      ["Cá đục đánh vảy, bỏ ruột, rửa nước muối, để thật ráo.",
       "Ướp muối, tiêu, chút hạt nêm 10 phút; áo qua lớp bột năng mỏng.",
       "Chiên ngập dầu lửa vừa đến vàng giòn, vớt ra để ráo.",
       "Chấm nước mắm tỏi ớt chua ngọt, ăn kèm rau sống."],
      None, tk("cá đục chiên giòn"),
      [("ca_duc", "Cá đục", 600, "g", "n", "chinh"), ("", "Bột năng", 3, MC, "x", "phu"), MUOI, HAT_NEM(0.5), TIEU,
       ("", "Dầu ăn để chiên", 500, "ml", "x", "gia_vi"), TOI(3), MAM(2), DUONG(1)]),
    M("man", "ca", "ca_bop_kho_tieu", "Cá bớp kho tiêu", "mon_chinh", "nong", "nang", "vua", "ca_bop", "mua", 45, "de",
      "Cá bớp cắt khúc dày kho tiêu – thịt chắc béo, nước kho sệt, cay thơm.",
      ["Cá bớp cắt khúc dày, rửa nước muối gừng, để ráo.",
       "Ướp cá với nước mắm, đường, hạt nêm, hành tỏi băm, nhiều tiêu 20 phút.",
       "Thắng nước màu, xếp cá vào, thêm nước xâm xấp, kho lửa nhỏ 25–30 phút, trở mặt một lần.",
       "Khi nước sệt lại, rắc thêm tiêu, hành lá."],
      None, tk("cá bớp kho tiêu"),
      [("ca_bop", "Cá bớp", 700, "g", "n", "chinh"), MAM(3), DUONG(1.5), HAT_NEM(0.5), HANH(2), TOI(3),
       ("", "Tiêu", 1, MCF, "x", "gia_vi"), GUNG(1), HANH_LA]),
    M("man", "ca", "ca_doi_kho_tieu", "Cá đối kho tiêu", "mon_chinh", "nong", "nang", "vua", "ca_doi", "mua", 50, "de",
      "Cá đối biển kho tiêu với chút mỡ hành – béo, thơm, mùa gió bấc cá đối ngon nhất.",
      ["Cá đối đánh vảy, bỏ ruột, cắt khúc, rửa nước muối, để ráo.",
       "Ướp cá với nước mắm, đường, tiêu, hành băm 20 phút.",
       "Xếp cá vào nồi, thêm nước màu và nước xâm xấp, kho lửa nhỏ 30 phút.",
       "Nước sệt thì rắc tiêu, hành lá; chan cơm nóng."],
      None, tk("cá đối kho tiêu"),
      [("ca_doi", "Cá đối", 800, "g", "n", "chinh"), MAM(3), DUONG(1.5), HANH(2), ("", "Nước màu", 1, MC, "x", "gia_vi"),
       ("", "Tiêu", 1, MCF, "x", "gia_vi"), HANH_LA]),
    M("man", "ca", "ca_ngu_soc_dua_nuong_sa", "Cá ngừ sọc dưa nướng sả", "mon_chinh", "nong", "nhe", "vua", "ca_ngu_soc_dua", "nang", 50, "vua",
      "Cá ngừ sọc dưa nguyên con ướp sả ớt, nướng than hoặc nồi chiên – thịt chắc, thơm, chấm muối ớt xanh.",
      ["Cá ngừ làm sạch, bỏ ruột, khứa thân; rửa nước muối, để ráo.",
       "Ướp cá với sả băm, tỏi, nước mắm, đường, chút dầu ăn 30 phút.",
       "Nướng than hoặc nồi chiên 200°C khoảng 25 phút, lật mặt giữa chừng, quét dầu cho khỏi khô.",
       "Gỡ thịt ăn với rau sống, bánh tráng, chấm muối ớt xanh chanh (phần bé chấm nước mắm ngọt)."],
      None, tk("cá ngừ nướng sả"),
      [("ca_ngu_soc_dua", "Cá ngừ sọc dưa", 800, "g", "n", "chinh"), SA(4), TOI(3), MAM(2), DUONG(1), DAU(2),
       RAU_THOM("Rau sống"), OT(2), ("", "Chanh", 1, "quả", "x", "gia_vi")]),
    M("man", "ca", "ca_chep_om_dua", "Cá chép om dưa", "mon_chinh", "nong", "nang", "vua", "ca_chep|dua_cai_chua", "mua", 60, "vua",
      "Cá chép rán sơ rồi om với dưa cải chua, cà chua, thì là – món om quen thuộc của người Bắc.",
      ["Cá chép đánh vảy, bỏ ruột và đường gân hai bên thân, cắt khúc; rửa nước muối gừng, ướp nước mắm, tiêu 15 phút.",
       "Rán cá sơ cho săn vàng mặt.",
       "Phi hành, xào cà chua cho nhừ, cho dưa vào đảo 3 phút, thêm nước, đun sôi.",
       "Thả cá vào om lửa nhỏ 20 phút, nêm lại; tắt bếp thả thì là, hành lá."],
      None, tk("cá chép om dưa"),
      [("ca_chep", "Cá chép", 1000, "g", "n", "chinh"), ("dua_cai_chua", "Dưa cải chua", 400, "g", "n", "chinh"),
       ("ca_chua", "Cà chua", 3, "quả", "n", "phu"), GUNG(1), HANH(2), MAM(2), DUONG(0.5), DAU(3),
       RAU_THOM("Thì là, hành lá")]),
    M("canh", "ca", "canh_dua_chua_nau_ca_loc", "Canh dưa chua nấu cá lóc", "canh", "mat", "nhe", "it", "ca_loc|dua_cai_chua", "nang", 35, "de",
      "Cá lóc rán sơ nấu với dưa cải chua, cà chua – canh chua nhẹ, ngọt cá, ăn ngày nắng.",
      ["Cá lóc làm sạch nhớt, cắt khúc, ướp chút nước mắm, tiêu.",
       "Rán cá sơ cho săn; dưa cải chua vắt bớt nước, cắt khúc; cà chua bổ múi.",
       "Phi hành, xào cà chua và dưa 3 phút, đổ khoảng 1,2 lít nước, đun sôi.",
       "Thả cá vào nấu 10 phút, nêm nước mắm, chút đường; tắt bếp thả hành lá, thì là."],
      None, tk("canh dưa chua cá lóc"),
      [("ca_loc", "Cá lóc", 500, "g", "n", "chinh"), ("dua_cai_chua", "Dưa cải chua", 300, "g", "n", "chinh"),
       ("ca_chua", "Cà chua", 2, "quả", "n", "phu"), HANH(2), MAM(1.5), DUONG(0.5), DAU(2), RAU_THOM("Thì là, hành lá")]),

    # ---------- Hải sản ----------
    M("man", "hai_san", "tom_chien_xu", "Tôm chiên xù", "mon_chinh", "nong", "nhe", "nhieu", "tom_the", "moi", 35, "de",
      "Tôm bóc vỏ chừa đuôi, lăn trứng và bột chiên xù, chiên vàng giòn – chấm tương cà, bé rất thích.",
      ["Tôm bóc vỏ chừa đuôi, rút chỉ, khứa bụng cho tôm thẳng; ướp chút muối, tiêu 10 phút.",
       "Lăn tôm lần lượt qua bột mì, trứng đánh tan, bột chiên xù; ấn nhẹ cho bột bám.",
       "Chiên ngập dầu lửa vừa đến khi vàng đều, vớt ra để ráo.",
       "Ăn kèm tương cà, mayonnaise và xà lách."],
      None, tk("tôm chiên xù"),
      [("tom_the", "Tôm thẻ", 500, "g", "n", "chinh"), ("trung", "Trứng gà", 2, "quả", "x", "phu"),
       ("", "Bột chiên xù", 150, "g", "x", "phu"), ("", "Bột mì", 50, "g", "x", "phu"), MUOI, TIEU,
       ("", "Dầu ăn để chiên", 500, "ml", "x", "gia_vi")]),
    M("man", "hai_san", "muc_chien_gion", "Mực chiên giòn", "mon_chinh", "nong", "nhe", "nhieu", "muc_tuoi", "moi", 30, "de",
      "Mực ống cắt khoanh, áo bột chiên giòn – giòn ngoài, mềm trong, chấm tương ớt.",
      ["Mực làm sạch, lột da, cắt khoanh; thấm thật khô.",
       "Ướp mực chút muối, tiêu, tỏi băm 10 phút.",
       "Lăn mực qua bột chiên giòn trộn chút bột năng.",
       "Chiên dầu thật nóng 2–3 phút đến khi vàng giòn (chiên lâu mực sẽ dai); ăn ngay khi nóng."],
      None, tk("mực chiên giòn"),
      [("muc_tuoi", "Mực ống", 600, "g", "n", "chinh"), ("", "Bột chiên giòn", 100, "g", "x", "phu"),
       ("", "Bột năng", 2, MC, "x", "phu"), TOI(3), MUOI, TIEU, ("", "Dầu ăn để chiên", 500, "ml", "x", "gia_vi")]),
    M("man", "hai_san", "muc_xao_can_toi", "Mực xào cần tỏi", "mon_chinh", "am", "nhe", "vua", "muc_tuoi", "moi", 25, "de",
      "Mực khía vảy rồng xào nhanh với cần tây, tỏi, cà chua – giòn ngọt, không dai.",
      ["Mực làm sạch, khía vảy rồng mặt trong, cắt miếng vừa ăn; chần nhanh nước sôi 10 giây cho mực cuộn lại.",
       "Cần tây cắt khúc; cà chua bổ múi; hành tây thái múi cau.",
       "Phi tỏi, xào cà chua, hành tây 1 phút, cho cần tây vào đảo.",
       "Cho mực vào đảo lửa lớn 1–2 phút, nêm dầu hào, nước mắm, hạt nêm, tiêu rồi tắt bếp."],
      None, tk("mực xào cần tỏi"),
      [("muc_tuoi", "Mực ống", 500, "g", "n", "chinh"), ("can_tay", "Cần tây", 200, "g", "n", "phu"),
       ("ca_chua", "Cà chua", 1, "quả", "n", "phu"), ("", "Hành tây", 0.5, "củ", "n", "phu"), TOI(5), DAU_HAO(1),
       MAM(0.5), HAT_NEM(0.5), DAU(2), TIEU]),
    M("man", "hai_san", "hau_nuong_mo_hanh", "Hàu nướng mỡ hành", "mon_chinh", "nong", "nhe", "vua", "hau", "moi", 30, "de",
      "Hàu tươi nướng với mỡ hành, đậu phộng rang – béo ngọt, nướng chín kỹ cho cả nhà.",
      ["Hàu cọ sạch vỏ, tách bỏ một mảnh vỏ, giữ lại phần thịt và nước trong vỏ.",
       "Làm mỡ hành: phi hành lá thái nhỏ với dầu ăn hoặc mỡ, thêm chút hạt nêm.",
       "Xếp hàu lên vỉ hoặc khay, nướng 5–7 phút đến khi hàu chín, nước sôi lăn tăn.",
       "Rưới mỡ hành, rắc đậu phộng rang, hành phi; ăn với muối ớt xanh chanh."],
      None, tk("hàu nướng mỡ hành"),
      [("hau", "Hàu", 24, "con", "n", "chinh"), HANH_LA, ("dau_phong", "Đậu phộng rang", 2, MC, "x", "phu"),
       DAU(4), HAT_NEM(0.5), OT(2), ("", "Chanh", 1, "quả", "x", "gia_vi"), MUOI]),
    M("man", "hai_san", "ngheu_xao_sa_ot", "Nghêu xào sả ớt", "mon_chinh", "nong", "nhe", "vua", "ngheu", "mua", 30, "de",
      "Nghêu luộc vừa há miệng rồi xào sả ớt, rau răm – cay thơm, chấm bánh mì nước sốt.",
      ["Ngâm nghêu nước muối pha ớt 2 tiếng cho nhả cát, rửa sạch.",
       "Luộc nghêu với sả đập dập đến khi vừa há miệng, vớt ra; bỏ con không mở.",
       "Phi tỏi, sả băm cho thơm, thêm chút sa tế (phần bé để riêng), nước mắm, đường.",
       "Cho nghêu vào đảo nhanh cho thấm, rắc rau răm, hành lá."],
      None, tk("nghêu xào sả ớt"),
      [("ngheu", "Nghêu", 1500, "g", "n", "chinh"), SA(4), TOI(4), OT(2), ("", "Sa tế", 1, MC, "x", "gia_vi"),
       MAM(1), DUONG(1), DAU(2), RAU_THOM("Rau răm"), HANH_LA]),

    # ---------- Trứng ----------
    M("man", "trung_dau", "trung_xao_ca_chua", "Trứng xào cà chua", "mon_chinh", "am", "nhe", "vua", "trung|ca_chua", "moi", 15, "de",
      "Trứng đánh tan xào với cà chua chín mềm, hành lá – nhanh, mềm, bé ăn cơm rất hợp.",
      ["Trứng đánh tan với chút nước mắm; cà chua bổ múi cau.",
       "Đổ trứng vào chảo nóng có dầu, đảo nhẹ đến khi vừa đông thì múc ra.",
       "Phi hành, xào cà chua đến mềm, ra nước, nêm chút đường, nước mắm.",
       "Cho trứng vào đảo nhẹ cho quyện, rắc hành lá, tiêu."],
      None, tk("trứng xào cà chua"),
      [("trung", "Trứng gà", 6, "quả", "n", "chinh"), ("ca_chua", "Cà chua", 3, "quả", "n", "chinh"),
       HANH(1), MAM(1), DUONG(0.5), DAU(2), HANH_LA, TIEU]),

    # ---------- Một tô, lẩu với kim chi ----------
    M("mot_to", "trung_dau", "com_chien_kim_chi", "Cơm chiên kim chi", "mon_chinh", "nong", "nhe", "vua", "kim_chi", "moi", 20, "de",
      "Cơm nguội chiên với kim chi, ba chỉ, trứng ốp la lên trên – bữa nhanh gọn, chua cay vừa.",
      ["Kim chi cắt nhỏ; ba chỉ thái hạt lựu; hành tây băm.",
       "Áp chảo ba chỉ cho ra mỡ, thêm hành tây, kim chi xào 3 phút.",
       "Cho cơm vào đảo tơi, thêm 2 muỗng nước kim chi, nước tương, chút đường; đảo đến khi cơm săn.",
       "Ốp la trứng đặt lên trên mỗi đĩa, rắc hành lá, vừng."],
      None, tk("cơm chiên kim chi"),
      [("kim_chi", "Kim chi cải thảo", 250, "g", "n", "chinh"), ("", "Cơm nguội", 800, "g", "n", "phu"),
       ("thit_heo", "Thịt ba chỉ", 150, "g", "n", "phu"), ("trung", "Trứng gà", 4, "quả", "n", "phu"),
       ("", "Hành tây", 0.5, "củ", "n", "phu"), ("", "Nước tương", 1, MC, "x", "gia_vi"), DUONG(0.5), DAU(2), HANH_LA]),
    M("lau", "hai_san", "lau_kim_chi_hai_san", "Lẩu kim chi hải sản", "lau", "nong", "nang", "vua", "kim_chi|tom_the|muc_tuoi", "mua", 50, "vua",
      "Nước lẩu kim chi chua cay nhúng tôm, mực, nghêu, nấm, đậu phụ – bữa chính ngày mưa.",
      ["Ninh xương gà hoặc xương heo 30 phút làm nước dùng.",
       "Xào kim chi với chút ba chỉ cho thơm, đổ vào nồi nước dùng cùng nước kim chi, nêm nước tương, đường, chút ớt bột Hàn (phần bé múc nước dùng trước khi cho ớt).",
       "Tôm cắt râu; mực cắt khoanh; nghêu ngâm nhả cát; đậu phụ, nấm, cải thảo, mì Hàn xếp đĩa.",
       "Nhúng hải sản, rau, nấm, đậu phụ; ăn kèm mì hoặc bún."],
      None, tk("lẩu kim chi hải sản"),
      [("kim_chi", "Kim chi cải thảo", 400, "g", "n", "chinh"), ("tom_the", "Tôm", 400, "g", "n", "chinh"),
       ("muc_tuoi", "Mực", 300, "g", "n", "chinh"), ("ngheu", "Nghêu", 500, "g", "n", "phu"),
       ("thit_heo", "Xương heo", 500, "g", "x", "phu"), ("dau_phu", "Đậu phụ", 2, "bìa", "n", "phu"),
       ("nam", "Nấm các loại", 300, "g", "n", "phu"), ("cai_thao", "Cải thảo", 300, "g", "n", "phu"),
       ("bun", "Mì Hàn hoặc bún", 400, "g", "n", "phu"), ("", "Nước tương", 2, MC, "x", "gia_vi"), DUONG(1),
       ("", "Ớt bột Hàn", 1, MC, "x", "gia_vi")]),

    # ---------- Bữa nướng (bữa chính một món, như lẩu) ----------
    M("nuong", "heo", "nuong_kieu_han_kim_chi", "Nướng ba chỉ, bò Mỹ kiểu Hàn ăn kèm kim chi", "nuong", "nong", "nang", "vua",
      "thit_heo|thit_bo|kim_chi", "moi", 60, "de",
      "Ba chỉ heo và bò Mỹ thái mỏng nướng bếp điện tại bàn, cuốn xà lách với kim chi, tỏi, sốt tương – bữa chính vui như lẩu.",
      ["Ba chỉ thái lát dày 0,5 cm; ướp bò Mỹ với nước tương, đường, dầu mè, tỏi băm, tiêu 30 phút (ba chỉ để nguyên vị hoặc ướp chút muối tiêu).",
       "Pha sốt chấm: tương đậu Hàn, chút tương ớt, dầu mè, tỏi băm, vừng (phần bé dùng sốt mè hoặc nước tương ngọt).",
       "Xà lách, lá tía tô rửa sạch; kim chi, tỏi lát, nấm, hành tây, ớt chuông xếp đĩa.",
       "Nướng ba chỉ trước cho ra mỡ, nướng kèm kim chi và nấm trong mỡ; bò Mỹ nướng nhanh 20–30 giây mỗi mặt.",
       "Cuốn thịt với xà lách, kim chi, tỏi, chấm sốt; ăn kèm cơm trắng."],
      None, tk("thịt nướng Hàn Quốc kim chi"),
      [("thit_heo", "Thịt ba chỉ", 500, "g", "n", "chinh"), ("thit_bo", "Ba chỉ bò Mỹ", 400, "g", "n", "chinh"),
       ("kim_chi", "Kim chi cải thảo", 300, "g", "n", "chinh"), ("xa_lach", "Xà lách", 300, "g", "n", "phu"),
       ("nam", "Nấm đùi gà, nấm kim châm", 300, "g", "n", "phu"), ("", "Hành tây", 1, "củ", "n", "phu"),
       ("", "Tương đậu Hàn (ssamjang)", 3, MC, "x", "gia_vi"), ("", "Nước tương", 2, MC, "x", "gia_vi"),
       ("", "Dầu mè", 1, MC, "x", "gia_vi"), TOI(8), DUONG(1), RAU_THOM("Lá tía tô")]),
    M("nuong", "heo", "nuong_thap_cam_kieu_viet", "Nướng thập cẩm kiểu Việt", "nuong", "nong", "nang", "vua",
      "thit_heo|thit_bo", "moi", 70, "vua",
      "Ba chỉ ướp sả, bò cuộn lá lốt, đậu bắp, cà tím, bắp nướng – cuốn bánh tráng rau sống, chấm mắm nêm hoặc muối ớt.",
      ["Ba chỉ thái lát, ướp sả băm, tỏi, nước mắm, đường, chút dầu hào 30 phút.",
       "Bò thái mỏng ướp tỏi, tiêu, dầu hào, cuộn trong lá lốt.",
       "Đậu bắp, cà tím, bắp, nấm cắt miếng, quét mỡ hành.",
       "Nướng trên bếp than hoặc bếp điện; ba chỉ và rau củ trước, bò lá lốt sau (chín nhanh).",
       "Cuốn bánh tráng với rau sống, dưa leo, bún; chấm mắm nêm pha dứa hoặc muối ớt chanh (phần bé chấm nước mắm ngọt)."],
      None, tk("nướng thập cẩm"),
      [("thit_heo", "Thịt ba chỉ", 500, "g", "n", "chinh"), ("thit_bo", "Thịt bò", 300, "g", "n", "chinh"),
       ("la_lot", "Lá lốt", 1, "bó", "x", "phu"), ("dau_bap", "Đậu bắp", 200, "g", "n", "phu"), ("ca_tim", "Cà tím", 2, "quả", "n", "phu"),
       ("ngo", "Bắp", 2, "trái", "n", "phu"), ("banh_trang", "Bánh tráng", 1, "xấp", "n", "phu"), ("bun", "Bún", 500, "g", "n", "phu"),
       RAU_THOM("Rau sống các loại"), SA(3), TOI(6), MAM(2), DUONG(1.5), DAU_HAO(1), ("", "Mắm nêm", 3, MC, "x", "gia_vi"), HANH_LA]),
    M("nuong", "hai_san", "hai_san_nuong_mo_hanh", "Hải sản nướng mỡ hành", "nuong", "nong", "nang", "vua",
      "tom_the|muc_tuoi|hau", "moi", 60, "vua",
      "Tôm, mực, hàu, sò điệp nướng mỡ hành – hải sản Phan Rang, chấm muối ớt xanh, bữa chính một món.",
      ["Tôm cắt râu, rút chỉ; mực làm sạch, khứa; hàu, sò điệp cọ sạch, tách một mảnh vỏ.",
       "Ướp tôm, mực với chút muối, tiêu, sả băm, dầu ăn 15 phút.",
       "Làm mỡ hành: phi hành lá với dầu, thêm chút hạt nêm; rang đậu phộng giã dập.",
       "Nướng tôm, mực trên than hoặc bếp điện; hàu, sò điệp nướng đến khi sôi nước thì rưới mỡ hành, đậu phộng.",
       "Chấm muối ớt xanh chanh; ăn kèm bánh mì hoặc cơm, rau sống."],
      None, tk("hải sản nướng mỡ hành"),
      [("tom_the", "Tôm", 500, "g", "n", "chinh"), ("muc_tuoi", "Mực", 400, "g", "n", "chinh"),
       ("hau", "Hàu", 12, "con", "n", "chinh"), ("so_diep", "Sò điệp", 12, "con", "n", "phu"), SA(2), HANH_LA,
       ("dau_phong", "Đậu phộng rang", 3, MC, "x", "phu"), DAU(4), HAT_NEM(0.5), MUOI, TIEU, OT(3),
       ("", "Chanh", 2, "quả", "x", "gia_vi"), RAU_THOM("Rau sống")]),
]
