"""Lô 4 – món chủ nhà chọn kèm link công thức Cookpad cụ thể (08/10/2026).

Cùng quy ước với lo1_bac.py: định lượng quy về 4 người, giữ đúng nguyên liệu của công thức gốc,
cách làm viết lại bằng lời của Cá Chef, cột nguon là link công thức chủ nhà chọn. Tất cả "chua_nau_thu".
KHUNG: (mã món, vai mâm, nhóm đạm). Mã trùng món đã có thì món đó đổi sang công thức này:
- món trong khung_mon.csv (Cookpad) – xuat_csv.py thay dòng khung;
- món trên Sheet (DE_SHEET) – app/server.py lấy bản này đè lên bản Sheet khi build.
"""
from urllib.parse import quote

from lo1_bac import (DAU, DUONG, HANH, HANH_LA, HAT_NEM, MAM, MC, MCF, Q, R, TIEU, TOI)

CP = "https://cookpad.com/vn/cong-thuc/"
TK = "https://cookpad.com/vn/tim-kiem/"
tk = lambda s: TK + quote(s)
SA = lambda n: ("sa_ot", "Sả", n, "cây", "x", "gia_vi")
OT = lambda n: ("sa_ot", "Ớt", n, "quả", "x", "gia_vi")
GUNG = lambda n: ("sa_ot", "Gừng", n, "nhánh", "x", "gia_vi")
RAU_THOM = lambda ten: ("rau_thom", ten, 1, "bó", "x", "phu")
MUOI = ("muoi_ca_na", "Muối", None, "vừa đủ", "x", "gia_vi")

# Nguyên liệu trước đây chưa có mã (dòng định lượng chỉ ghi tên) – app/server.py gắn mã theo data/de_xuat/gan_ma.csv.
# (mã, tên, nhóm, vùng, lịch 12 tháng, nơi mua, tin cậy, ghi chú)
NGUYEN_LIEU = [
    ("ca_dieu_hong", "Cá diêu hồng", "thủy sản", "chung", Q, "chợ/GO!", "C", "Cá nuôi nước ngọt, có quanh năm"),
    ("ca_ro_phi", "Cá rô phi", "thủy sản", "chung", Q, "chợ/GO!", "C", "Cá nuôi nước ngọt, có quanh năm"),
    ("ca_hoi", "Cá hồi", "hải sản", "nhập khẩu", Q, "GO!/siêu thị", "C", "Cá hồi nhập (Na Uy) cắt khúc, phi lê – mua ở siêu thị"),
    ("cha_ca", "Chả cá", "hải sản", "chung", Q, "chợ/GO!", "C", "Chả cá Nha Trang, Phan Rang làm sẵn"),
    ("tom_kho", "Tôm khô", "hàng khô", "chung", Q, "chợ/GO!", "C", "Hàng khô, có quanh năm"),
    ("gio_song", "Giò sống", "thịt", "chung", Q, "chợ", "C", "Thịt heo quết nhuyễn làm sẵn ở hàng giò chả"),
    ("lap_xuong", "Lạp xưởng", "khác", "chung", Q, "chợ/GO!", "C", "Đồ khô đóng gói, có quanh năm"),
    ("he", "Hẹ", "rau củ", "chung", Q, "chợ", "C", "Rau gia vị có quanh năm"),
    ("la_chanh", "Lá chanh", "rau củ", "chung", Q, "chợ", "C", "Có quanh năm"),
    ("ot_chuong", "Ớt chuông", "rau củ", "Đà Lạt", Q, "chợ/GO!", "C", "Rau Đà Lạt, có quanh năm"),
    ("doc_mung", "Dọc mùng (bạc hà)", "rau củ", "chung", Q, "chợ", "C", "Có quanh năm"),
    ("cu_dau", "Củ đậu (củ sắn)", "rau củ", "chung", Q, "chợ", "C", "Có quanh năm, nhiều nhất mùa khô"),
    ("toi_tay", "Tỏi tây", "rau củ", "Đà Lạt", Q, "chợ/GO!", "C", "Rau Đà Lạt, có quanh năm"),
    ("cu_den", "Củ dền", "rau củ", "Đà Lạt", Q, "chợ/GO!", "C", "Rau Đà Lạt, có quanh năm"),
    ("mang_chua", "Măng chua", "khác", "chung", Q, "chợ", "C", "Măng muối chua làm sẵn, có quanh năm"),
    ("ky_tu", "Kỷ tử", "hàng khô", "chung", Q, "chợ/tiệm thuốc bắc", "C", "Hàng khô, có quanh năm"),
    ("sua_tuoi", "Sữa tươi", "khác", "chung", Q, "GO!/tạp hóa", "A", "Có quanh năm"),
    ("sua_dac", "Sữa đặc", "hàng khô", "chung", Q, "GO!/tạp hóa", "A", "Hộp, có quanh năm"),
    ("sua_chua", "Sữa chua", "khác", "chung", Q, "GO!/tạp hóa", "A", "Có quanh năm"),
]
DE_SHEET = {"goi_cuon"}  # món trên Sheet đổi sang công thức chủ nhà chọn
KHUNG = []


def M(vai, dam, *a, **kw):
    r = R(*a, **kw)
    KHUNG.append((r["ma"], vai, dam))
    return r


RECIPES = [
    # ---------- Gà ----------
    M("man", "ga", "ga_ham_nam", "Gà hầm nấm", "mon_chinh", "nong", "nang", "it", "ga_ta", "mua", 90, "de",
      "Gà ri nguyên con hầm với hạt sen, nấm đông cô, cà rốt, kỷ tử – nước trong ngọt, thịt mềm, cả nhà đều ăn được.",
      ["Gừng đập dập; nấm đông cô ngâm nở, thái miếng (chân nấm để nguyên cho ngọt nước); cà rốt bổ dọc rồi thái khoanh; hành tây cắt đôi; hành hoa thái ngắn.",
       "Rải hạt sen, gừng xuống đáy nồi, đặt gà lên trên, xếp cà rốt và nấm xung quanh, nhét hành tây vào bụng gà.",
       "Đổ nước lạnh ngập gà, đun lửa lớn đến sôi rồi hớt sạch bọt; thả kỷ tử, tiêu hột đập dập, nêm nhẹ.",
       "Hạ lửa nhỏ, đậy vung hầm đến khi hạt sen bở và gà mềm (khoảng 60 phút); nêm lại vừa miệng.",
       "Cho hành hoa vào tô, múc cà rốt, hạt sen, đặt gà vào giữa, xếp nấm xung quanh rồi chan nước dùng."],
      None, CP + "7232286",
      [("ga_ta", "Gà ri", 1000, "g", "n", "chinh"), ("hat_sen", "Hạt sen khô", 100, "g", "n", "phu"),
       ("ca_rot", "Cà rốt", 1, "củ", "n", "phu"), ("nam", "Nấm đông cô", 4, "tai", "n", "phu"),
       ("", "Kỷ tử", 1, MC, "x", "phu"), ("", "Hành tây", 1, "củ", "x", "phu"), GUNG(1),
       ("", "Tiêu hột", 10, "hạt", "x", "gia_vi"), HANH_LA, MUOI, HAT_NEM(1)]),
    M("lau", "ga", "ga_ham_sa", "Gà hầm sả", "lau", "nong", "nang", "vua", "ga_ta", "mua", 90, "vua",
      "Gà ướp sả ớt xào săn rồi hầm nước dừa với củ cải, cà rốt – ăn với bún và mồng tơi trụng như lẩu.",
      ["Gà chặt miếng vừa ăn, ướp với sả băm, hành tỏi băm, đường, nước mắm, hạt nêm, tương ớt, chút sa tế, tiêu và 2 muỗng dầu ăn khoảng 30 phút (phần bé bớt tương ớt, sa tế).",
       "Củ cải, cà rốt gọt vỏ thái khoanh; ngọn sả thái lát, gốc sả đập dập; ớt sừng băm; mồng tơi nhặt rửa sạch.",
       "Phi thơm sả lát, ớt, hành tỏi băm, cho gà vào xào đến khi săn.",
       "Đổ nước dừa ngập gà (thiếu thì thêm nước lọc), sôi thì hạ lửa, đậy nắp hầm, thỉnh thoảng hớt bọt; gà gần mềm thì cho củ cải, rồi cà rốt.",
       "Gà mềm, rau củ chín thì thả gốc sả đập dập, nêm lại, rắc hành lá, tiêu rồi tắt bếp.",
       "Khi ăn đun sôi lại; xếp bún vào tô, trụng mồng tơi trong nồi nước dùng, gắp gà, củ cải, cà rốt lên trên và chan nước."],
      None, CP + "24018723",
      [("ga_ta", "Gà", 800, "g", "n", "chinh"), ("dua", "Dừa xiêm (lấy nước)", 2, "trái", "x", "phu"),
       ("mong_toi", "Mồng tơi", 300, "g", "n", "phu"), ("cu_cai", "Củ cải trắng", 1, "củ", "n", "phu"),
       ("ca_rot", "Cà rốt", 1, "củ", "n", "phu"), ("bun", "Bún tươi", 800, "g", "n", "phu"), SA(3), OT(1),
       HANH(1), TOI(3), ("", "Tương ớt", 1, MC, "x", "gia_vi"), ("", "Sa tế", 0.5, MC, "x", "gia_vi"),
       MAM(2), DUONG(2), HAT_NEM(1), DAU(4), TIEU, HANH_LA]),
    M("man", "ga", "ga_hap_mam_nhi", "Gà hấp mắm nhĩ", "mon_chinh", "nong", "nhe", "vua", "ga_ta", "moi", 70, "vua",
      "Gà ta thoa sốt mắm nhĩ, nhồi gừng hành tỏi tiêu xanh rồi hấp lửa nhỏ – thịt thấm mắm, chấm muối ớt xanh.",
      ["Gà làm sạch, rửa nước muối, để ráo; lá gừng hoặc lá sả rửa sạch; rau ăn kèm ngâm nước muối loãng.",
       "Gừng, hành, tỏi, tiêu xanh đập dập; phi với dầu điều cho thơm, thêm tương ớt, đường, tiêu, nước mắm nhĩ và chút nước, khuấy tan rồi đun sôi, để nguội.",
       "Giã muối hột, tiêu đen, ớt xanh, chút đường, thêm nước cốt chanh làm muối ớt xanh (phần bé chấm nước mắm ngọt).",
       "Nhồi phần gừng, hành, tỏi, tiêu xanh vào bụng gà, thoa sốt khắp mình gà; lót lá gừng, lá sả dưới đáy nồi, đặt gà lên, đậy kín, hấp lửa nhỏ khoảng 40 phút.",
       "Gà hơi nguội thì chặt hoặc xé miếng, ăn với dưa leo, cà chua, rau răm, chấm muối ớt xanh."],
      None, CP + "9552340",
      [("ga_ta", "Gà ta", 1200, "g", "n", "chinh"), ("", "Nước mắm nhĩ", 70, "g", "x", "gia_vi"),
       ("", "Dầu màu điều", 2, MC, "x", "gia_vi"), GUNG(1), HANH(3), TOI(6), ("tieu_moi", "Tiêu xanh", 15, "g", "x", "gia_vi"),
       ("", "Tương ớt", 2, MC, "x", "gia_vi"), DUONG(3), ("", "Lá gừng, lá sả", 1, "nắm", "x", "phu"),
       ("dua_leo", "Dưa leo", 2, "quả", "n", "phu"), ("ca_chua", "Cà chua", 2, "quả", "n", "phu"), RAU_THOM("Rau răm"),
       ("muoi_ca_na", "Muối hột", 1, MC, "x", "gia_vi"), OT(3), ("", "Chanh", 1, "quả", "x", "gia_vi")]),
    M("canh", "ga", "canh_ga_rau_cu", "Canh gà rau củ", "canh", "am", "nhe", "it", "ga_ta", "moi", 45, "de",
      "Cánh gà xào săn rồi hầm với bắp, cà rốt, khoai tây, củ dền, su su bao tử – canh ngọt, nhiều màu, bé thích.",
      ["Cánh gà chần qua nước sôi cho sạch, chặt khúc, ướp hạt nêm, nước mắm, đầu hành trắng băm 15 phút.",
       "Bắp cắt khúc; cà rốt và củ dền gọt vỏ, tỉa hoa hoặc cắt miếng; khoai tây cắt miếng vừa; su su bao tử rửa sạch.",
       "Phi thơm đầu hành, cho cánh gà vào đảo săn, đổ khoảng 1,5 lít nước, cho bắp, cà rốt, củ dền vào hầm 15 phút.",
       "Thêm khoai tây và su su nấu đến khi chín mềm, nêm hạt nêm, nước mắm vừa ăn, rắc hành ngò."],
      None, CP + "14049848",
      [("ga_ta", "Cánh gà", 6, "cái", "n", "chinh"), ("ngo", "Bắp Mỹ", 1, "trái", "n", "phu"),
       ("ca_rot", "Cà rốt", 1, "củ", "n", "phu"), ("khoai_tay", "Khoai tây", 3, "củ", "n", "phu"),
       ("", "Củ dền (củ cải đường)", 2, "củ", "n", "phu"), ("su_su", "Su su bao tử", 6, "quả", "n", "phu"),
       RAU_THOM("Hành, ngò"), HAT_NEM(1), MAM(1), DAU(1)]),
    M("mot_to", "ga", "mien_xao_long_ga", "Miến xào lòng gà", "mon_chinh", "nong", "nhe", "vua", "ga_ta", "moi", 35, "de",
      "Miến dong xào với mề, gan, tim gà, giá, mộc nhĩ, cà rốt – món nhà kiểu Bắc, tận dụng bộ lòng khi mua gà.",
      ["Lòng gà (mề bóc màng vàng, gan, tim) rửa muối và chút rượu, thái lát mỏng; ướp nước mắm, tiêu, hành băm 15 phút.",
       "Miến ngâm nước ấm cho mềm, cắt đoạn; mộc nhĩ ngâm, thái sợi; cà rốt thái sợi; hành tây thái múi; giá rửa sạch.",
       "Phi hành tỏi, xào lòng gà lửa lớn đến chín tới thì múc ra.",
       "Xào cà rốt, mộc nhĩ, hành tây, cho miến vào đảo cùng chút nước tương, nước mắm cho miến mềm và thấm; cho lòng gà, giá vào đảo nhanh, rắc hành lá, rau mùi, tiêu."],
      None, tk("miến xào lòng gà"),
      [("ga_ta", "Lòng gà (mề, gan, tim)", 400, "g", "n", "chinh"), ("bun", "Miến dong", 250, "g", "n", "phu"),
       ("gia_do", "Giá đỗ", 150, "g", "n", "phu"), ("", "Mộc nhĩ", 5, "tai", "n", "phu"), ("ca_rot", "Cà rốt", 1, "củ", "n", "phu"),
       ("", "Hành tây", 1, "củ", "n", "phu"), TOI(4), HANH(2), MAM(1.5), ("", "Nước tương", 1, MC, "x", "gia_vi"), DAU(3),
       HANH_LA, RAU_THOM("Rau mùi"), TIEU]),

    # ---------- Tôm ----------
    M("man", "hai_san", "tom_thit_kho_thom", "Tôm thịt kho thơm", "mon_chinh", "nong", "nhe", "vua", "tom_the|thom", "moi", 35, "de",
      "Tôm và ba rọi kho với thơm, nước mắm tỏi ớt – chua ngọt, sệt bóng, rất đưa cơm.",
      ["Tôm cắt râu, rút chỉ; ba rọi thái miếng mỏng; thơm cắt lát.",
       "Phi thơm tỏi băm, cho tôm vào xào săn rồi cho thịt vào đảo cùng.",
       "Cho thơm vào xào chung, thêm nước mắm tỏi ớt, tương ớt (phần bé múc ra trước khi cho ớt), chút nước; nêm hơi nhạt vì tôm sẽ kho sắc lại.",
       "Kho lửa nhỏ đến khi tôm thấm và nước cạn sệt; rắc tiêu, tỏi phi, hành lá."],
      None, CP + "26500239",
      [("tom_the", "Tôm", 600, "g", "n", "chinh"), ("thit_heo", "Thịt ba rọi", 200, "g", "n", "phu"),
       ("thom", "Thơm (dứa)", 0.5, "trái", "n", "chinh"), TOI(4), ("", "Nước mắm tỏi ớt", 0.6, "chén", "x", "gia_vi"),
       ("", "Tương ớt", 1, MC, "x", "gia_vi"), TIEU, HANH_LA, ("", "Tỏi phi", 1, MC, "x", "phu")]),
    M("man", "hai_san", "tom_rang_gion", "Tôm rang giòn", "mon_chinh", "nong", "nhe", "vua", "tom_the", "moi", 30, "de",
      "Tôm nhỏ (tép) rang khô với lá chanh rồi rang lại với hành khô hai lửa – giòn thơm, ăn được cả vỏ, nhiều canxi cho bé.",
      ["Tôm nhỏ nhặt rửa sạch, để ráo (tôm to thì cắt đầu, chân, bỏ phần bẩn ở đầu).",
       "Ướp tôm với chút bột canh, đường 10–15 phút.",
       "Cho tôm và lá chanh vào chảo không dầu, đảo lửa nhỏ đến khi nước tôm tiết ra cạn hẳn, tôm se khô; nhặt bỏ lá chanh.",
       "Chảo khác phi hành khô vừa thơm (đừng để vàng quá kẻo cháy), cho tôm vào rang lửa nhỏ 5–7 phút rồi tắt bếp, để nguyên chảo cho hơi nóng làm tôm giòn.",
       "Trước khi ăn thêm 1 thìa dầu, rang lại lửa nhỏ đến khi tôm vàng giòn, rắc tiêu."],
      None, CP + "470734",
      [("tom_the", "Tôm nhỏ (tép)", 400, "g", "n", "chinh"), ("", "Lá chanh", 6, "lá", "x", "phu"), HANH(2),
       ("", "Bột canh", 0.5, MCF, "x", "gia_vi"), DUONG(0.3), DAU(3), TIEU]),
    M("mot_to", "hai_san", "sup_tom_ngo_nam", "Soup tôm ngô nấm", "mon_chinh", "am", "nhe", "it", "tom_the|ngo", "moi", 60, "vua",
      "Nước dùng đầu vỏ tôm và ngô ngọt, tôm giã xào nấm, trứng cút, vân trứng – soup sánh nhẹ, bé rất thích.",
      ["Tôm bóc vỏ, giữ đầu và vỏ nấu nước dùng; sả thái vát; ngô bẻ đôi; cà rốt thái hạt lựu; nấm rơm bổ đôi; nấm đông cô thái chỉ; trứng cút luộc bóc vỏ.",
       "Đun nước với sả, sôi thì cho đầu vỏ tôm nấu lửa nhỏ, nêm chút nước mắm, đường, hạt nêm; 15 phút sau cho ngô vào nấu tiếp; ngô chín vớt ra tách hạt, lọc bỏ bã nước dùng.",
       "Tôm nõn giã nhuyễn với hành khô; xào nấm rơm, nấm đông cô, cà rốt với chút nước mắm, tiêu rồi cho tôm vào xào chín tới.",
       "Cho phần xào và hạt ngô vào nồi nước dùng, đun sôi nhỏ lửa, hớt bọt cho trong, nêm vừa ăn, nấu 10 phút.",
       "Hòa bột năng với nước, đổ từ từ vừa khuấy một chiều đến khi soup sánh; đổ lòng trắng trứng từ từ, khuấy nhanh tạo vân; thả trứng cút, đun thêm 1 phút.",
       "Múc ra bát, rắc tiêu, rau mùi."],
      None, CP + "5714681",
      [("tom_the", "Tôm biển", 500, "g", "n", "chinh"), ("ngo", "Bắp ngô ngọt", 1, "bắp", "n", "chinh"),
       ("nam", "Nấm rơm", 100, "g", "n", "phu"), ("nam", "Nấm đông cô", 10, "tai", "n", "phu"),
       ("ca_rot", "Cà rốt", 0.5, "củ", "n", "phu"), ("trung", "Trứng cút", 15, "quả", "n", "phu"),
       ("trung", "Trứng gà (lấy lòng trắng)", 1, "quả", "n", "phu"), SA(2), HANH(1), ("", "Bột năng", 3, MC, "x", "gia_vi"),
       MAM(1), DUONG(0.5), HAT_NEM(1), TIEU, RAU_THOM("Rau mùi")]),
    M("man", "hai_san", "goi_cuon", "Gỏi cuốn tôm thịt", "goi", "mat", "nhe", "it", "tom_the", "nang", 60, "vua",
      "Bánh tráng cuốn tôm, thịt luộc, bún, rau, hẹ – chấm tương đen bơ đậu phộng, không dầu mỡ, hợp ngày nắng.",
      ["Tôm rửa sạch, luộc chín, thả ngay vào tô nước đá 5 phút cho giòn; thịt bỏ da, luộc chín cũng ngâm nước đá 5 phút cho khỏi thâm, vớt ra để ráo.",
       "Tôm bóc vỏ, chẻ đôi; thịt thái lát mỏng; rau ngâm nước muối loãng rồi rửa sạch, để ráo; ớt băm, đậu phộng rang giã dập.",
       "Phi hành tím vàng giòn, vớt ra giấy thấm dầu; dùng chảo đó nấu sốt: tương đen, bơ đậu phộng, sữa tươi hoặc nước cốt dừa, nước lọc, chút hạt nêm, đường, khuấy sôi rồi tắt bếp.",
       "Nhúng ướt bánh tráng, xếp rau, bún, giá, hẹ, thịt, tôm, gấp mép và cuộn thật chặt tay.",
       "Bày ra đĩa, chấm tương rắc đậu phộng, hành phi (phần người lớn thêm ớt)."],
      None, CP + "6399579",
      [("tom_the", "Tôm tươi", 300, "g", "n", "chinh"), ("thit_heo", "Thịt nạc đùi hoặc ba chỉ", 200, "g", "n", "phu"),
       ("banh_trang", "Bánh tráng cuốn", 20, "cái", "n", "phu"), ("bun", "Bún tươi", 300, "g", "n", "phu"),
       ("xa_lach", "Xà lách", 1, "bó", "x", "phu"), ("gia_do", "Giá sống", 100, "g", "n", "phu"), ("", "Hẹ", 1, "bó", "x", "phu"),
       RAU_THOM("Rau thơm"), ("dau_phong", "Đậu phộng rang", 2, MC, "x", "phu"), HANH(2), OT(1),
       ("", "Tương đen", 4, MC, "x", "gia_vi"), ("", "Bơ đậu phộng", 2, MC, "x", "gia_vi"),
       ("", "Sữa tươi hoặc nước cốt dừa", 4, MC, "x", "gia_vi"), HAT_NEM(1), DUONG(0.3), DAU(2)]),
    M("mot_to", "heo", "bun_suon_tom_chua_cay", "Bún sườn tôm chua cay", "mon_chinh", "nong", "nang", "vua", "thit_heo|tom_the", "mua", 90, "vua",
      "Sườn non hầm sả với nước me, thêm tôm và dầu ớt – bún chua cay kiểu Thái, ăn với rau sống, bắp chuối.",
      ["Sườn chặt miếng, luộc sơ rồi rửa sạch; ướp với hành tím băm, nước mắm, muối, tiêu, đường khoảng 1 tiếng.",
       "Tôm bóc vỏ chừa đuôi, giữ gạch tôm cho nước dùng màu đẹp; ướp hành tím, nước mắm, tiêu, đường, để ngăn mát.",
       "Sả đập dập buộc thành bó; me vắt ngâm nước sôi lọc lấy nước cốt (khoảng nửa chén); làm dầu ớt: dầu nóng già rưới vào ớt bột, khuấy đều.",
       "Phi hành tím, xào sườn cho săn, đổ khoảng 2 lít nước, thả bó sả và nước me, hầm lửa vừa 30 phút đến khi sườn mềm.",
       "Cho tôm vào, nêm lại, tôm chín tới thì múc phần nước dùng cho bé ra trước rồi đổ dầu ớt vào nồi.",
       "Xếp bún ra tô, chan nước dùng, thêm hành lá; ăn với xà lách, rau thơm, bắp chuối, rau muống chẻ."],
      None, CP + "831592",
      [("thit_heo", "Sườn non", 500, "g", "n", "chinh"), ("tom_the", "Tôm sú hoặc tôm thẻ", 12, "con", "n", "chinh"),
       ("bun", "Bún", 800, "g", "n", "phu"), SA(4), HANH(2), ("khe_me", "Me vắt", 1, MC, "x", "gia_vi"),
       ("", "Ớt bột", 1, MCF, "x", "gia_vi"), MAM(3), DUONG(1), TIEU, DAU(3),
       RAU_THOM("Xà lách, rau thơm"), ("hoa_chuoi", "Bắp chuối bào", 1, "đĩa", "x", "phu"),
       ("rau_muong", "Rau muống chẻ", 1, "đĩa", "x", "phu"), HANH_LA]),

    # ---------- Vịt ----------
    M("lau", "ga", "lau_vit_nau_chao", "Lẩu vịt nấu chao", "lau", "nong", "nang", "vua", "vit", "mua", 120, "vua",
      "Vịt ướp áp chảo rồi hầm trong nước lèo rau củ, nêm chao và nước cốt dừa – béo thơm, ăn với khoai môn chiên, bún, rau.",
      ["Hầm nước lèo: cà rốt, củ cải cắt khúc to, sả đập dập, hành tây bổ đôi, hầm lửa nhỏ 40 phút cho ngọt.",
       "Vịt rửa muối và chút rượu, chặt miếng to, khứa chỗ thịt dày; ướp gừng đập dập, nước mắm, hạt nêm, đường, chút dầu điều 30 phút.",
       "Khoai môn cạo vỏ cắt khúc, chiên sơ vàng mặt.",
       "Áp chảo vịt vàng hai mặt rồi cho vào nồi nước lèo hầm thêm 40 phút; khoảng 20 phút thì hớt bọt, mỡ và vớt sả, gừng ra.",
       "Đánh tan khoảng nửa chén chao cho vào nồi, nêm lại (không thêm muối vì chao đã mặn), thêm nước cốt dừa cho béo.",
       "Bày lên bếp lẩu; nhúng rau muống, cải xanh, khoai môn; ăn với bún, chấm chao đánh tỏi ớt hoặc nước mắm."],
      None, CP + "15259003",
      [("vit", "Vịt ta", 1200, "g", "n", "chinh"), ("", "Chao", 1, "hũ", "x", "gia_vi"),
       ("ca_rot", "Cà rốt", 1, "củ", "x", "phu"), ("cu_cai", "Củ cải trắng", 1, "củ", "x", "phu"),
       ("khoai_mon", "Khoai môn", 400, "g", "n", "phu"), SA(4), ("", "Hành tây", 2, "củ", "x", "phu"),
       ("rau_muong", "Rau muống", 1, "bó", "n", "phu"), ("cai_xanh", "Cải xanh", 1, "bó", "n", "phu"),
       ("bun", "Bún tươi", 800, "g", "n", "phu"), ("dua", "Nước cốt dừa", 1, "lon nhỏ", "x", "phu"), GUNG(1),
       ("", "Dầu màu điều", 1, MCF, "x", "gia_vi"), MAM(2), HAT_NEM(2), DUONG(1), TIEU]),
    M("man", "ga", "vit_nau_mang", "Vịt nấu măng", "mon_chinh", "nong", "nang", "it", "vit|mang_rung", "mua", 70, "vua",
      "Vịt khử mùi bằng rượu gừng, xào săn rồi nấu với măng tươi xào thấm – nước ngọt, thơm ngò gai.",
      ["Gừng đập nát trộn rượu trắng, thoa đều lên vịt vài phút rồi rửa lại cho hết mùi; chặt miếng, chần nước sôi, để ráo.",
       "Ướp vịt với hành khô băm, muối, bột canh, hạt nêm 15–20 phút.",
       "Măng tươi bỏ phần già, xé sợi; luộc sôi 5 phút không đậy vung, xả nước lạnh, luộc thêm một lần nữa cho hết đắng.",
       "Xào vịt cho săn (7–10 phút), đổ khoảng 1 lít nước, thả một nhánh gừng nướng, hầm 15–20 phút, vớt bọt.",
       "Phi hành khô, cho măng vào xào với bột canh, hạt nêm, múc hai muôi nước vịt vào xào 10 phút cho măng thấm.",
       "Đổ măng vào nồi vịt, thêm nước, nấu sôi 10 phút, nêm vừa ăn; thả hành lá, ngò gai rồi tắt bếp."],
      None, CP + "270078",
      [("vit", "Thịt vịt cả xương", 800, "g", "n", "chinh"), ("mang_rung", "Măng tươi", 400, "g", "n", "chinh"),
       GUNG(2), HANH(3), HANH_LA, RAU_THOM("Ngò gai"), ("", "Rượu trắng", 0.3, "bát", "x", "gia_vi"),
       MUOI, ("", "Bột canh", 1, MCF, "x", "gia_vi"), HAT_NEM(2), MAM(1), DAU(1)]),
    M("man", "ga", "mang_xao_long_vit", "Măng xào lòng vịt", "mon_chinh", "nong", "nhe", "vua", "vit|mang_rung", "moi", 40, "de",
      "Bộ lòng đi kèm khi mua vịt (hoặc gà) xào với măng tươi luộc kỹ – giòn, thấm, ăn với cơm nóng.",
      ["Lòng vịt làm sạch kỹ với muối hột và rượu trắng, rửa lại, để thật ráo; cắt miếng vừa ăn; ướp hạt nêm, đường, nước mắm, hành tím băm 15–20 phút.",
       "Măng tươi thái mỏng, luộc với chút muối, sôi 5 phút thì đổ ra; luộc như vậy 3 lần cho hết đắng, để ráo.",
       "Phi hành tím, xào lòng đến chín thì múc ra.",
       "Cùng chảo đó phi hành, xào măng, nêm hạt nêm, đường, nước mắm; cho lòng vào đảo đều, nêm lại, thêm hành lá và tiêu rồi tắt bếp."],
      None, CP + "17026149",
      [("vit", "Lòng vịt (hoặc lòng gà)", 2, "bộ", "n", "chinh"), ("mang_rung", "Măng tươi", 300, "g", "n", "chinh"),
       HANH(3), HANH_LA, HAT_NEM(1), DUONG(0.3), MAM(1), DAU(4), TIEU, ("muoi_ca_na", "Muối hột", 1, MC, "x", "gia_vi"),
       ("", "Rượu trắng", 2, MC, "x", "gia_vi")]),

    # ---------- Món khác ----------
    M("mot_to", "hai_san", "pad_thai", "Pad Thái", "mon_chinh", "am", "nhe", "vua", "tom_the|dau_phu", "moi", 40, "vua",
      "Sợi phở khô Thái xào với tôm, đậu phụ, trứng, giá, hẹ, sốt me chua ngọt, rắc lạc rang – món một đĩa kiểu Thái.",
      ["Ngâm sợi phở khô (sợi Pad Thái) nước ấm khoảng 30 phút cho mềm dẻo, để ráo.",
       "Pha sốt: nước cốt me, nước mắm, đường thốt nốt (hoặc đường vàng), khuấy tan.",
       "Tôm bóc vỏ, rút chỉ; đậu phụ cắt hạt lựu chiên vàng; hẹ cắt khúc; lạc rang giã dập.",
       "Phi tỏi, hành tím, xào tôm vừa chín, cho đậu phụ; đẩy sang một bên, đập trứng vào đảo tơi.",
       "Cho sợi phở và sốt vào đảo lửa lớn đến khi sợi thấm, mềm (khô quá thì thêm chút nước); cho giá, hẹ đảo nhanh.",
       "Bày ra đĩa, rắc lạc, ăn kèm chanh, giá sống, ớt bột (phần bé không ớt)."],
      None, tk("pad thái"),
      [("tom_the", "Tôm", 300, "g", "n", "chinh"), ("dau_phu", "Đậu phụ", 1, "bìa", "n", "chinh"),
       ("bun", "Sợi phở khô Pad Thái", 300, "g", "n", "phu"), ("trung", "Trứng gà", 2, "quả", "n", "phu"),
       ("gia_do", "Giá đỗ", 200, "g", "n", "phu"), ("", "Hẹ", 1, "bó", "x", "phu"), ("dau_phong", "Lạc rang", 3, MC, "x", "phu"),
       ("khe_me", "Nước cốt me", 3, MC, "x", "gia_vi"), MAM(2), ("", "Đường thốt nốt", 2, MC, "x", "gia_vi"),
       TOI(3), HANH(2), DAU(3), ("", "Chanh", 1, "quả", "x", "gia_vi"), ("", "Ớt bột", 0.5, MCF, "x", "gia_vi")]),

    # ---------- Lô 4b (08/10/2026) ----------
    M("man", "heo", "cha_trung_hap_thit_bam", "Chả trứng hấp thịt băm", "mon_chinh", "am", "nhe", "vua", "thit_heo|trung", "moi", 50, "vua",
      "Thịt xay trộn miến, nấm mèo, trứng vịt hấp thành ổ, mặt láng lòng đỏ vàng – kiểu chả trứng cơm tấm, mềm, bé dễ ăn.",
      ["Nấm mèo, miến ngâm mềm; nấm mèo thái sợi, miến cắt ngắn.",
       "Ướp thịt xay với tỏi, hành tím băm, tiêu, hạt nêm, đường, nước mắm, dầu mè; trộn thật đều rồi cho miến, nấm mèo vào trộn cùng.",
       "Đập 4 quả trứng, tách riêng 2 lòng đỏ; phần trứng còn lại đổ vào thịt, trộn đều.",
       "Đánh tan 2 lòng đỏ với dầu điều để làm mặt chả.",
       "Khay hoặc đĩa sâu lót màng bọc, thoa chút dầu; dàn đều thịt vào, hấp lửa lớn khoảng 30 phút. Xăm tăm thấy không chảy nước, không dính thịt là chín.",
       "Láng lòng đỏ lên mặt, hạ nhỏ lửa, mở hé vung hấp thêm đến khi mặt ráo để giữ màu vàng đẹp.",
       "Tắt bếp, để chả nguội hẳn mới lấy ra cắt miếng."],
      None, CP + "24286744",
      [("thit_heo", "Thịt heo xay (khoảng 30% mỡ)", 250, "g", "n", "chinh"), ("trung", "Trứng vịt", 4, "quả", "n", "chinh"),
       ("", "Nấm mèo", 3, "tai", "x", "phu"), ("bun", "Miến khô", 1, "vắt", "n", "phu"),
       ("toi_pr", "Tỏi băm", 0.5, MC, "x", "gia_vi"), ("hanh_tim", "Hành tím băm", 0.5, MC, "x", "gia_vi"),
       HAT_NEM(1), TIEU, DUONG(0.5), MAM(0.5), ("", "Dầu mè", 0.5, MC, "x", "gia_vi"), ("", "Dầu điều", 1, MC, "x", "gia_vi")]),
    M("man", "heo", "thit_bam_xao_kieu_thai", "Thịt băm xào kiểu Thái (Pad Krapao)", "mon_chinh", "am", "nhe", "vua", "thit_heo", "moi", 15, "de",
      "Thịt nạc băm xào tỏi ớt giã, sốt xì dầu dầu hào, cuối cùng thả lá hương nhu – ăn với cơm nóng, trứng ốp la lòng đào, dưa chuột.",
      ["Tỏi, ớt giã nhuyễn (hoặc đập dập rồi băm); hương nhu (hoặc húng quế) nhặt lấy lá, rửa sạch; thịt nạc băm vừa, không băm quá nhuyễn.",
       "Pha sốt: nước, xì dầu, hắc xì dầu, đường, dầu hào, khuấy đều.",
       "Đun nóng già dầu, ốp trứng, múc dầu rưới lên mặt cho lòng trắng chín, lòng đỏ còn lòng đào; vớt ra đĩa, giữ dầu trong chảo.",
       "Phi tỏi ớt lửa lớn 15–20 giây cho thơm, cho thịt vào dằm tơi, đảo đến khi săn chín.",
       "Đổ sốt vào đảo đều 2–3 phút, thịt còn chút nước sốt là được.",
       "Thả lá hương nhu đảo vài giây rồi tắt bếp. Ăn với cơm, trứng ốp la và vài lát dưa chuột."],
      None, CP + "3889988",
      [("thit_heo", "Thịt nạc heo (hoặc ức gà)", 400, "g", "n", "chinh"), ("trung", "Trứng gà (ốp la)", 4, "quả", "n", "phu"),
       ("rau_thom", "Lá hương nhu (hoặc húng quế)", 2, "nắm", "x", "phu"), ("dua_leo", "Dưa chuột", 1, "quả", "x", "phu"),
       TOI(10), OT(4), DAU(4), ("", "Dầu hào", 2, MCF, "x", "gia_vi"), ("", "Xì dầu", 2.5, MCF, "x", "gia_vi"),
       ("", "Hắc xì dầu", 2, MCF, "x", "gia_vi"), DUONG(0.3)]),
    M("man", "heo", "khoai_tay_xao_thit_bam", "Khoai tây xào thịt băm", "mon_chinh", "am", "nhe", "vua", "khoai_tay|thit_heo", "moi", 35, "de",
      "Khoai tây hạt lựu chiên sơ cho vàng rồi om cùng thịt băm trong sốt xì dầu tương ớt – đậm đà, đưa cơm.",
      ["Khoai tây gọt vỏ, thái hạt lựu to, để ráo; hành lá thái nhỏ, để riêng phần đầu trắng và phần lá.",
       "Ướp thịt băm 15 phút với muối, tiêu, đường, dầu hào và đầu hành.",
       "Pha sốt: đường, nước lọc, tương ớt, nước tương.",
       "Chiên sơ khoai tây với ít dầu, đảo đều đến khi vàng các mặt và chín tới thì vớt ra.",
       "Phi đầu hành còn lại, cho thịt vào đảo săn và chín đều.",
       "Cho khoai vào đảo cùng, đổ sốt, đun lửa vừa 4–5 phút cho thấm. Gần tắt bếp thì thả hành lá."],
      None, CP + "24754176",
      [("thit_heo", "Thịt băm", 500, "g", "n", "chinh"), ("khoai_tay", "Khoai tây", 6, "củ", "n", "chinh"), HANH_LA,
       MUOI, TIEU, DUONG(1.5), ("", "Dầu hào", 2.5, MCF, "x", "gia_vi"), ("", "Nước tương", 6, MCF, "x", "gia_vi"),
       ("", "Tương ớt", 2, MCF, "x", "gia_vi"), DAU(3)]),
    M("canh", "heo", "canh_rau_ngot_thit_bam", "Canh rau ngót thịt băm", "canh", "mat", "nhe", "it", "rau_ngot", "nang", 15, "de",
      "Thịt nạc băm thả thẳng vào nồi nước sôi, hớt bọt cho trong rồi cho rau ngót – canh thanh, ngọt nước, nấu rất nhanh.",
      ["Thịt nạc thái mỏng rồi băm nhỏ, ướp chút nước mắm, muối, tiêu, hành tím băm.",
       "Rau ngót tuốt lá, rửa sạch.",
       "Đun sôi khoảng 1,2 lít nước, cho thịt vào, hớt bọt cho nước canh trong.",
       "Cho rau ngót vào, đun sôi lại, nêm vừa ăn rồi tắt bếp."],
      None, CP + "17303468",
      [("rau_ngot", "Rau ngót", 2, "bó", "n", "chinh"), ("thit_heo", "Thịt nạc heo", 200, "g", "n", "phu"),
       HANH(1), MAM(1), MUOI, TIEU]),
    M("mot_to", "ga", "sup_ga_ngo_nam", "Súp gà ngô nấm", "mon_chinh", "am", "nhe", "it", "ga_ta|ngo", "moi", 40, "de",
      "Lườn gà luộc xé, nấm hương xào thơm, nấu trong nước dùng gà, tạo vân trứng và sánh bột năng – súp nhẹ cho cả nhà.",
      ["Luộc lườn gà, giữ nước luộc làm nước dùng; gà chín xé nhỏ. Nấm hương ngâm nở, thái nhỏ. Ngô tách hạt.",
       "Xào nấm với thịt gà, nêm vừa.",
       "Đun sôi nước dùng gà, cho hạt ngô, gà và nấm vào, nêm hạt nêm, hớt sạch bọt.",
       "Đánh tan trứng; để lửa to cho nồi sôi mạnh, rót trứng từ từ, dùng đũa khuấy vòng tròn cho trứng thành vân.",
       "Hòa bột năng với nước, đổ vào nồi, đun sôi lại rồi tắt bếp.",
       "Múc ra bát, rắc rau mùi."],
      None, CP + "2831922",
      [("ga_ta", "Lườn gà", 300, "g", "n", "chinh"), ("ngo", "Bắp ngô ngọt", 1, "bắp", "n", "chinh"),
       ("nam", "Nấm hương", 8, "tai", "n", "phu"), ("trung", "Trứng gà", 2, "quả", "n", "phu"),
       ("", "Nước dùng gà", 1.2, "lít", "x", "phu"), ("", "Bột năng", 3, MC, "x", "gia_vi"), HAT_NEM(1), DAU(1),
       RAU_THOM("Rau mùi")]),

    # ---------- Phở gà (trưa), nấu dư nước dùng cho tối (miến gà / súp gà thay canh) ----------
    M("mot_to", "ga", "pho_ga", "Phở gà", "mon_chinh", "nong", "nhe", "it", "ga_ta", "mua", 120, "vua",
      "Phở gà kiểu Bắc: luộc gà nguyên con, ninh xương với gừng hành nướng và hoa hồi, quế – nước trong, ngọt; "
      "nấu dư nước dùng và để riêng ít thịt ức để tối nấu miến hoặc súp thay canh.",
      ["Gà làm sạch, xát muối với gừng giã rồi rửa lại; chân, cổ, khung xương chần sơ nước sôi.",
       "Nướng (hoặc đốt trên bếp) gừng, hành tây, hành khô đến cháy xém vỏ, cạo sạch; rang thơm hoa hồi, quế, thảo quả, hạt mùi rồi cho vào túi lọc.",
       "Cho gà, xương, gừng hành nướng vào nồi khoảng 5 lít nước lạnh, đun sôi rồi hạ lửa nhỏ, hớt bọt; luộc gà khoảng 30–35 phút đến khi chín (xiên đùi không ra nước hồng) thì vớt ra ngâm nước nguội cho da giòn.",
       "Thả túi gia vị vào nồi, ninh tiếp xương lửa nhỏ khoảng 1 tiếng; nêm muối, nước mắm, chút đường phèn cho nước ngọt thanh.",
       "Múc riêng khoảng 1,5 lít nước dùng và để riêng phần ức gà, cất ngăn mát – tối nấu miến gà hoặc súp gà.",
       "Gà xé hoặc chặt miếng; lá chanh thái chỉ; hành lá, rau mùi thái nhỏ. Trụng bánh phở, xếp thịt gà, rắc hành, lá chanh, chan nước dùng thật nóng; ăn kèm chanh, ớt (phần người lớn)."],
      None, tk("phở gà Hà Nội"),
      [("ga_ta", "Gà ta nguyên con", 1600, "g", "n", "chinh"), ("ga_ta", "Chân, cổ, khung xương gà", 500, "g", "n", "phu"),
       ("bun", "Bánh phở tươi", 1000, "g", "n", "phu"), ("", "Hành tây", 2, "củ", "x", "phu"), GUNG(1), HANH(5),
       ("", "Gia vị phở (hồi, quế, thảo quả, hạt mùi)", 1, "gói", "x", "gia_vi"), ("", "Lá chanh", 10, "lá", "x", "phu"),
       HANH_LA, RAU_THOM("Rau mùi"), ("", "Chanh", 2, "quả", "x", "gia_vi"), OT(2), MUOI, MAM(2),
       ("", "Đường phèn", 1, MC, "x", "gia_vi")]),
]
