"""30 công thức mẫu cho Cá Chef.

Tham khảo Cookpad (link ở cột nguon), định lượng chuẩn hoá lại cho khẩu phần gốc,
cách làm viết lại ngắn gọn. Tất cả đang ở trạng thái "chua_nau_thu".

Nhãn:
  loai: mon_chinh / canh / goi / lau / an_vat / trang_mieng / do_uong
  nhiet: mat / am / nong      do_nang: nhe / nang      dau_mo: it / vua / nhieu
  thoi_tiet_hop: nang / mua / moi (mọi thời tiết)
  nguyen_lieu_chinh: mã trong tab nguyen_lieu; nhiều mã cách nhau "|" = chỉ cần 1 mã đang có mùa.
Nguyên liệu: (mã nguyên liệu hoặc "", tên, số lượng, đơn vị, kiểu tính, vai trò)
  kiểu tính: "n" = theo_nguoi (nhân thẳng), "x" = theo_noi (gia vị/nước, tăng chậm)
  số lượng None = nêm vừa ăn.
"""

CP = "https://cookpad.com/vn/cong-thuc/"
MC, MCF = "muỗng canh", "muỗng cà phê"


def R(ma, ten, loai, nhiet, do_nang, dau_mo, chinh, thoi_tiet, phut, do_kho, mo_ta,
      cach_lam, pho_bien, nguon, nguyen_lieu, khau_phan=4):
    return dict(ma=ma, ten=ten, loai=loai, nhiet=nhiet, do_nang=do_nang, dau_mo=dau_mo,
                chinh=chinh, thoi_tiet=thoi_tiet, khau_phan=khau_phan, phut=phut,
                do_kho=do_kho, mo_ta=mo_ta, cach_lam=cach_lam, pho_bien=pho_bien,
                nguon=nguon, nguyen_lieu=nguyen_lieu)


RECIPES = [
    R("banh_can", "Bánh căn Phan Rang", "an_vat", "nong", "nhe", "it", "bot_gao", "mua", 60, "vua",
      "Bánh bột gạo nướng khuôn đất, giòn đáy, chấm mắm nêm – món ăn sáng/chiều mưa đặc trưng Phan Rang.",
      ["Xay nhuyễn cơm nguội với 300ml nước, trộn cùng bột gạo, thêm khoảng 500ml nước và 1/2 muỗng cà phê muối; để bột nghỉ ít nhất 2–3 tiếng (tốt nhất qua đêm).",
       "Mắm nêm: luộc cà chua, băm cùng thơm, tỏi, ớt; đun với mắm nêm, đường và chút nước đến khi sánh.",
       "Phi dầu nóng vào hành lá cắt nhỏ làm mỡ hành.",
       "Đốt nóng khuôn đất hoặc khuôn gang, quét ít dầu, đổ bột 2/3 khuôn, thêm trứng cút hoặc tôm/mực, đậy nắp 3–4 phút đến khi đáy giòn vàng.",
       "Gắp bánh ra, rưới mỡ hành, chấm mắm nêm, ăn kèm xoài sống, rau thơm."],
      10, CP + "15352056",
      [("bot_gao", "Bột gạo", 300, "g", "n", "chinh"),
       ("", "Cơm nguội", 150, "g", "n", "phu"),
       ("trung", "Trứng cút", 20, "quả", "n", "phu"),
       ("muc_tuoi|tom_the", "Tôm hoặc mực tươi", 200, "g", "n", "phu"),
       ("", "Hành lá", 50, "g", "x", "phu"),
       ("", "Mắm nêm", 100, "g", "x", "gia_vi"),
       ("", "Thơm (dứa)", 100, "g", "x", "gia_vi"),
       ("ca_chua", "Cà chua", 1, "quả", "x", "gia_vi"),
       ("toi_pr", "Tỏi Phan Rang", 4, "tép", "x", "gia_vi"),
       ("", "Đường", 2, MC, "x", "gia_vi"),
       ("", "Dầu ăn", 3, MC, "x", "gia_vi")]),

    R("banh_xeo_pr", "Bánh xèo Phan Rang", "an_vat", "nong", "nang", "vua", "bot_gao", "mua", 60, "vua",
      "Bánh xèo nhỏ đổ khuôn đất, nhân tôm mực, chấm nước mắm đậu phộng cà chua kiểu Phan Rang.",
      ["Pha bột gạo với nước và chút muối, thêm hành lá cắt nhỏ, để nghỉ 30 phút.",
       "Nước chấm: luộc cà chua, xay cùng đậu phộng rang, nước mắm và đường đã đun tan, để nguội.",
       "Làm nóng khuôn, quét ít dầu, cho tôm mực vào áp sơ rồi đổ bột, thêm giá hoặc trứng, đậy nắp 3–4 phút.",
       "Khi bánh chín giòn, gắp ra, cuốn rau sống và chấm nước mắm đậu phộng."],
      1, CP + "24703150",
      [("bot_gao", "Bột gạo", 300, "g", "n", "chinh"),
       ("tom_the", "Tôm", 200, "g", "n", "phu"),
       ("muc_tuoi", "Mực", 200, "g", "n", "phu"),
       ("trung", "Trứng gà", 2, "quả", "n", "phu"),
       ("", "Giá đỗ", 200, "g", "n", "phu"),
       ("rau_thom", "Xà lách, rau thơm", 300, "g", "n", "phu"),
       ("dau_phong", "Đậu phộng rang", 100, "g", "x", "gia_vi"),
       ("ca_chua", "Cà chua", 2, "quả", "x", "gia_vi"),
       ("mam_ca_na", "Nước mắm", 4, MC, "x", "gia_vi"),
       ("", "Đường", 4, MC, "x", "gia_vi")]),

    R("com_ga_pr", "Cơm gà Phan Rang", "mon_chinh", "am", "nang", "vua", "ga_ta", "moi", 75, "vua",
      "Gà ta luộc xé trộn rau răm, cơm vàng nghệ nấu nước gà, chấm nước mắm gừng.",
      ["Gà làm sạch, chà muối, luộc với gừng đập dập lửa nhỏ khoảng 20 phút, vớt ra ngâm nước lạnh cho da giòn.",
       "Giã gừng, tỏi; phi thơm rồi rang gạo cùng bột nghệ, nấu cơm bằng nước luộc gà.",
       "Xé gà, trộn với hành tây thái mỏng, rau răm, muối tiêu chanh.",
       "Nước chấm: giã gừng, tỏi, ớt với đường, pha nước mắm, chanh và chút nước luộc gà.",
       "Dọn cơm với gà, dưa leo, cà chua và nước chấm gừng."],
      6, CP + "5338422",
      [("ga_ta", "Gà ta", 1300, "g", "n", "chinh"),
       ("", "Gạo", 500, "g", "n", "chinh"),
       ("sa_ot", "Gừng", 150, "g", "x", "gia_vi"),
       ("toi_pr", "Tỏi Phan Rang", 8, "tép", "x", "gia_vi"),
       ("hanh_tim", "Hành tím", 3, "củ", "x", "gia_vi"),
       ("", "Bột nghệ", 1, MCF, "x", "gia_vi"),
       ("", "Hành tây", 1, "củ", "n", "phu"),
       ("rau_thom", "Rau răm", 1, "bó", "n", "phu"),
       ("", "Dưa leo", 1, "quả", "n", "phu"),
       ("mam_ca_na", "Nước mắm", 3, MC, "x", "gia_vi"),
       ("", "Chanh", 1, "quả", "x", "gia_vi")]),

    R("goi_ca_mai", "Gỏi cá mai", "goi", "mat", "nhe", "it", "ca_mai", "nang", 40, "vua",
      "Cá mai tái chanh trộn hành tây, rau răm, đậu phộng; cuốn bánh tráng rau sống. Ăn tái – chỉ dùng cá thật tươi.",
      ["Cá mai bỏ đầu, xẻ bỏ xương, rửa nước muối loãng.",
       "Vắt nước cốt chanh ngập cá, bóp 10–15 phút đến khi thịt cá trắng đục, vắt thật ráo.",
       "Hành tây bào mỏng, ngâm nước đá cho giòn và bớt hăng.",
       "Trộn cá với hành tây, rau răm, đường và nước mắm; rắc đậu phộng giã và hành phi.",
       "Cuốn bánh tráng với rau sống, chấm nước mắm chua ngọt tỏi ớt."],
      1, CP + "11056866",
      [("ca_mai", "Cá mai", 400, "g", "n", "chinh"),
       ("", "Chanh", 6, "quả", "x", "gia_vi"),
       ("", "Hành tây", 1, "củ", "n", "phu"),
       ("rau_thom", "Rau răm", 1, "bó", "n", "phu"),
       ("dau_phong", "Đậu phộng rang", 50, "g", "x", "phu"),
       ("hanh_tim", "Hành phi", 2, MC, "x", "gia_vi"),
       ("banh_trang", "Bánh tráng", 10, "lá", "n", "phu"),
       ("rau_thom", "Rau sống", 300, "g", "n", "phu"),
       ("mam_ca_na", "Nước mắm", 3, MC, "x", "gia_vi"),
       ("", "Đường", 2, MC, "x", "gia_vi")]),

    R("bun_sua", "Bún sứa chả cá", "mon_chinh", "mat", "nhe", "it", "sua", "nang", 60, "vua",
      "Nước dùng cá thanh ngọt, sứa giòn, chả cá – món nước nhẹ cho ngày nắng.",
      ["Nấu nước dùng: phi hành tỏi với dầu điều, xào cà chua, đổ khoảng 2 lít nước, nêm mắm ruốc, muối, đường.",
       "Cho đầu và khúc cá vào nấu 20 phút cho ngọt nước; thêm chả cá cắt miếng.",
       "Sứa rửa sạch, chần nhanh qua nước sôi, để ráo.",
       "Bắp cải bào nhỏ, trụng sơ.",
       "Xếp bún, sứa, cá, chả vào tô, chan nước dùng, thêm hành ngò, thì là."],
      8, CP + "14079877",
      [("sua", "Sứa", 300, "g", "n", "chinh"),
       ("", "Chả cá", 300, "g", "n", "phu"),
       ("ca_nuc|ca_thu", "Cá nục hoặc cá thu (đầu + khúc)", 400, "g", "n", "phu"),
       ("bun", "Bún tươi", 800, "g", "n", "chinh"),
       ("ca_chua", "Cà chua", 3, "quả", "x", "phu"),
       ("bap_cai", "Bắp cải", 200, "g", "n", "phu"),
       ("", "Mắm ruốc", 1, MC, "x", "gia_vi"),
       ("", "Dầu điều", 1, MC, "x", "gia_vi"),
       ("rau_thom", "Hành ngò, thì là", 1, "bó", "x", "phu")]),

    R("banh_canh_cha_ca", "Bánh canh chả cá", "mon_chinh", "nong", "nhe", "it", "ca_thu", "moi", 45, "de",
      "Bánh canh bột gạo, nước dùng đầu cá thu, chả cá chiên – ăn sáng quen thuộc dải Nam Trung Bộ.",
      ["Phi giòn hành tím, giữ lại dầu hành.",
       "Nấu sôi khoảng 2 lít nước với đầu/xương cá thu, chút muối và đường, hớt bọt, ninh 20 phút.",
       "Trụng sợi bánh canh, xắt chả cá.",
       "Cho bánh canh và chả cá vào nồi, nêm lại vừa ăn.",
       "Múc ra tô, rắc tiêu, hành lá, hành phi."],
      127, CP + "25087411",
      [("bun", "Bánh canh tươi", 800, "g", "n", "chinh"),
       ("ca_thu", "Đầu/xương cá thu", 500, "g", "x", "chinh"),
       ("", "Chả cá chiên", 300, "g", "n", "phu"),
       ("hanh_tim", "Hành tím", 5, "củ", "x", "gia_vi"),
       ("", "Hành lá", 30, "g", "x", "phu"),
       ("", "Nước", 2, "lít", "x", "gia_vi")]),

    R("banh_hoi_long_heo", "Bánh hỏi lòng heo", "mon_chinh", "am", "nang", "vua", "long_heo", "moi", 60, "vua",
      "Bánh hỏi phết mỡ hành, lòng heo luộc, rau sống và nước mắm tỏi ớt.",
      ["Đổ dầu sôi vào hành lá cắt nhỏ với chút muối đường làm mỡ hành; phết lên từng lớp bánh hỏi.",
       "Lòng heo rửa với muối, giấm, gừng; chần 1 phút rồi rửa lại.",
       "Luộc lòng với hành khô, sả, gừng đến chín, vớt ra ngâm nước lạnh rồi thái.",
       "Nước chấm: hoà đường với nước, thêm nước mắm, giấm, tỏi ớt băm.",
       "Dọn bánh hỏi, lòng, rau sống và nước chấm."],
      1, CP + "3768046",
      [("bun", "Bánh hỏi", 800, "g", "n", "chinh"),
       ("long_heo", "Lòng heo các loại", 800, "g", "n", "chinh"),
       ("", "Hành lá", 100, "g", "x", "phu"),
       ("sa_ot", "Sả, gừng", 1, "phần", "x", "gia_vi"),
       ("rau_thom", "Rau sống", 300, "g", "n", "phu"),
       ("mam_ca_na", "Nước mắm", 3, MC, "x", "gia_vi"),
       ("toi_pr", "Tỏi", 4, "tép", "x", "gia_vi"),
       ("", "Giấm, đường", None, "vừa đủ", "x", "gia_vi")]),

    R("lau_de", "Lẩu dê rau Đà Lạt", "lau", "nong", "nang", "vua", "thit_de", "mua", 120, "kho",
      "Lẩu dê thuốc bắc, khoai môn, táo đỏ; nhúng rau Đà Lạt, chấm chao – món tủ ngày mưa.",
      ["Thịt dê rửa với rượu và gừng để khử mùi, thái mỏng, ướp sa tế và chút gia vị.",
       "Hầm xương với gừng, sả, gói thuốc bắc khoảng 1 tiếng, lọc lấy nước.",
       "Cho khoai môn, táo đỏ, đậu phụ vào nồi nước lẩu, nêm vừa ăn.",
       "Bày thịt dê, rau Đà Lạt (cải thảo, nấm, cải cúc), bún/mì; nhúng ăn dần.",
       "Chấm chao pha đường, ớt, chanh."],
      9, CP + "10431495",
      [("thit_de", "Thịt dê", 1000, "g", "n", "chinh"),
       ("", "Xương dê hoặc xương heo", 1000, "g", "x", "phu"),
       ("", "Gói thuốc bắc lẩu", 1, "gói", "x", "gia_vi"),
       ("", "Khoai môn", 300, "g", "n", "phu"),
       ("", "Đậu phụ", 4, "miếng", "n", "phu"),
       ("", "Táo đỏ", 10, "quả", "x", "gia_vi"),
       ("sa_ot", "Gừng, sả", 1, "phần", "x", "gia_vi"),
       ("cai_thao|nam", "Rau lẩu Đà Lạt (cải thảo, nấm, cải cúc)", 800, "g", "n", "phu"),
       ("bun", "Bún hoặc mì", 500, "g", "n", "phu"),
       ("", "Chao", 1, "hũ", "x", "gia_vi"),
       ("", "Sa tế", 2, MC, "x", "gia_vi")]),

    R("de_nuong", "Dê nướng chao sả", "mon_chinh", "nong", "nang", "it", "thit_de", "moi", 60, "vua",
      "Thịt dê ướp chao, sả, mè rồi nướng than – đặc sản quán dê Phan Rang.",
      ["Thịt dê rửa, ngâm với rượu trắng và gừng giã 30 phút, rửa lại, thái miếng vừa ăn.",
       "Ướp với chao, sả tỏi ớt băm, đường, hạt nêm, ngũ vị hương và dầu ăn 15–30 phút.",
       "Trộn thêm mè trắng.",
       "Nướng trên than hồng 10–15 phút đến khi săn và vàng nâu.",
       "Ăn kèm rau sống, chấm chao hoặc muối ớt chanh."],
      8, CP + "15124350",
      [("thit_de", "Thịt dê", 600, "g", "n", "chinh"),
       ("", "Chao", 1, "hũ nhỏ", "x", "gia_vi"),
       ("sa_ot", "Sả", 5, "cây", "x", "gia_vi"),
       ("toi_pr", "Tỏi", 5, "tép", "x", "gia_vi"),
       ("", "Mè trắng", 1, MC, "x", "gia_vi"),
       ("", "Rượu trắng + gừng (khử mùi)", None, "vừa đủ", "x", "gia_vi"),
       ("", "Đường, hạt nêm, ngũ vị hương", None, "vừa đủ", "x", "gia_vi"),
       ("rau_thom", "Rau sống", 300, "g", "n", "phu")]),

    R("de_xao_lan", "Dê xào lăn", "mon_chinh", "nong", "nang", "nhieu", "thit_de", "mua", 60, "vua",
      "Dê xào sả, cà ri, nước cốt dừa – thơm cay, ăn với bánh mì hoặc cơm.",
      ["Thịt dê thái mỏng, ướp sa tế, muối, hạt nêm, tiêu, ngũ vị hương khoảng 1 tiếng.",
       "Phi sả, hành, tỏi; cho bột cà ri, bột nghệ vào xào đến khi ra dầu.",
       "Cho thịt dê vào xào săn, thêm sữa tươi hoặc nước cốt dừa, đun sôi nhẹ.",
       "Thêm hành tây, hành lá, đảo đều rồi tắt bếp, rắc đậu phộng và tiêu."],
      3, CP + "15747616",
      [("thit_de", "Thịt dê", 600, "g", "n", "chinh"),
       ("", "Hành tây", 300, "g", "n", "phu"),
       ("sa_ot", "Sả băm", 2, MC, "x", "gia_vi"),
       ("toi_pr", "Tỏi, hành tím băm", 2, MC, "x", "gia_vi"),
       ("", "Nước cốt dừa hoặc sữa tươi", 200, "ml", "x", "phu"),
       ("", "Bột cà ri", 2, MCF, "x", "gia_vi"),
       ("", "Bột nghệ", 1, MCF, "x", "gia_vi"),
       ("", "Sa tế", 1, MC, "x", "gia_vi"),
       ("dau_phong", "Đậu phộng rang", 30, "g", "x", "phu")]),

    R("muc_mot_nang_nuong", "Mực một nắng nướng muối ớt xanh", "mon_chinh", "am", "nhe", "it", "muc_mot_nang", "moi", 40, "de",
      "Mực một nắng Ninh Thuận ướp muối ớt xanh, nướng than; ngon cả ngày nắng lẫn ngày mưa.",
      ["Xay nhuyễn ớt xanh, muối hột, đường, lá chanh, vỏ và nước cốt chanh thành muối ớt xanh.",
       "Khứa nhẹ mặt mực, ướp với một nửa phần muối ớt xanh và chút dầu ăn 30 phút.",
       "Nướng than hoặc lò 180°C khoảng 15–20 phút, trở mặt giữa chừng.",
       "Cắt miếng, chấm phần muối ớt xanh còn lại, ăn kèm dưa leo, rau thơm."],
      5, CP + "22554074",
      [("muc_mot_nang", "Mực một nắng", 600, "g", "n", "chinh"),
       ("", "Ớt xanh", 3, "quả", "x", "gia_vi"),
       ("", "Lá chanh", 5, "lá", "x", "gia_vi"),
       ("", "Chanh", 1, "quả", "x", "gia_vi"),
       ("muoi_ca_na", "Muối hột", 1, MCF, "x", "gia_vi"),
       ("", "Đường", 2, MCF, "x", "gia_vi"),
       ("", "Dưa leo, rau thơm", 300, "g", "n", "phu")]),

    R("goi_rong_sun", "Gỏi rong sụn tôm", "goi", "mat", "nhe", "it", "rong_sun", "nang", 40, "de",
      "Rong sụn Ninh Hải giòn sần sật trộn tôm, cà rốt, rau húng – món mát ngày nắng gắt.",
      ["Ngâm rong sụn 20 phút, thay nước vài lần cho hết mặn, rửa sạch, cắt khúc.",
       "Tôm luộc, bóc vỏ; cà rốt bào sợi; rau húng rửa sạch.",
       "Pha nước trộn: nước mắm, đường, nước cốt tắc/chanh, tỏi ớt băm.",
       "Trộn rong, tôm, cà rốt, rau; chỉ rưới nước trộn khi sắp ăn; rắc đậu phộng.",
       "Ăn kèm bánh tráng mè nướng."],
      15, CP + "24745143",
      [("rong_sun", "Rong sụn", 400, "g", "n", "chinh"),
       ("tom_the", "Tôm", 300, "g", "n", "phu"),
       ("ca_rot", "Cà rốt", 150, "g", "n", "phu"),
       ("rau_thom", "Rau húng", 70, "g", "n", "phu"),
       ("", "Tắc hoặc chanh", 5, "quả", "x", "gia_vi"),
       ("mam_ca_na", "Nước mắm", 3, MC, "x", "gia_vi"),
       ("", "Đường", 5, MC, "x", "gia_vi"),
       ("dau_phong", "Đậu phộng rang", 50, "g", "x", "phu"),
       ("banh_trang", "Bánh tráng mè", 4, "cái", "n", "phu")]),

    R("goi_tao_xanh", "Gỏi táo xanh tôm khô", "goi", "mat", "nhe", "it", "tao_xanh", "nang", 20, "de",
      "Táo xanh Phan Rang bào sợi trộn tôm khô, rau thơm – chua giòn, giải nhiệt. (Cách làm theo gỏi xoài tôm khô.)",
      ["Táo xanh rửa sạch, để cả vỏ cho giòn, bào sợi, ngâm nước muối loãng cho khỏi thâm, vắt ráo.",
       "Tôm khô ngâm mềm, rang sơ.",
       "Pha nước trộn: nước mắm, đường, tương ớt.",
       "Trộn táo, tôm khô, rau răm, húng quế, ớt với nước trộn; rắc hành phi và đậu phộng."],
      10, CP + "16755224",
      [("tao_xanh", "Táo xanh", 600, "g", "n", "chinh"),
       ("", "Tôm khô", 40, "g", "n", "phu"),
       ("rau_thom", "Rau răm, húng quế", 1, "bó", "n", "phu"),
       ("mam_ca_na", "Nước mắm", 2, MC, "x", "gia_vi"),
       ("", "Đường", 3, MC, "x", "gia_vi"),
       ("", "Tương ớt", 1, MC, "x", "gia_vi"),
       ("hanh_tim", "Hành phi", 2, MC, "x", "gia_vi"),
       ("dau_phong", "Đậu phộng rang", 40, "g", "x", "phu")]),

    R("nem_nuong", "Nem nướng cuốn bánh tráng", "mon_chinh", "am", "nang", "it", "thit_heo", "moi", 90, "vua",
      "Nem thịt heo nướng than, cuốn bánh tráng rau sống, chấm tương đậu phộng.",
      ["Thịt nạc vai xay nhuyễn, trộn mỡ heo hạt lựu đã trụng, tỏi băm, đường, nước mắm, bột năng, tiêu; quết thật dẻo.",
       "Để hỗn hợp nghỉ lạnh 30 phút, nắn quanh que tre hoặc cây sả.",
       "Nướng than hoặc lò 200°C khoảng 15–20 phút đến khi vàng đều.",
       "Nước chấm: tương đen, bơ đậu phộng, tương ớt, chút nước, đun sánh; rắc đậu phộng giã.",
       "Cuốn nem với bánh tráng, rau sống, dưa leo, khế."],
      90, CP + "24967972",
      [("thit_heo", "Thịt nạc vai xay", 600, "g", "n", "chinh"),
       ("", "Mỡ heo", 100, "g", "n", "phu"),
       ("toi_pr", "Tỏi", 4, "tép", "x", "gia_vi"),
       ("", "Bột năng", 1, MC, "x", "gia_vi"),
       ("mam_ca_na", "Nước mắm", 2, MC, "x", "gia_vi"),
       ("", "Đường", 1, MC, "x", "gia_vi"),
       ("banh_trang", "Bánh tráng", 20, "lá", "n", "phu"),
       ("rau_thom", "Rau sống, dưa leo, khế", 400, "g", "n", "phu"),
       ("", "Tương đen", 4, MC, "x", "gia_vi"),
       ("dau_phong", "Bơ đậu phộng / đậu phộng giã", 2, MC, "x", "gia_vi")]),

    R("ca_com_rim", "Cá cơm rim mắm tỏi", "mon_chinh", "am", "nhe", "vua", "ca_com", "moi", 30, "de",
      "Cá cơm tươi rim khô với tỏi phi và nước mắm Cà Ná – món mặn ăn cơm.",
      ["Cá cơm rửa nhanh dưới vòi nước, để thật ráo.",
       "Phi tỏi thái lát vàng nhạt, vớt ra.",
       "Cho cá vào dầu tỏi, lửa nhỏ, đảo nhẹ đến khi cá săn khô.",
       "Hoà nước mắm, đường, ớt với 2 muỗng nước, đổ vào rim đến khi khô lại; cho tỏi phi, tiêu, hành lá rồi tắt bếp."],
      126, CP + "24195659",
      [("ca_com", "Cá cơm tươi", 400, "g", "n", "chinh"),
       ("toi_pr", "Tỏi Phan Rang", 1, "củ", "x", "gia_vi"),
       ("mam_ca_na", "Nước mắm Cà Ná", 2, MC, "x", "gia_vi"),
       ("", "Đường", 1, MC, "x", "gia_vi"),
       ("", "Dầu ăn", 3, MC, "x", "gia_vi"),
       ("sa_ot", "Ớt", 2, "quả", "x", "gia_vi")]),

    R("ca_nuc_hap_cuon", "Cá nục hấp cuốn bánh tráng", "mon_chinh", "mat", "nhe", "it", "ca_nuc", "nang", 45, "de",
      "Cá nục hấp cuốn bánh tráng, rau sống, chấm mắm nêm thơm – nhẹ bụng ngày nắng.",
      ["Cá nục làm sạch, ướp dầu hào, nước mắm, đường, hành tím băm, tiêu 15–20 phút.",
       "Hấp cách thuỷ 10–15 phút đến khi chín.",
       "Rửa sạch rau muống, xà lách, rau thơm; thái dưa leo, khế.",
       "Mắm nêm: mắm nêm, thơm băm, tỏi, ớt, đường trộn đều.",
       "Gỡ cá, cuốn bánh tráng với rau, chấm mắm nêm."],
      23, CP + "16892911",
      [("ca_nuc", "Cá nục", 600, "g", "n", "chinh"),
       ("", "Dầu hào", 2, MC, "x", "gia_vi"),
       ("mam_ca_na", "Nước mắm", 1, MC, "x", "gia_vi"),
       ("hanh_tim", "Hành tím", 2, "củ", "x", "gia_vi"),
       ("banh_trang", "Bánh tráng", 20, "lá", "n", "phu"),
       ("rau_thom", "Rau muống, xà lách, rau thơm", 400, "g", "n", "phu"),
       ("", "Mắm nêm", 4, MC, "x", "gia_vi"),
       ("", "Thơm (dứa)", 100, "g", "x", "gia_vi"),
       ("toi_pr", "Tỏi", 3, "tép", "x", "gia_vi")]),

    R("chao_ga", "Cháo gà hành tím", "mon_chinh", "nong", "nhe", "it", "ga_ta", "mua", 60, "de",
      "Cháo gà ta nấu gừng, rắc hành tím phi Ninh Thuận – ấm bụng ngày mưa.",
      ["Gà làm sạch, luộc với gừng và chút muối trong khoảng 2,5 lít nước.",
       "Vớt gà ra, cho gạo đã vo vào nước luộc, nấu nhỏ lửa 30–40 phút đến khi nhừ.",
       "Xé thịt gà, trộn muối tiêu chanh và rau răm.",
       "Nêm cháo với nước mắm, múc ra tô, thêm gà, hành lá, hành tím phi, tiêu."],
      100, CP + "25473627",
      [("ga_ta", "Gà ta", 1200, "g", "n", "chinh"),
       ("", "Gạo", 200, "g", "n", "chinh"),
       ("sa_ot", "Gừng", 1, "củ", "x", "gia_vi"),
       ("hanh_tim", "Hành tím phi", 3, MC, "x", "gia_vi"),
       ("", "Hành lá", 30, "g", "x", "phu"),
       ("rau_thom", "Rau răm", 1, "bó", "n", "phu"),
       ("mam_ca_na", "Nước mắm", 1, MC, "x", "gia_vi")]),

    R("canh_chua_ca_nuc", "Canh chua cá nục", "canh", "mat", "nhe", "it", "ca_nuc", "nang", 30, "de",
      "Canh chua cá nục cà chua, thơm, rau răm – giải nhiệt ngày nắng gió.",
      ["Cá nục rửa với muối và giấm, cắt khúc.",
       "Phi hành tím, xào cà chua cắt múi đến mềm.",
       "Đổ khoảng 1,5 lít nước, nấu sôi, cho thơm, me (hoặc giấm), đường, nước mắm.",
       "Thả cá vào nấu 7–10 phút, thêm hành tây; tắt bếp cho rau răm, ngò gai, tiêu."],
      535, CP + "26265384",
      [("ca_nuc", "Cá nục", 500, "g", "n", "chinh"),
       ("ca_chua", "Cà chua", 3, "quả", "x", "phu"),
       ("", "Thơm (dứa)", 150, "g", "x", "phu"),
       ("", "Hành tây", 1, "củ", "x", "phu"),
       ("khe_me", "Me chua hoặc giấm", 30, "g", "x", "gia_vi"),
       ("rau_thom", "Rau răm, ngò gai", 1, "bó", "x", "phu"),
       ("mam_ca_na", "Nước mắm", 2, MC, "x", "gia_vi"),
       ("", "Đường", 1, MC, "x", "gia_vi")]),

    R("mang_tay_xao_tom", "Măng tây xào tôm tỏi", "mon_chinh", "am", "nhe", "vua", "mang_tay", "moi", 15, "de",
      "Măng tây xanh Ninh Thuận xào tôm với tỏi Phan Rang – nhanh gọn, giữ giòn.",
      ["Tôm bóc vỏ; măng tây bỏ phần gốc xơ, cắt khúc 4–5cm.",
       "Phi thơm tỏi, xào tôm đến đỏ, nêm hạt nêm và dầu hào.",
       "Cho măng tây vào xào lửa lớn, thêm 3–4 muỗng nước, đảo 2 phút.",
       "Rắc tiêu, nêm lại rồi tắt bếp."],
      19, CP + "16494256",
      [("mang_tay", "Măng tây", 500, "g", "n", "chinh"),
       ("tom_the", "Tôm", 300, "g", "n", "phu"),
       ("toi_pr", "Tỏi Phan Rang", 4, "tép", "x", "gia_vi"),
       ("", "Dầu hào", 2, MC, "x", "gia_vi"),
       ("", "Dầu ăn", 2, MC, "x", "gia_vi"),
       ("", "Hạt nêm", 1, MCF, "x", "gia_vi")]),

    R("lau_ga_la_e", "Lẩu gà lá é", "lau", "nong", "nang", "vua", "ga_ta", "mua", 60, "vua",
      "Lẩu gà ta nấu măng chua, lá é, nhúng nấm Đà Lạt – món mưa của vùng cao nguyên.",
      ["Măng chua thái lát, luộc qua 2–3 nước.",
       "Gà xát muối chanh, chặt miếng, ướp muối và một phần lá é xay.",
       "Phi hành tím, đảo gà săn, đổ khoảng 2,5 lít nước, ninh 20 phút với tiêu xanh, ớt hiểm.",
       "Cho măng vào, nêm lại; khi ăn nhúng nấm và lá é.",
       "Chấm muối lá é: muối, đường, tỏi, ớt giã với lá é."],
      31, CP + "17047170",
      [("ga_ta", "Gà ta", 1200, "g", "n", "chinh"),
       ("", "Lá é", 100, "g", "x", "gia_vi"),
       ("", "Măng chua", 300, "g", "n", "phu"),
       ("nam", "Nấm các loại", 400, "g", "n", "phu"),
       ("sa_ot", "Ớt hiểm", 10, "quả", "x", "gia_vi"),
       ("", "Tiêu xanh", 2, "nhánh", "x", "gia_vi"),
       ("hanh_tim", "Hành tím", 3, "củ", "x", "gia_vi"),
       ("bun", "Bún", 500, "g", "n", "phu")]),

    R("sinh_to_bo", "Sinh tố bơ", "do_uong", "mat", "nhe", "it", "bo_booth|bo_sap", "nang", 5, "de",
      "Bơ xay sữa đá – mát, béo, no lâu.",
      ["Nạo lấy thịt bơ.",
       "Xay bơ cùng sữa tươi, sữa đặc và đá đến mịn.",
       "Rót ra ly, dùng ngay."],
      159, CP + "26435337",
      [("bo_booth|bo_sap", "Bơ", 1, "trái lớn", "n", "chinh"),
       ("", "Sữa tươi", 200, "ml", "n", "phu"),
       ("", "Sữa đặc", 60, "g", "x", "gia_vi"),
       ("", "Đá viên", 2, "ly", "n", "phu")], khau_phan=2),

    R("nuoc_ep_nho", "Nước ép nho Ninh Thuận", "do_uong", "mat", "nhe", "it", "nho_nt", "nang", 10, "de",
      "Nho xanh Ninh Thuận ép với bạc hà và chanh – chua dịu, giải khát.",
      ["Ngâm nho nước muối loãng 5 phút, rửa sạch, bỏ cuống và hạt.",
       "Ép hoặc xay nho cùng lá bạc hà, lọc lấy nước.",
       "Thêm nước cốt chanh, đường tuỳ khẩu vị, đá viên."],
      7, CP + "16647657",
      [("nho_nt", "Nho xanh Ninh Thuận", 600, "g", "n", "chinh"),
       ("", "Chanh", 1, "quả", "x", "gia_vi"),
       ("", "Lá bạc hà", 4, "nhánh", "x", "phu"),
       ("", "Đường", None, "vừa đủ", "x", "gia_vi")], khau_phan=2),

    R("canh_bap_cai_cuon", "Canh bắp cải cuộn thịt", "canh", "am", "nhe", "it", "bap_cai", "moi", 50, "vua",
      "Lá bắp cải Đà Lạt cuộn thịt băm nấm mèo, nấu canh thanh.",
      ["Tách lá bắp cải, trụng sơ cho mềm.",
       "Trộn thịt xay với nấm mèo băm, tỏi, tiêu, hạt nêm.",
       "Cuộn thịt trong lá cải, buộc bằng cọng hành lá trụng.",
       "Đun sôi 1,5 lít nước dùng, thả cuộn bắp cải vào nấu 15–20 phút, nêm vừa ăn, rắc hành ngò, tiêu."],
      23, CP + "24825589",
      [("bap_cai", "Bắp cải (lá)", 16, "lá", "n", "chinh"),
       ("thit_heo", "Thịt heo xay", 300, "g", "n", "phu"),
       ("nam", "Nấm mèo", 3, "tai", "x", "phu"),
       ("", "Hành lá (để buộc)", 1, "bó", "x", "phu"),
       ("toi_pr", "Tỏi", 2, "tép", "x", "gia_vi"),
       ("", "Nước dùng", 1.5, "lít", "x", "gia_vi")]),

    R("sup_lo_xao_nam", "Súp lơ xanh xào nấm", "mon_chinh", "am", "nhe", "vua", "sup_lo", "moi", 20, "de",
      "Súp lơ, nấm, cà rốt Đà Lạt xào tỏi – món rau nhanh.",
      ["Súp lơ cắt nhánh, ngâm nước muối; nấm xé miếng; cà rốt thái lát.",
       "Trụng súp lơ và cà rốt 1 phút với chút muối để giữ màu.",
       "Phi tỏi, cho nấm vào xào săn, thêm súp lơ, cà rốt, dầu hào, hạt nêm.",
       "Đảo nhanh 1–2 phút, rắc tiêu, tắt bếp."],
      26, CP + "25413787",
      [("sup_lo", "Súp lơ xanh", 400, "g", "n", "chinh"),
       ("nam", "Nấm bào ngư hoặc nấm đùi gà", 200, "g", "n", "phu"),
       ("ca_rot", "Cà rốt", 80, "g", "n", "phu"),
       ("toi_pr", "Tỏi", 4, "tép", "x", "gia_vi"),
       ("", "Dầu hào", 1, MC, "x", "gia_vi"),
       ("", "Dầu ăn", 2, MC, "x", "gia_vi")]),

    R("canh_atiso_gio_heo", "Canh atiso hầm giò heo", "canh", "nong", "nang", "vua", "atiso", "mua", 90, "de",
      "Bông atiso tươi Đà Lạt hầm giò heo – bổ, mát gan. Chỉ có atiso tươi mùa 1–4.",
      ["Atiso bổ nhỏ, bỏ nhụy, rửa sạch.",
       "Giò heo chặt khoanh, trụng nước sôi rồi rửa lại.",
       "Nấu sôi khoảng 2,5 lít nước với hành tím đập, muối, nước mắm, đường; cho giò và atiso vào.",
       "Hầm lửa nhỏ đến khi giò mềm (khoảng 1 tiếng), nêm lại, thêm hành ngò, tiêu."],
      6, CP + "26303749",
      [("atiso", "Atiso tươi", 2, "bông", "n", "chinh"),
       ("thit_heo", "Giò heo", 1000, "g", "n", "chinh"),
       ("hanh_tim", "Hành tím", 5, "củ", "x", "gia_vi"),
       ("mam_ca_na", "Nước mắm", 1, MC, "x", "gia_vi"),
       ("", "Hành ngò", 1, "bó", "x", "phu")]),

    R("su_su_xao_trung", "Su su xào trứng", "mon_chinh", "am", "nhe", "vua", "su_su", "moi", 20, "de",
      "Su su Đà Lạt xào trứng – món rau nhà làm nhanh, rẻ.",
      ["Đánh trứng với chút nước mắm và tiêu; phi hành tỏi, chiên trứng đảo tơi rồi trút ra.",
       "Su su gọt vỏ, thái sợi, xào lửa lớn với chút muối.",
       "Khi su su vừa mềm, cho trứng vào đảo đều, thêm hành ngò, tiêu."],
      63, CP + "24286175",
      [("su_su", "Su su", 600, "g", "n", "chinh"),
       ("trung", "Trứng gà", 4, "quả", "n", "phu"),
       ("toi_pr", "Hành tỏi băm", 2, MCF, "x", "gia_vi"),
       ("mam_ca_na", "Nước mắm", 1, MC, "x", "gia_vi"),
       ("", "Dầu ăn", 2, MC, "x", "gia_vi")]),

    R("canh_suon_khoai_ca_rot", "Canh sườn khoai tây cà rốt", "canh", "nong", "nhe", "it", "khoai_tay", "mua", 60, "de",
      "Canh sườn hầm khoai tây, cà rốt Đà Lạt – ngọt nước, dễ ăn cho cả nhà.",
      ["Sườn chặt miếng, trụng sơ, ướp chút muối hạt nêm.",
       "Ninh sườn với khoảng 1,5 lít nước 30 phút.",
       "Cho khoai tây, cà rốt cắt miếng vào nấu thêm 15 phút đến mềm.",
       "Thêm cà chua, hành ngò, nêm vừa ăn, sôi lại 2 phút rồi tắt bếp."],
      9, CP + "13238803",
      [("thit_heo", "Sườn non", 500, "g", "n", "phu"),
       ("khoai_tay", "Khoai tây", 400, "g", "n", "chinh"),
       ("ca_rot", "Cà rốt", 300, "g", "n", "chinh"),
       ("ca_chua", "Cà chua", 1, "quả", "x", "phu"),
       ("", "Hành ngò", 1, "bó", "x", "phu")]),

    R("ca_ngu_kho_thom", "Cá ngừ kho thơm", "mon_chinh", "am", "nang", "vua", "ca_ngu_dd", "moi", 45, "de",
      "Cá ngừ chiên sơ kho với thơm và nước dừa – đậm đà ăn cơm.",
      ["Cá ngừ rửa sạch, cắt lát dày, chiên vàng hai mặt.",
       "Phi hành tím, cho thơm thái lát vào đảo sơ.",
       "Đổ nước dừa, nước mắm, đường, nước màu; cho cá vào đun sôi.",
       "Hạ lửa nhỏ kho đến khi nước sánh lại, thêm ớt, tiêu."],
      60, CP + "25064711",
      [("ca_ngu_dd", "Cá ngừ tươi", 600, "g", "n", "chinh"),
       ("", "Thơm (dứa)", 300, "g", "n", "phu"),
       ("", "Nước dừa", 300, "ml", "x", "gia_vi"),
       ("hanh_tim", "Hành tím", 3, "củ", "x", "gia_vi"),
       ("mam_ca_na", "Nước mắm", 3, MC, "x", "gia_vi"),
       ("", "Đường", 1, MC, "x", "gia_vi"),
       ("", "Nước màu", 1, MC, "x", "gia_vi")]),

    R("goi_cuon", "Gỏi cuốn tôm thịt", "goi", "mat", "nhe", "it", "tom_the", "nang", 60, "de",
      "Bánh tráng cuốn tôm, thịt luộc, bún, rau sống – không dầu mỡ, hợp ngày nắng.",
      ["Thịt ba rọi luộc chín, để nguội, thái mỏng.",
       "Tôm luộc, bóc vỏ, chẻ đôi.",
       "Trụng bún; rửa xà lách, rau thơm, hẹ.",
       "Cuốn bánh tráng với rau, bún, thịt, tôm.",
       "Chấm tương đen đậu phộng hoặc nước mắm tỏi ớt."],
      23, CP + "25705081",
      [("tom_the", "Tôm", 300, "g", "n", "chinh"),
       ("thit_heo", "Thịt ba rọi", 400, "g", "n", "phu"),
       ("bun", "Bún", 300, "g", "n", "phu"),
       ("banh_trang", "Bánh tráng", 20, "lá", "n", "phu"),
       ("rau_thom", "Xà lách, rau thơm, hẹ", 300, "g", "n", "phu"),
       ("", "Tương đen", 4, MC, "x", "gia_vi"),
       ("dau_phong", "Đậu phộng giã", 2, MC, "x", "gia_vi")]),

    R("sua_chua_dau_tay", "Sữa chua dâu tây", "trang_mieng", "mat", "nhe", "it", "dau_tay", "moi", 10, "de",
      "Sữa chua với dâu tây Đà Lạt, mật ong, hạt – tráng miệng mùa dâu (11–4).",
      ["Dâu tây ngâm nước muối loãng, rửa, bỏ cuống, cắt đôi.",
       "Trộn dâu với mật ong, để 10 phút cho ra nước.",
       "Cho sữa chua ra ly, thêm dâu và hạt/granola lên trên."],
      27, CP + "17049946",
      [("dau_tay", "Dâu tây", 200, "g", "n", "chinh"),
       ("", "Sữa chua", 2, "hũ", "n", "phu"),
       ("", "Mật ong", 2, MC, "x", "gia_vi"),
       ("", "Granola hoặc hạt", 40, "g", "n", "phu")], khau_phan=2),
]
